package com.home.commonGame.net.request.quest;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送领取成就奖励成功消息(generated by shine) */
public class SendGetAchievementRewardSuccessRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.SendGetAchievementRewardSuccess;
	
	/** id */
	public int id;
	
	public SendGetAchievementRewardSuccessRequest()
	{
		_dataID=GameRequestType.SendGetAchievementRewardSuccess;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendGetAchievementRewardSuccessRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("id");
		writer.sb.append(':');
		writer.sb.append(this.id);
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.id);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.id=0;
	}
	
	/** 创建实例 */
	public static SendGetAchievementRewardSuccessRequest create(int id)
	{
		SendGetAchievementRewardSuccessRequest re=(SendGetAchievementRewardSuccessRequest)BytesControl.createRequest(dataID);
		re.id=id;
		return re;
	}
	
}
