package com.home.commonGame.net.serverRequest.scene.login;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.scene.scene.SceneServerEnterData;
import com.home.commonGame.net.serverRequest.scene.base.GameToSceneServerRequest;
import com.home.commonGame.net.serverRequest.scene.base.PlayerGameToSceneServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 玩家进入场景服消息(generated by shine) */
public class PlayerEnterServerSceneServerRequest extends PlayerGameToSceneServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.PlayerEnterServerScene;
	
	/** 携带数据 */
	public SceneServerEnterData data;
	
	public PlayerEnterServerSceneServerRequest()
	{
		_dataID=ServerMessageType.PlayerEnterServerScene;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		SceneServerEnterData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(SceneServerEnterData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "PlayerEnterServerSceneServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("SceneServerEnterData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static PlayerEnterServerSceneServerRequest create(long playerID,SceneServerEnterData data)
	{
		PlayerEnterServerSceneServerRequest re=(PlayerEnterServerSceneServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.data=data;
		return re;
	}
	
}
