package com.home.commonClient.net.sceneRequest.scene;
import com.home.commonClient.constlist.generate.SceneRequestType;
import com.home.commonClient.net.base.SceneRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** (generated by shine) */
public class PreEnterSceneReadyForSceneRequest extends SceneRequest
{
	/** 数据类型ID */
	public static final int dataID=SceneRequestType.PreEnterSceneReadyForScene;
	
	public PreEnterSceneReadyForSceneRequest()
	{
		_dataID=SceneRequestType.PreEnterSceneReadyForScene;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "PreEnterSceneReadyForSceneRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 创建实例 */
	public static PreEnterSceneReadyForSceneRequest create()
	{
		PreEnterSceneReadyForSceneRequest re=(PreEnterSceneReadyForSceneRequest)BytesControl.createRequest(dataID);
		return re;
	}
	
}
