package com.home.commonClient.net.request.mail;
import com.home.commonBase.data.mail.MailData;
import com.home.commonClient.constlist.generate.GameRequestType;
import com.home.commonClient.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 客户端发送邮件消息(generated by shine) */
public class ClientSendMailRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.ClientSendMail;
	
	/** 目标玩家ID */
	public long playerID;
	
	/** 邮件数据 */
	public MailData mail;
	
	public ClientSendMailRequest()
	{
		_dataID=GameRequestType.ClientSendMail;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		MailData mailTemp=mail;
		if(mailTemp!=null)
		{
			this.mail=(MailData)mailTemp.clone();
		}
		else
		{
			this.mail=null;
			nullObjError("mail");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ClientSendMailRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("playerID");
		writer.sb.append(':');
		writer.sb.append(this.playerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("mail");
		writer.sb.append(':');
		if(this.mail!=null)
		{
			this.mail.writeDataString(writer);
		}
		else
		{
			writer.sb.append("MailData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeLong(this.playerID);
		
		if(this.mail!=null)
		{
			stream.writeDataFullNotNull(this.mail);
		}
		else
		{
			nullObjError("mail");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.playerID);
		
		if(this.mail!=null)
		{
			stream.writeDataSimpleNotNull(this.mail);
		}
		else
		{
			nullObjError("mail");
		}
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.playerID=0L;
		this.mail.release(pool);
		this.mail=null;
	}
	
	/** 创建实例 */
	public static ClientSendMailRequest create(long playerID,MailData mail)
	{
		ClientSendMailRequest re=(ClientSendMailRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.mail=mail;
		return re;
	}
	
}
