package com.home.commonCenter.net.serverRequest.game.func.rank.subsection;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonCenter.net.serverRequest.game.func.base.FuncCenterToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 重置排行榜到game服(generated by shine) */
public class FuncResetSubsectionRankToGameServerRequest extends FuncCenterToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncResetSubsectionRankToGame;
	
	/** 新版本号 */
	public int version;
	
	public FuncResetSubsectionRankToGameServerRequest()
	{
		_dataID=ServerMessageType.FuncResetSubsectionRankToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncResetSubsectionRankToGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.version);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("version");
		writer.sb.append(':');
		writer.sb.append(this.version);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.version=0;
	}
	
	/** 创建实例 */
	public static FuncResetSubsectionRankToGameServerRequest create(int funcID,int version)
	{
		FuncResetSubsectionRankToGameServerRequest re=(FuncResetSubsectionRankToGameServerRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.version=version;
		return re;
	}
	
}
