package com.home.commonGame.net.serverRequest.center.func.match;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.scene.match.PlayerMatchData;
import com.home.commonGame.net.serverRequest.center.base.PlayerToCenterServerRequest;
import com.home.commonGame.net.serverRequest.center.func.base.FuncPlayerToCenterServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 申请匹配到中心服(generated by shine) */
public class FuncApplyMatchToCenterServerRequest extends FuncPlayerToCenterServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncApplyMatchToCenter;
	
	/** 匹配数据 */
	public PlayerMatchData matchData;
	
	public FuncApplyMatchToCenterServerRequest()
	{
		_dataID=ServerMessageType.FuncApplyMatchToCenter;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		PlayerMatchData matchDataTemp=matchData;
		if(matchDataTemp!=null)
		{
			this.matchData=(PlayerMatchData)matchDataTemp.clone();
		}
		else
		{
			this.matchData=null;
			nullObjError("matchData");
		}
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.matchData!=null)
		{
			stream.writeDataSimpleNotNull(this.matchData);
		}
		else
		{
			nullObjError("matchData");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncApplyMatchToCenterServerRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("matchData");
		writer.sb.append(':');
		if(this.matchData!=null)
		{
			this.matchData.writeDataString(writer);
		}
		else
		{
			writer.sb.append("PlayerMatchData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.matchData.release(pool);
		this.matchData=null;
	}
	
	/** 创建实例 */
	public static FuncApplyMatchToCenterServerRequest create(long playerID,int funcID,PlayerMatchData matchData)
	{
		FuncApplyMatchToCenterServerRequest re=(FuncApplyMatchToCenterServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.funcID=funcID;
		re.matchData=matchData;
		return re;
	}
	
}
