package com.home.commonGame.net.serverRequest.center.func.match;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.net.serverRequest.center.base.PlayerToCenterServerRequest;
import com.home.commonGame.net.serverRequest.center.func.base.FuncPlayerToCenterServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** 功能申请需要匹配到中心服(generated by shine) */
public class FuncApplyCancelMatchToCenterServerRequest extends FuncPlayerToCenterServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncApplyCancelMatchToCenter;
	
	public FuncApplyCancelMatchToCenterServerRequest()
	{
		_dataID=ServerMessageType.FuncApplyCancelMatchToCenter;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncApplyCancelMatchToCenterServerRequest";
	}
	
	/** 创建实例 */
	public static FuncApplyCancelMatchToCenterServerRequest create(long playerID,int funcID)
	{
		FuncApplyCancelMatchToCenterServerRequest re=(FuncApplyCancelMatchToCenterServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.funcID=funcID;
		return re;
	}
	
}
