package com.home.commonGame.net.serverRequest.center.func.auction;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.net.serverRequest.center.func.base.FuncPlayerToCenterServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 取消上架物品到拍卖行(generated by shine) */
public class FuncSendAuctionCancelSellItemToCenterServerRequest extends FuncPlayerToCenterServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncSendAuctionCancelSellItemToCenter;
	
	public int reason;
	
	public long instanceID;
	
	public FuncSendAuctionCancelSellItemToCenterServerRequest()
	{
		_dataID=ServerMessageType.FuncSendAuctionCancelSellItemToCenter;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendAuctionCancelSellItemToCenterServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.instanceID);
		
		stream.writeInt(this.reason);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("instanceID");
		writer.sb.append(':');
		writer.sb.append(this.instanceID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("reason");
		writer.sb.append(':');
		writer.sb.append(this.reason);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.instanceID=0L;
		this.reason=0;
	}
	
	/** 创建实例 */
	public static FuncSendAuctionCancelSellItemToCenterServerRequest create(long playerID,int funcID,long instanceID,int reason)
	{
		FuncSendAuctionCancelSellItemToCenterServerRequest re=(FuncSendAuctionCancelSellItemToCenterServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.funcID=funcID;
		re.instanceID=instanceID;
		re.reason=reason;
		return re;
	}
	
}
