package com.home.commonGame.net.request.role;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 更改角色名字消息(generated by shine) */
public class ChangeRoleNameRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.ChangeRoleName;
	
	/** 名字 */
	public String name="";
	
	public ChangeRoleNameRequest()
	{
		_dataID=GameRequestType.ChangeRoleName;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ChangeRoleNameRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("name");
		writer.sb.append(':');
		writer.sb.append(this.name);
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeUTF(this.name);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeUTF(this.name);
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.name="";
	}
	
	/** 创建实例 */
	public static ChangeRoleNameRequest create(String name)
	{
		ChangeRoleNameRequest re=(ChangeRoleNameRequest)BytesControl.createRequest(dataID);
		re.name=name;
		return re;
	}
	
}
