package com.home.commonGame.net.request.role;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 刷新角色战斗力消息(generated by shine) */
public class RefreshFightForceRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.RefreshFightForce;
	
	/** 战斗力 */
	public long fightForce;
	
	public RefreshFightForceRequest()
	{
		_dataID=GameRequestType.RefreshFightForce;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "RefreshFightForceRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeLong(this.fightForce);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.fightForce);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("fightForce");
		writer.sb.append(':');
		writer.sb.append(this.fightForce);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.fightForce=0L;
	}
	
	/** 创建实例 */
	public static RefreshFightForceRequest create(long fightForce)
	{
		RefreshFightForceRequest re=(RefreshFightForceRequest)BytesControl.createRequest(dataID);
		re.fightForce=fightForce;
		return re;
	}
	
}
