package com.home.commonGame.net.serverResponse.login.system;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.global.GameC;
import com.home.commonGame.net.serverRequest.login.system.ReBeLoginToGameServerRequest;
import com.home.commonGame.net.serverResponse.login.base.LoginToGameServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.constlist.SocketType;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** (generated by shine) */
public class BeLoginToGameServerResponse extends LoginToGameServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.BeLoginToGame;
	
	public int id;
	
	public BeLoginToGameServerResponse()
	{
		_dataID=ServerMessageType.BeLoginToGame;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "BeLoginToGameServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("id");
		writer.sb.append(':');
		writer.sb.append(this.id);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		GameC.server.getSocketInfo(SocketType.Login).registerSocket(id,socket);
		socket.send(ReBeLoginToGameServerRequest.create(GameC.main.getAreaDatas()));
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.id=0;
	}
	
}
