package com.home.commonClient.net.response.social.friend;
import com.home.commonBase.data.social.friend.ApplyAddFriendData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.base.GameResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送申请添加好友消息(generated by shine) */
public class SendApplyAddFriendResponse extends GameResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.SendApplyAddFriend;
	
	/** 申请数据 */
	public ApplyAddFriendData applyData;
	
	public SendApplyAddFriendResponse()
	{
		_dataID=GameResponseType.SendApplyAddFriend;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		me.friend.onApplyAddFriend(applyData);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendApplyAddFriendResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		BaseData applyDataT=stream.readDataFullNotNull();
		if(applyDataT!=null)
		{
			if(applyDataT instanceof ApplyAddFriendData)
			{
				this.applyData=(ApplyAddFriendData)applyDataT;
			}
			else
			{
				this.applyData=new ApplyAddFriendData();
				if(!(applyDataT.getClass().isAssignableFrom(ApplyAddFriendData.class)))
				{
					stream.throwTypeReadError(ApplyAddFriendData.class,applyDataT.getClass());
				}
				this.applyData.shadowCopy(applyDataT);
			}
		}
		else
		{
			this.applyData=null;
		}
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.applyData=(ApplyAddFriendData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("applyData");
		writer.sb.append(':');
		if(this.applyData!=null)
		{
			this.applyData.writeDataString(writer);
		}
		else
		{
			writer.sb.append("ApplyAddFriendData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.applyData=null;
	}
	
}
