package com.home.commonGame.net.request.scene.syncScene;
import com.home.commonBase.data.scene.fight.FrameSyncData;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.request.scene.base.SceneSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.SList;
import com.home.shine.support.pool.DataPool;

/** 帧同步起始消息(generated by shine) */
public class FrameSyncStartRequest extends SceneSRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FrameSyncStart;
	
	/** 数据组 */
	public SList<FrameSyncData> list;
	
	public FrameSyncStartRequest()
	{
		_dataID=GameRequestType.FrameSyncStart;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		SList<FrameSyncData> listTemp=list;
		if(listTemp!=null)
		{
			this.list=new SList<FrameSyncData>(FrameSyncData[]::new,listTemp.size());
			SList<FrameSyncData> listT=this.list;
			if(!listTemp.isEmpty())
			{
				Object[] listVValues=listTemp.getValues();
				for(int listVI=0,listVLen=listTemp.length();listVI<listVLen;++listVI)
				{
					FrameSyncData listV=(FrameSyncData)listVValues[listVI];
					FrameSyncData listU;
					if(listV!=null)
					{
						listU=(FrameSyncData)listV.clone();
					}
					else
					{
						listU=null;
						nullObjError("listU");
					}
					
					listT.add(listU);
				}
			}
		}
		else
		{
			this.list=null;
			nullObjError("list");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FrameSyncStartRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("list");
		writer.sb.append(':');
		writer.sb.append("List<FrameSyncData>");
		if(this.list!=null)
		{
			SList<FrameSyncData> listT=this.list;
			int listLen=listT.size();
			writer.sb.append('(');
			writer.sb.append(listLen);
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			for(int listI=0;listI<listLen;++listI)
			{
				FrameSyncData listV=listT.get(listI);
				writer.writeTabs();
				writer.sb.append(listI);
				writer.sb.append(':');
				if(listV!=null)
				{
					listV.writeDataString(writer);
				}
				else
				{
					writer.sb.append("FrameSyncData=null");
				}
				
				writer.writeEnter();
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		if(this.list!=null)
		{
			stream.writeLen(this.list.size());
			if(!this.list.isEmpty())
			{
				Object[] listVValues=this.list.getValues();
				for(int listVI=0,listVLen=this.list.length();listVI<listVLen;++listVI)
				{
					FrameSyncData listV=(FrameSyncData)listVValues[listVI];
					if(listV!=null)
					{
						stream.writeDataFullNotNull(listV);
					}
					else
					{
						nullObjError("listV");
					}
					
				}
			}
		}
		else
		{
			nullObjError("list");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.list!=null)
		{
			stream.writeLen(this.list.size());
			if(!this.list.isEmpty())
			{
				Object[] listVValues=this.list.getValues();
				for(int listVI=0,listVLen=this.list.length();listVI<listVLen;++listVI)
				{
					FrameSyncData listV=(FrameSyncData)listVValues[listVI];
					if(listV!=null)
					{
						stream.writeDataSimpleNotNull(listV);
					}
					else
					{
						nullObjError("listV");
					}
					
				}
			}
		}
		else
		{
			nullObjError("list");
		}
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		if(this.list!=null)
		{
			if(!this.list.isEmpty())
			{
				Object[] listVValues=this.list.getValues();
				for(int listVI=0,listVLen=this.list.length();listVI<listVLen;++listVI)
				{
					FrameSyncData listV=(FrameSyncData)listVValues[listVI];
					listV.release(pool);
					listV=null;
					listVValues[listVI]=null;
				}
			}
			this.list.justClearSize();
		}
	}
	
	/** 创建实例 */
	public static FrameSyncStartRequest create(SList<FrameSyncData> list)
	{
		FrameSyncStartRequest re=(FrameSyncStartRequest)BytesControl.createRequest(dataID);
		re.list=list;
		return re;
	}
	
}
