package com.home.commonGame.net.serverResponse.center.system;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.global.GameC;
import com.home.commonGame.net.request.system.CenterTransGameToClientRequest;
import com.home.commonGame.net.serverResponse.center.base.CenterToGameServerResponse;
import com.home.commonGame.part.player.Player;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.net.base.BaseResponse;
import com.home.shine.server.BaseServer;

/** 中心服转发消息(generated by shine) */
public class CenterTransCenterToGameServerResponse extends CenterToGameServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.CenterTransCenterToGame;
	
	private byte[] _data;
	
	private long _playerID;
	
	public CenterTransCenterToGameServerResponse()
	{
		_dataID=ServerMessageType.CenterTransCenterToGame;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		GameC.gameSwitch.addPlayerCenterRequest(_playerID,_data);
	}
	
	@Override
	public BaseResponse readFromStream(BytesReadStream stream,BaseServer server)
	{
		_playerID=stream.readLong();
		_data=stream.getByteArrayFromPos();
		
		return this;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CenterTransCenterToGameServerResponse";
	}
	
}
