package com.home.commonClient.net.request.func.aution;
import com.home.commonClient.constlist.generate.GameRequestType;
import com.home.commonClient.net.request.func.base.FuncRRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 上架拍卖行物品消息(generated by shine) */
public class FuncAuctionSellItemRequest extends FuncRRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncAuctionSellItem;
	
	/** 物品id */
	public int itemID;
	
	/** 物品格子 */
	public int index;
	
	/** 上架数目 */
	public int num;
	
	/** 单价 */
	public int onePrice;
	
	public FuncAuctionSellItemRequest()
	{
		_dataID=GameRequestType.FuncAuctionSellItem;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncAuctionSellItemRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.index);
		
		stream.writeInt(this.itemID);
		
		stream.writeInt(this.num);
		
		stream.writeInt(this.onePrice);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.index);
		
		stream.writeInt(this.itemID);
		
		stream.writeInt(this.num);
		
		stream.writeInt(this.onePrice);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("index");
		writer.sb.append(':');
		writer.sb.append(this.index);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("itemID");
		writer.sb.append(':');
		writer.sb.append(this.itemID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("num");
		writer.sb.append(':');
		writer.sb.append(this.num);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("onePrice");
		writer.sb.append(':');
		writer.sb.append(this.onePrice);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.index=0;
		this.itemID=0;
		this.num=0;
		this.onePrice=0;
	}
	
	/** 创建实例 */
	public static FuncAuctionSellItemRequest create(int funcID,int index,int itemID,int num,int onePrice)
	{
		FuncAuctionSellItemRequest re=(FuncAuctionSellItemRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.index=index;
		re.itemID=itemID;
		re.num=num;
		re.onePrice=onePrice;
		return re;
	}
	
}
