package com.home.commonClient.net.response.func.roleGroup;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.response.func.base.FuncPlayerRoleGroupSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送更换队长消息(generated by shine) */
public class FuncSendChangeLeaderRoleGroupResponse extends FuncPlayerRoleGroupSResponse
{
	/** 上次队长 */
	public long lastLeader;
	
	/** 数据类型ID */
	public static final int dataID=GameResponseType.FuncSendChangeLeaderRoleGroup;
	
	/** 现在的队长 */
	public long nowLeader;
	
	public FuncSendChangeLeaderRoleGroupResponse()
	{
		_dataID=GameResponseType.FuncSendChangeLeaderRoleGroup;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendChangeLeaderRoleGroupResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.lastLeader=stream.readLong();
		
		this.nowLeader=stream.readLong();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.lastLeader=stream.readLong();
		
		this.nowLeader=stream.readLong();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("lastLeader");
		writer.sb.append(':');
		writer.sb.append(this.lastLeader);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("nowLeader");
		writer.sb.append(':');
		writer.sb.append(this.nowLeader);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		roleGroup.onChangeLeader(lastLeader,nowLeader);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.lastLeader=0L;
		this.nowLeader=0L;
	}
	
}
