package com.home.commonClient.net.response.func.roleGroup;
import com.home.commonBase.data.social.roleGroup.PlayerRoleGroupData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.response.func.base.FuncSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送添加玩家群消息(generated by shine) */
public class FuncSendPlayerJoinRoleGroupResponse extends FuncSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.FuncSendPlayerJoinRoleGroup;
	
	/** 方式 */
	public int type;
	
	/** 玩家群数据 */
	public PlayerRoleGroupData data;
	
	public FuncSendPlayerJoinRoleGroupResponse()
	{
		_dataID=GameResponseType.FuncSendPlayerJoinRoleGroup;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendPlayerJoinRoleGroupResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		BaseData dataT=stream.readDataFullNotNull();
		if(dataT!=null)
		{
			if(dataT instanceof PlayerRoleGroupData)
			{
				this.data=(PlayerRoleGroupData)dataT;
			}
			else
			{
				this.data=new PlayerRoleGroupData();
				if(!(dataT.getClass().isAssignableFrom(PlayerRoleGroupData.class)))
				{
					stream.throwTypeReadError(PlayerRoleGroupData.class,dataT.getClass());
				}
				this.data.shadowCopy(dataT);
			}
		}
		else
		{
			this.data=null;
		}
		
		this.type=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.data=(PlayerRoleGroupData)stream.readDataSimpleNotNull();
		
		this.type=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("PlayerRoleGroupData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("type");
		writer.sb.append(':');
		writer.sb.append(this.type);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		me.func.getRoleGroupTool(funcID).onJoinRoleGroup(data,type);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data=null;
		this.type=0;
	}
	
}
