package com.home.commonClient.net.response.func.roleGroup;
import com.home.commonBase.data.social.roleGroup.PlayerApplyRoleGroupSelfData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.response.func.base.FuncSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 添加申请玩家群到自身消息(generated by shine) */
public class FuncSendAddApplyRoleGroupSelfResponse extends FuncSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.FuncSendAddApplyRoleGroupSelf;
	
	/** 数据 */
	public PlayerApplyRoleGroupSelfData data;
	
	public FuncSendAddApplyRoleGroupSelfResponse()
	{
		_dataID=GameResponseType.FuncSendAddApplyRoleGroupSelf;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendAddApplyRoleGroupSelfResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		BaseData dataT=stream.readDataFullNotNull();
		if(dataT!=null)
		{
			if(dataT instanceof PlayerApplyRoleGroupSelfData)
			{
				this.data=(PlayerApplyRoleGroupSelfData)dataT;
			}
			else
			{
				this.data=new PlayerApplyRoleGroupSelfData();
				if(!(dataT.getClass().isAssignableFrom(PlayerApplyRoleGroupSelfData.class)))
				{
					stream.throwTypeReadError(PlayerApplyRoleGroupSelfData.class,dataT.getClass());
				}
				this.data.shadowCopy(dataT);
			}
		}
		else
		{
			this.data=null;
		}
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.data=(PlayerApplyRoleGroupSelfData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("PlayerApplyRoleGroupSelfData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		me.func.getRoleGroupTool(funcID).onAddApplySelf(data);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data=null;
	}
	
}
