package com.home.commonClient.net.response.func.roleGroup;
import com.home.commonBase.data.social.roleGroup.RoleGroupMemberChangeData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.response.func.base.FuncPlayerRoleGroupSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 玩家群成员数据改变消息(generated by shine) */
public class FuncSendRoleGroupMemberChangeResponse extends FuncPlayerRoleGroupSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.FuncSendRoleGroupMemberChange;
	
	public long memberID;
	
	public RoleGroupMemberChangeData data;
	
	public FuncSendRoleGroupMemberChangeResponse()
	{
		_dataID=GameResponseType.FuncSendRoleGroupMemberChange;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendRoleGroupMemberChangeResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.memberID=stream.readLong();
		
		BaseData dataT=stream.readDataFullNotNull();
		if(dataT!=null)
		{
			if(dataT instanceof RoleGroupMemberChangeData)
			{
				this.data=(RoleGroupMemberChangeData)dataT;
			}
			else
			{
				this.data=new RoleGroupMemberChangeData();
				if(!(dataT.getClass().isAssignableFrom(RoleGroupMemberChangeData.class)))
				{
					stream.throwTypeReadError(RoleGroupMemberChangeData.class,dataT.getClass());
				}
				this.data.shadowCopy(dataT);
			}
		}
		else
		{
			this.data=null;
		}
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.memberID=stream.readLong();
		
		this.data=(RoleGroupMemberChangeData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("memberID");
		writer.sb.append(':');
		writer.sb.append(this.memberID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RoleGroupMemberChangeData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.memberID=0L;
		this.data=null;
	}
	
}
