package com.home.commonManager.net.serverRequest.login;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonManager.net.serverRequest.login.base.ManagerToLoginServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送服务器开放状态到登陆服(generated by shine) */
public class SendServerOpenToLoginServerRequest extends ManagerToLoginServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.SendServerOpenToLogin;
	
	/** 当前开放状态 */
	public boolean isOpen;
	
	public SendServerOpenToLoginServerRequest()
	{
		_dataID=ServerMessageType.SendServerOpenToLogin;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendServerOpenToLoginServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeBoolean(this.isOpen);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("isOpen");
		writer.sb.append(':');
		writer.sb.append(this.isOpen);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.isOpen=false;
	}
	
	/** 创建实例 */
	public static SendServerOpenToLoginServerRequest create(boolean isOpen)
	{
		SendServerOpenToLoginServerRequest re=(SendServerOpenToLoginServerRequest)BytesControl.createRequest(dataID);
		re.isOpen=isOpen;
		return re;
	}
	
}
