namespace Shine
{
	/** 进入场景失败消息(generated by shine) */
	export class EnterSceneFailedResponse extends GameResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.EnterSceneFailed;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.EnterSceneFailed;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "EnterSceneFailedResponse";
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
