package com.home.commonBase.data.gm;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.system.PlayerWorkData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** 查询角色等级事务(测试)(generated by shine) */
public class QueryPlayerLevelWData extends PlayerWorkData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.QueryPlayerLevelW;
	
	public QueryPlayerLevelWData()
	{
		_dataID=BaseDataType.QueryPlayerLevelW;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "QueryPlayerLevelWData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
}
