namespace Shine
{
	/** 回复获取角色社交数据在线数据(generated by shine) */
	export class ReGetRoleSocialDataWData extends PlayerWorkData
	{
		/** 数据类型ID */
		public static dataID:number=BaseDataType.ReGetRoleSocialDataW;
		
		/** 获取类型 */
		public type:number;
		
		/** 目标角色ID */
		public playerID:number;
		
		/** 数据 */
		public data:RoleSocialData;
		
		/** 参数 */
		public arg:number;
		
		constructor()
		{
			super();
			this._dataID=BaseDataType.ReGetRoleSocialDataW;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "ReGetRoleSocialDataWData";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.type=stream.readInt();
			
			this.playerID=stream.readLong();
			
			if(stream.readBoolean())
			{
				this.data=stream.readDataSimpleNotNull() as RoleSocialData;
			}
			else
			{
				this.data=null;
			}
			
			this.arg=stream.readInt();
			
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			super.toWriteBytesSimple(stream);
			
			stream.writeInt(this.type);
			
			stream.writeLong(this.playerID);
			
			if(this.data!=null)
			{
				stream.writeBoolean(true);
				stream.writeDataSimpleNotNull(this.data);
			}
			else
			{
				stream.writeBoolean(false);
			}
			
			stream.writeInt(this.arg);
			
		}
		
		/** 复制(潜拷贝) */
		protected toShadowCopy(data:BaseData):void
		{
			super.toShadowCopy(data);
			
			if(!(data instanceof ReGetRoleSocialDataWData))
				return;
			
			var mData:ReGetRoleSocialDataWData=data as ReGetRoleSocialDataWData;
			
			this.type=mData.type;
			this.playerID=mData.playerID;
			this.data=mData.data;
			this.arg=mData.arg;
		}
		
		/** 复制(深拷贝) */
		protected toCopy(data:BaseData):void
		{
			super.toCopy(data);
			
			if(!(data instanceof ReGetRoleSocialDataWData))
				return;
			
			var mData:ReGetRoleSocialDataWData=data as ReGetRoleSocialDataWData;
			
			this.type=mData.type;
			
			this.playerID=mData.playerID;
			
			if(mData.data!=null)
			{
				this.data=mData.data.clone() as RoleSocialData;
			}
			else
			{
				this.data=null;
			}
			
			this.arg=mData.arg;
			
		}
		
		/** 初始化初值 */
		public initDefault():void
		{
			super.initDefault();
			
		}
		
	}
}
