package com.home.commonBase.data.social.friend;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.social.RoleSocialData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 申请添加好友数据(generated by shine) */
public class ApplyAddFriendData extends BaseData
{
	/** 角色ID */
	public long playerID;
	
	/** 数据类型ID */
	public static final int dataID=BaseDataType.ApplyAddFriend;
	
	/** 社交数据 */
	public RoleSocialData data;
	
	/** 添加类型 */
	public int type;
	
	/** 申请时间 */
	public long applyTime;
	
	public ApplyAddFriendData()
	{
		_dataID=BaseDataType.ApplyAddFriend;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ApplyAddFriendData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.playerID=stream.readLong();
		
		BaseData dataT=stream.readDataFullNotNull();
		if(dataT!=null)
		{
			if(dataT instanceof RoleSocialData)
			{
				this.data=(RoleSocialData)dataT;
			}
			else
			{
				this.data=new RoleSocialData();
				if(!(dataT.getClass().isAssignableFrom(RoleSocialData.class)))
				{
					stream.throwTypeReadError(RoleSocialData.class,dataT.getClass());
				}
				this.data.shadowCopy(dataT);
			}
		}
		else
		{
			this.data=null;
		}
		
		this.applyTime=stream.readLong();
		
		this.type=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeLong(this.playerID);
		
		if(this.data!=null)
		{
			stream.writeDataFullNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
		stream.writeLong(this.applyTime);
		
		stream.writeInt(this.type);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.playerID=stream.readLong();
		
		this.data=(RoleSocialData)stream.readDataSimpleNotNull();
		
		this.applyTime=stream.readLong();
		
		this.type=stream.readInt();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeLong(this.playerID);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
		stream.writeLong(this.applyTime);
		
		stream.writeInt(this.type);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof ApplyAddFriendData))
			return;
		
		ApplyAddFriendData mData=(ApplyAddFriendData)data;
		
		this.playerID=mData.playerID;
		this.data=mData.data;
		this.applyTime=mData.applyTime;
		this.type=mData.type;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof ApplyAddFriendData))
			return;
		
		ApplyAddFriendData mData=(ApplyAddFriendData)data;
		
		this.playerID=mData.playerID;
		
		if(mData.data!=null)
		{
			this.data=(RoleSocialData)mData.data.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
		this.applyTime=mData.applyTime;
		
		this.type=mData.type;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		ApplyAddFriendData mData=(ApplyAddFriendData)data;
		if(this.playerID!=mData.playerID)
			return false;
		
		if(mData.data!=null)
		{
			if(this.data==null)
				return false;
			if(!this.data.dataEquals(mData.data))
				return false;
		}
		else
		{
			if(this.data!=null)
				return false;
		}
		
		if(this.applyTime!=mData.applyTime)
			return false;
		
		if(this.type!=mData.type)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("playerID");
		writer.sb.append(':');
		writer.sb.append(this.playerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RoleSocialData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("applyTime");
		writer.sb.append(':');
		writer.sb.append(this.applyTime);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("type");
		writer.sb.append(':');
		writer.sb.append(this.type);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.data=new RoleSocialData();
		this.data.initDefault();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.playerID=0L;
		this.data=null;
		this.applyTime=0L;
		this.type=0;
	}
	
}
