using ShineEngine;

/// <summary>
/// 推送更换队长消息(generated by shine)
/// </summary>
public class FuncSendChangeLeaderRoleGroupResponse:FuncPlayerRoleGroupSResponse
{
	/// <summary>
	/// 上次队长
	/// </summary>
	public long lastLeader;
	
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=GameResponseType.FuncSendChangeLeaderRoleGroup;
	
	/// <summary>
	/// 现在的队长
	/// </summary>
	public long nowLeader;
	
	public FuncSendChangeLeaderRoleGroupResponse()
	{
		_dataID=GameResponseType.FuncSendChangeLeaderRoleGroup;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "FuncSendChangeLeaderRoleGroupResponse";
	}
	
	/// <summary>
	/// 读取字节流(完整版)
	/// </summary>
	protected override void toReadBytesFull(BytesReadStream stream)
	{
		base.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.lastLeader=stream.readLong();
		
		this.nowLeader=stream.readLong();
		
		stream.endReadObj();
	}
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		base.toReadBytesSimple(stream);
		
		this.lastLeader=stream.readLong();
		
		this.nowLeader=stream.readLong();
		
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("lastLeader");
		writer.sb.Append(':');
		writer.sb.Append(this.lastLeader);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("nowLeader");
		writer.sb.Append(':');
		writer.sb.Append(this.nowLeader);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 执行
	/// </summary>
	protected override void execute()
	{
		roleGroup.onChangeLeader(lastLeader,nowLeader);
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		this.lastLeader=0L;
		this.nowLeader=0L;
	}
	
}
