package com.home.commonClient.net.response.social;
import com.home.commonBase.data.social.friend.ContactData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.base.GameResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 返回搜索结果(generated by shine) */
public class ReSearchPlayerResponse extends GameResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.ReSearchPlayer;
	
	/** 结果 */
	public ContactData contact;
	
	public ReSearchPlayerResponse()
	{
		_dataID=GameResponseType.ReSearchPlayer;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ReSearchPlayerResponse";
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		BaseData contactT=stream.readDataFullNotNull();
		if(contactT!=null)
		{
			if(contactT instanceof ContactData)
			{
				this.contact=(ContactData)contactT;
			}
			else
			{
				this.contact=new ContactData();
				if(!(contactT.getClass().isAssignableFrom(ContactData.class)))
				{
					stream.throwTypeReadError(ContactData.class,contactT.getClass());
				}
				this.contact.shadowCopy(contactT);
			}
		}
		else
		{
			this.contact=null;
		}
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.contact=(ContactData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("contact");
		writer.sb.append(':');
		if(this.contact!=null)
		{
			this.contact.writeDataString(writer);
		}
		else
		{
			writer.sb.append("ContactData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.contact=null;
	}
	
}
