package com.home.commonBase.data.scene.unit;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.IntIntMap;
import com.home.shine.support.pool.DataPool;

/** 单位造型数据(generated by shine) */
public class UnitAvatarData extends BaseData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.UnitAvatar;
	
	/** 模型ID */
	public int modelID=-1;
	
	/** 显示部件组 */
	public IntIntMap parts;
	
	public UnitAvatarData()
	{
		_dataID=BaseDataType.UnitAvatar;
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.modelID=stream.readInt();
		
		int partsLen=stream.readLen();
		if(this.parts!=null)
		{
			this.parts.clear();
			this.parts.ensureCapacity(partsLen);
		}
		else
		{
			this.parts=new IntIntMap(partsLen);
		}
		
		IntIntMap partsT=this.parts;
		for(int partsI=partsLen-1;partsI>=0;--partsI)
		{
			int partsK;
			int partsV;
			partsK=stream.readInt();
			
			partsV=stream.readInt();
			
			partsT.put(partsK,partsV);
		}
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeInt(this.modelID);
		
		if(this.parts!=null)
		{
			stream.writeLen(this.parts.size());
			if(!this.parts.isEmpty())
			{
				int partsKFreeValue=this.parts.getFreeValue();
				int[] partsKTable=this.parts.getTable();
				for(int partsKI=partsKTable.length-2;partsKI>=0;partsKI-=2)
				{
					if(partsKTable[partsKI]!=partsKFreeValue)
					{
						int partsK=partsKTable[partsKI];
						int partsV=partsKTable[partsKI+1];
						stream.writeInt(partsK);
						
						stream.writeInt(partsV);
						
					}
				}
			}
		}
		else
		{
			nullObjError("parts");
		}
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.modelID=stream.readInt();
		
		int partsLen=stream.readLen();
		if(this.parts!=null)
		{
			this.parts.clear();
			this.parts.ensureCapacity(partsLen);
		}
		else
		{
			this.parts=new IntIntMap(partsLen);
		}
		
		IntIntMap partsT=this.parts;
		for(int partsI=partsLen-1;partsI>=0;--partsI)
		{
			int partsK;
			int partsV;
			partsK=stream.readInt();
			
			partsV=stream.readInt();
			
			partsT.put(partsK,partsV);
		}
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeInt(this.modelID);
		
		if(this.parts!=null)
		{
			stream.writeLen(this.parts.size());
			if(!this.parts.isEmpty())
			{
				int partsKFreeValue=this.parts.getFreeValue();
				int[] partsKTable=this.parts.getTable();
				for(int partsKI=partsKTable.length-2;partsKI>=0;partsKI-=2)
				{
					if(partsKTable[partsKI]!=partsKFreeValue)
					{
						int partsK=partsKTable[partsKI];
						int partsV=partsKTable[partsKI+1];
						stream.writeInt(partsK);
						
						stream.writeInt(partsV);
						
					}
				}
			}
		}
		else
		{
			nullObjError("parts");
		}
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof UnitAvatarData))
			return;
		
		UnitAvatarData mData=(UnitAvatarData)data;
		
		this.modelID=mData.modelID;
		this.parts=mData.parts;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof UnitAvatarData))
			return;
		
		UnitAvatarData mData=(UnitAvatarData)data;
		
		this.modelID=mData.modelID;
		
		if(mData.parts!=null)
		{
			if(this.parts!=null)
			{
				this.parts.clear();
				this.parts.ensureCapacity(mData.parts.size());
			}
			else
			{
				this.parts=new IntIntMap(mData.parts.size());
			}
			
			IntIntMap partsT=this.parts;
			if(!mData.parts.isEmpty())
			{
				int partsKFreeValue=mData.parts.getFreeValue();
				int[] partsKTable=mData.parts.getTable();
				for(int partsKI=partsKTable.length-2;partsKI>=0;partsKI-=2)
				{
					if(partsKTable[partsKI]!=partsKFreeValue)
					{
						int partsK=partsKTable[partsKI];
						int partsV=partsKTable[partsKI+1];
						int partsW;
						int partsU;
						partsW=partsK;
						
						partsU=partsV;
						
						partsT.put(partsW,partsU);
					}
				}
			}
		}
		else
		{
			this.parts=null;
			nullObjError("parts");
		}
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		UnitAvatarData mData=(UnitAvatarData)data;
		if(this.modelID!=mData.modelID)
			return false;
		
		if(mData.parts!=null)
		{
			if(this.parts==null)
				return false;
			if(this.parts.size()!=mData.parts.size())
				return false;
			IntIntMap partsR=mData.parts;
			if(!this.parts.isEmpty())
			{
				int partsKFreeValue=this.parts.getFreeValue();
				int[] partsKTable=this.parts.getTable();
				for(int partsKI=partsKTable.length-2;partsKI>=0;partsKI-=2)
				{
					if(partsKTable[partsKI]!=partsKFreeValue)
					{
						int partsK=partsKTable[partsKI];
						int partsV=partsKTable[partsKI+1];
						int partsU=partsR.get(partsK);
						if(partsV!=partsU)
							return false;
						
					}
				}
			}
		}
		else
		{
			if(this.parts!=null)
				return false;
		}
		
		return true;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "UnitAvatarData";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("modelID");
		writer.sb.append(':');
		writer.sb.append(this.modelID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("parts");
		writer.sb.append(':');
		writer.sb.append("Map<int,int>");
		if(this.parts!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.parts.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.parts.isEmpty())
			{
				int partsKFreeValue=this.parts.getFreeValue();
				int[] partsKTable=this.parts.getTable();
				for(int partsKI=partsKTable.length-2;partsKI>=0;partsKI-=2)
				{
					if(partsKTable[partsKI]!=partsKFreeValue)
					{
						int partsK=partsKTable[partsKI];
						int partsV=partsKTable[partsKI+1];
						writer.writeTabs();
						writer.sb.append(partsK);
						
						writer.sb.append(':');
						writer.sb.append(partsV);
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.parts=new IntIntMap();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.modelID=0;
		this.parts=null;
	}
	
}
