package com.home.commonClient.net.request.scene.unit;
import com.home.commonBase.data.scene.base.BulletData;
import com.home.commonClient.constlist.generate.GameRequestType;
import com.home.commonClient.net.request.scene.base.CUnitRRequest;
import com.home.commonClient.net.request.scene.base.SceneRRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 客户端主控单位添加子弹(generated by shine) */
public class CUnitAddBulletRequest extends CUnitRRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.CUnitAddBullet;
	
	/** 子弹数据 */
	public BulletData bullet;
	
	public CUnitAddBulletRequest()
	{
		_dataID=GameRequestType.CUnitAddBullet;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		BulletData bulletTemp=bullet;
		if(bulletTemp!=null)
		{
			this.bullet=(BulletData)bulletTemp.clone();
		}
		else
		{
			this.bullet=null;
			nullObjError("bullet");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CUnitAddBulletRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("bullet");
		writer.sb.append(':');
		if(this.bullet!=null)
		{
			this.bullet.writeDataString(writer);
		}
		else
		{
			writer.sb.append("BulletData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		if(this.bullet!=null)
		{
			stream.writeDataFullNotNull(this.bullet);
		}
		else
		{
			nullObjError("bullet");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.bullet!=null)
		{
			stream.writeDataSimpleNotNull(this.bullet);
		}
		else
		{
			nullObjError("bullet");
		}
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.bullet.release(pool);
		this.bullet=null;
	}
	
	/** 创建实例 */
	public static CUnitAddBulletRequest create(int instanceID,BulletData bullet)
	{
		CUnitAddBulletRequest re=(CUnitAddBulletRequest)BytesControl.createRequest(dataID);
		re.instanceID=instanceID;
		re.bullet=bullet;
		return re;
	}
	
}
