package com.home.commonCenter.net.serverRequest.game.func.rank;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.social.rank.RankData;
import com.home.commonCenter.net.serverRequest.game.base.CenterToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送增加排行榜数据消息(generated by shine) */
public class FuncAddRankToGameServerRequest extends CenterToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncAddRankToGame;
	
	/** 功能ID */
	public int funcID;
	
	/** 排行数据 */
	public RankData data;
	
	public FuncAddRankToGameServerRequest()
	{
		_dataID=ServerMessageType.FuncAddRankToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		RankData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(RankData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.funcID);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncAddRankToGameServerRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("funcID");
		writer.sb.append(':');
		writer.sb.append(this.funcID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RankData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.funcID=0;
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static FuncAddRankToGameServerRequest create(int funcID,RankData data)
	{
		FuncAddRankToGameServerRequest re=(FuncAddRankToGameServerRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.data=data;
		return re;
	}
	
}
