package com.home.commonBase.table.task;
import com.home.commonBase.table.result.ActivationCodeDBResult;
import com.home.commonBase.table.table.ActivationCodeTable;
import com.home.shine.table.BaseDBResult;
import com.home.shine.table.BaseTable;
import com.home.shine.table.task.BaseDBTask;

/** 激活码表(generated by shine) */
public class ActivationCodeDBTask extends BaseDBTask
{
	/** 码 */
	public String code="";
	
	/** id */
	public int id;
	
	/** 剩余可使用次数 */
	public int lastNum;
	
	/** 生成时间戳 */
	public long bornTime;
	
	/** 失效时间戳 */
	public long disableTime;
	
	@Override
	public BaseTable createTable()
	{
		return new ActivationCodeTable();
	}
	
	@Override
	public BaseDBResult createResult()
	{
		return new ActivationCodeDBResult();
	}
	
	@Override
	protected void toSetValues(boolean isInsert)
	{
		setString(code);
		setInt(id);
		setInt(lastNum);
		setLong(bornTime);
		setLong(disableTime);
	}
	
	@Override
	public Object getPrimaryKeyByIndex(int index)
	{
		switch(index)
		{
			case 0:
				return code;
		}
		return null;
	}
	
	@Override
	protected void toSetPrimaryKeyByIndex(int index)
	{
		switch(index)
		{
			case 0:
			{
				setString(code);
			}
				break;
		}
	}
	
}
