package com.home.commonBase.table.task;
import com.home.commonBase.table.result.PlayerNameDBResult;
import com.home.commonBase.table.table.PlayerNameTable;
import com.home.shine.table.BaseDBResult;
import com.home.shine.table.BaseTable;
import com.home.shine.table.task.BaseDBTask;

/** 中心服角色名字表(generated by shine) */
public class PlayerNameDBTask extends BaseDBTask
{
	/** 名字 */
	public String name="";
	
	/** 角色id */
	public long playerID;
	
	@Override
	public BaseTable createTable()
	{
		return new PlayerNameTable();
	}
	
	@Override
	public BaseDBResult createResult()
	{
		return new PlayerNameDBResult();
	}
	
	@Override
	protected void toSetValues(boolean isInsert)
	{
		setString(name);
		setLong(playerID);
	}
	
	@Override
	public Object getPrimaryKeyByIndex(int index)
	{
		switch(index)
		{
			case 0:
				return name;
		}
		return null;
	}
	
	@Override
	protected void toSetPrimaryKeyByIndex(int index)
	{
		switch(index)
		{
			case 0:
			{
				setString(name);
			}
				break;
		}
	}
	
}
