package com.home.commonClient.tool.generate;
import com.home.commonClient.constlist.generate.SceneBaseRequestType;
import com.home.commonClient.net.sceneBaseRequest.base.CRoleRRequest;
import com.home.commonClient.net.sceneBaseRequest.base.CUnitRRequest;
import com.home.commonClient.net.sceneBaseRequest.base.SceneRRequest;
import com.home.commonClient.net.sceneBaseRequest.scene.ClientSceneRadioRequest;
import com.home.commonClient.net.sceneBaseRequest.syncScene.CUnitPreBattleSureRequest;
import com.home.commonClient.net.sceneBaseRequest.syncScene.FrameSyncOneRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitAddBulletRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitAttackRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitBulletHitRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitChatRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitDriveRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitGetOffVehicleRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitGetOnVehicleRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitKillSelfRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitMoveDirRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitMovePosListRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitMovePosRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitOperateRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitPickUpItemBagAllRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitPickUpItemRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitRemoveBulletRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitSkillOverRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitSkillStepRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitSpecialMoveRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitStopMoveRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitSyncCommandRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitUseSkillExRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.CUnitUseSkillRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.building.CBuildingCancelLevelUpRequest;
import com.home.commonClient.net.sceneBaseRequest.unit.building.CBuildingLevelUpRequest;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class SceneBaseRequestMaker extends DataMaker
{
	public SceneBaseRequestMaker()
	{
		offSet=SceneBaseRequestType.off;
		list=new CreateDataFunc[SceneBaseRequestType.count-offSet];
		list[SceneBaseRequestType.CBuildingCancelLevelUp-offSet]=this::createCBuildingCancelLevelUpRequest;
		list[SceneBaseRequestType.CBuildingLevelUp-offSet]=this::createCBuildingLevelUpRequest;
		list[SceneBaseRequestType.CRoleR-offSet]=this::createCRoleRRequest;
		list[SceneBaseRequestType.CUnitAddBullet-offSet]=this::createCUnitAddBulletRequest;
		list[SceneBaseRequestType.CUnitAttack-offSet]=this::createCUnitAttackRequest;
		list[SceneBaseRequestType.CUnitBulletHit-offSet]=this::createCUnitBulletHitRequest;
		list[SceneBaseRequestType.CUnitChat-offSet]=this::createCUnitChatRequest;
		list[SceneBaseRequestType.CUnitDrive-offSet]=this::createCUnitDriveRequest;
		list[SceneBaseRequestType.CUnitGetOffVehicle-offSet]=this::createCUnitGetOffVehicleRequest;
		list[SceneBaseRequestType.CUnitGetOnVehicle-offSet]=this::createCUnitGetOnVehicleRequest;
		list[SceneBaseRequestType.CUnitKillSelf-offSet]=this::createCUnitKillSelfRequest;
		list[SceneBaseRequestType.CUnitMoveDir-offSet]=this::createCUnitMoveDirRequest;
		list[SceneBaseRequestType.CUnitMovePosList-offSet]=this::createCUnitMovePosListRequest;
		list[SceneBaseRequestType.CUnitMovePos-offSet]=this::createCUnitMovePosRequest;
		list[SceneBaseRequestType.CUnitOperate-offSet]=this::createCUnitOperateRequest;
		list[SceneBaseRequestType.CUnitPickUpItemBagAll-offSet]=this::createCUnitPickUpItemBagAllRequest;
		list[SceneBaseRequestType.CUnitPickUpItem-offSet]=this::createCUnitPickUpItemRequest;
		list[SceneBaseRequestType.CUnitPreBattleSure-offSet]=this::createCUnitPreBattleSureRequest;
		list[SceneBaseRequestType.CUnitR-offSet]=this::createCUnitRRequest;
		list[SceneBaseRequestType.CUnitRemoveBullet-offSet]=this::createCUnitRemoveBulletRequest;
		list[SceneBaseRequestType.CUnitSkillOver-offSet]=this::createCUnitSkillOverRequest;
		list[SceneBaseRequestType.CUnitSkillStep-offSet]=this::createCUnitSkillStepRequest;
		list[SceneBaseRequestType.CUnitSpecialMove-offSet]=this::createCUnitSpecialMoveRequest;
		list[SceneBaseRequestType.CUnitStopMove-offSet]=this::createCUnitStopMoveRequest;
		list[SceneBaseRequestType.CUnitSyncCommand-offSet]=this::createCUnitSyncCommandRequest;
		list[SceneBaseRequestType.CUnitUseSkillEx-offSet]=this::createCUnitUseSkillExRequest;
		list[SceneBaseRequestType.CUnitUseSkill-offSet]=this::createCUnitUseSkillRequest;
		list[SceneBaseRequestType.ClientSceneRadio-offSet]=this::createClientSceneRadioRequest;
		list[SceneBaseRequestType.FrameSyncOne-offSet]=this::createFrameSyncOneRequest;
		list[SceneBaseRequestType.SceneR-offSet]=this::createSceneRRequest;
	}
	
	private BaseData createCBuildingCancelLevelUpRequest()
	{
		return new CBuildingCancelLevelUpRequest();
	}
	
	private BaseData createCBuildingLevelUpRequest()
	{
		return new CBuildingLevelUpRequest();
	}
	
	private BaseData createCRoleRRequest()
	{
		return new CRoleRRequest();
	}
	
	private BaseData createCUnitAddBulletRequest()
	{
		return new CUnitAddBulletRequest();
	}
	
	private BaseData createCUnitAttackRequest()
	{
		return new CUnitAttackRequest();
	}
	
	private BaseData createCUnitBulletHitRequest()
	{
		return new CUnitBulletHitRequest();
	}
	
	private BaseData createCUnitChatRequest()
	{
		return new CUnitChatRequest();
	}
	
	private BaseData createCUnitDriveRequest()
	{
		return new CUnitDriveRequest();
	}
	
	private BaseData createCUnitGetOffVehicleRequest()
	{
		return new CUnitGetOffVehicleRequest();
	}
	
	private BaseData createCUnitGetOnVehicleRequest()
	{
		return new CUnitGetOnVehicleRequest();
	}
	
	private BaseData createCUnitKillSelfRequest()
	{
		return new CUnitKillSelfRequest();
	}
	
	private BaseData createCUnitMoveDirRequest()
	{
		return new CUnitMoveDirRequest();
	}
	
	private BaseData createCUnitMovePosListRequest()
	{
		return new CUnitMovePosListRequest();
	}
	
	private BaseData createCUnitMovePosRequest()
	{
		return new CUnitMovePosRequest();
	}
	
	private BaseData createCUnitOperateRequest()
	{
		return new CUnitOperateRequest();
	}
	
	private BaseData createCUnitPickUpItemBagAllRequest()
	{
		return new CUnitPickUpItemBagAllRequest();
	}
	
	private BaseData createCUnitPickUpItemRequest()
	{
		return new CUnitPickUpItemRequest();
	}
	
	private BaseData createCUnitPreBattleSureRequest()
	{
		return new CUnitPreBattleSureRequest();
	}
	
	private BaseData createCUnitRRequest()
	{
		return new CUnitRRequest();
	}
	
	private BaseData createCUnitRemoveBulletRequest()
	{
		return new CUnitRemoveBulletRequest();
	}
	
	private BaseData createCUnitSkillOverRequest()
	{
		return new CUnitSkillOverRequest();
	}
	
	private BaseData createCUnitSkillStepRequest()
	{
		return new CUnitSkillStepRequest();
	}
	
	private BaseData createCUnitSpecialMoveRequest()
	{
		return new CUnitSpecialMoveRequest();
	}
	
	private BaseData createCUnitStopMoveRequest()
	{
		return new CUnitStopMoveRequest();
	}
	
	private BaseData createCUnitSyncCommandRequest()
	{
		return new CUnitSyncCommandRequest();
	}
	
	private BaseData createCUnitUseSkillExRequest()
	{
		return new CUnitUseSkillExRequest();
	}
	
	private BaseData createCUnitUseSkillRequest()
	{
		return new CUnitUseSkillRequest();
	}
	
	private BaseData createClientSceneRadioRequest()
	{
		return new ClientSceneRadioRequest();
	}
	
	private BaseData createFrameSyncOneRequest()
	{
		return new FrameSyncOneRequest();
	}
	
	private BaseData createSceneRRequest()
	{
		return new SceneRRequest();
	}
	
}
