using ShineEngine;

/// <summary>
/// 攻击远近类型(generated by shine)
/// </summary>
public class AttackRangeType
{
	/// <summary>
	/// 无
	/// </summary>
	public const int None=0;
	
	/// <summary>
	/// 近战
	/// </summary>
	public const int Near=1;
	
	/// <summary>
	/// 远程
	/// </summary>
	public const int Far=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
