using ShineEngine;

/// <summary>
/// 聊天元素类型(generated by shine)
/// </summary>
public class ChatElementType
{
	/// <summary>
	/// 物品
	/// </summary>
	public const int Item=1;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=2;
	
}
