using ShineEngine;

/// <summary>
/// 客户端请求结果数据类型(generated by shine)
/// </summary>
public class ClientLoginHttpResultType
{
	/// <summary>
	/// 成功了
	/// </summary>
	public const int Success=0;
	
	/// <summary>
	/// 网络问题(网络不通)
	/// </summary>
	public const int NetworkBarrier=-1;
	
	/// <summary>
	/// 正在登录
	/// </summary>
	public const int IsLogining=1;
	
	/// <summary>
	/// 服务器没准备好
	/// </summary>
	public const int ServerNotReady=2;
	
	/// <summary>
	/// 平台校验失败
	/// </summary>
	public const int PlatformCheckFailed=3;
	
	/// <summary>
	/// 中心服阶段登陆失败
	/// </summary>
	public const int CenterLoginFaied=4;
	
	/// <summary>
	/// 代码版本校验失败
	/// </summary>
	public const int VersionCheckFailed=5;
	
	/// <summary>
	/// 超时
	/// </summary>
	public const int TimeOut=6;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=7;
	
}
