using ShineEngine;

/// <summary>
/// 货币表(generated by shine)
/// </summary>
public class CurrencyType
{
	/// <summary>
	/// 金币(游戏币1)
	/// </summary>
	public const int Coin=1;
	
	/// <summary>
	/// 元宝(人民币1)
	/// </summary>
	public const int Cash=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
