using ShineEngine;

/// <summary>
/// 属性公式类型(generated by shine)
/// </summary>
public class RewardLevelFormulaType
{
	/// <summary>
	/// 单值 value
	/// </summary>
	public const int Single=1;
	
	/// <summary>
	/// 标准线性公式 arg1:标准等级,arg2:线性成长参
	/// </summary>
	public const int Line=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
