using ShineEngine;

/// <summary>
/// 玩家群成员进出类型(generated by shine)
/// </summary>
public class RoleGroupMemberInOutType
{
	/// <summary>
	/// 创建群
	/// </summary>
	public const int Create=1;
	
	/// <summary>
	/// 邀请进群
	/// </summary>
	public const int Invite=2;
	
	/// <summary>
	/// 同意申请进趣
	/// </summary>
	public const int AgreeApply=3;
	
	/// <summary>
	/// 解散退出
	/// </summary>
	public const int Disband=4;
	
	/// <summary>
	/// 主动退出
	/// </summary>
	public const int Leave=5;
	
	/// <summary>
	/// 踢出
	/// </summary>
	public const int Kick=6;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=7;
	
}
