using ShineEngine;

/// <summary>
/// 场景元素类型(generated by shine)
/// </summary>
public class SceneElementType
{
	/// <summary>
	/// 怪物
	/// </summary>
	public const int Monster=2;
	
	/// <summary>
	/// NPC
	/// </summary>
	public const int Npc=3;
	
	/// <summary>
	/// 载具
	/// </summary>
	public const int Vehicle=6;
	
	/// <summary>
	/// 场景特效
	/// </summary>
	public const int SceneEffect=7;
	
	/// <summary>
	/// 操作体
	/// </summary>
	public const int Operation=8;
	
	/// <summary>
	/// 掉落物品
	/// </summary>
	public const int FieldItem=9;
	
	/// <summary>
	/// 建筑物
	/// </summary>
	public const int Building=10;
	
	/// <summary>
	/// 点
	/// </summary>
	public const int Point=11;
	
	/// <summary>
	/// 区域
	/// </summary>
	public const int Region=12;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=13;
	
}
