using ShineEngine;

/// <summary>
/// 性别类型(generated by shine)
/// </summary>
public class SexType
{
	/// <summary>
	/// 默认值
	/// </summary>
	public const int Default=0;
	
	/// <summary>
	/// 男
	/// </summary>
	public const int Boy=1;
	
	/// <summary>
	/// 女
	/// </summary>
	public const int Girl=2;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=3;
	
}
