using ShineEngine;

/// <summary>
/// 技能目标类型(generated by shine)
/// </summary>
public class SkillTargetType
{
	/// <summary>
	/// 无目标(立即释放)(无视距离限制)
	/// </summary>
	public const int None=0;
	
	/// <summary>
	/// 任意目标(单体)
	/// </summary>
	public const int Single=1;
	
	/// <summary>
	/// 地面坐标
	/// </summary>
	public const int Ground=2;
	
	/// <summary>
	/// 朝向
	/// </summary>
	public const int Direction=3;
	
	/// <summary>
	/// 攻击范围判定(矩形)(但是先要符合距离限制)
	/// </summary>
	public const int AttackScope=4;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=5;
	
}
