package com.home.commonClient.net.response.func.match;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.base.GameResponse;
import com.home.commonClient.net.response.func.base.FuncSResponse;
import com.home.shine.bytes.BytesReadStream;

/** 匹配结束(成功结束)(generated by shine) */
public class FuncMatchOverResponse extends FuncSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.FuncMatchOver;
	
	public FuncMatchOverResponse()
	{
		_dataID=GameResponseType.FuncMatchOver;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		me.scene.setMatchingFuncID(-1);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncMatchOverResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
}
