package com.home.commonGame.net.serverResponse.center.social;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.global.GameC;
import com.home.commonGame.net.serverResponse.center.base.CenterToGameServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** (generated by shine) */
public class SendGetRoleSocialDataToGameServerResponse extends CenterToGameServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.SendGetRoleSocialDataToGame;
	
	/** 来源角色ID */
	public long fromPlayerID;
	
	/** 目标玩家ID */
	public long targetPlayerID;
	
	/** 类型 */
	public int type;
	
	public SendGetRoleSocialDataToGameServerResponse()
	{
		_dataID=ServerMessageType.SendGetRoleSocialDataToGame;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendGetRoleSocialDataToGameServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.fromPlayerID=stream.readLong();
		
		this.targetPlayerID=stream.readLong();
		
		this.type=stream.readInt();
		
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		GameC.global.social.onGetAbsPlayerRoleSocialData(fromPlayerID,targetPlayerID,type);
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("fromPlayerID");
		writer.sb.append(':');
		writer.sb.append(this.fromPlayerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("targetPlayerID");
		writer.sb.append(':');
		writer.sb.append(this.targetPlayerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("type");
		writer.sb.append(':');
		writer.sb.append(this.type);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.fromPlayerID=0L;
		this.targetPlayerID=0L;
		this.type=0;
	}
	
}
