package com.home.commonClient.net.response.scene.unit;
import com.home.commonBase.data.scene.base.PosDirData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.response.scene.base.UnitSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 单位拉回消息(generated by shine) */
public class ReCUnitPullBackResponse extends UnitSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.ReCUnitPullBack;
	
	/** 位置 */
	public PosDirData posDir;
	
	public ReCUnitPullBackResponse()
	{
		_dataID=GameResponseType.ReCUnitPullBack;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		scene.getFightUnitAbs(instanceID).move.onServerPullBack(posDir);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ReCUnitPullBackResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.posDir=new PosDirData();
		this.posDir.readBytesFull(stream);
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.posDir=new PosDirData();
		this.posDir.readBytesSimple(stream);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("posDir");
		writer.sb.append(':');
		if(this.posDir!=null)
		{
			this.posDir.writeDataString(writer);
		}
		else
		{
			writer.sb.append("PosDirData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.posDir=null;
	}
	
}
