package com.home.commonClient.net.response.scene.unit;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.constlist.generate.MGameResponseType;
import com.home.commonClient.net.response.scene.unit.ReCUnitSkillFailedResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 回复技能失败消息(generated by shine) */
public class ReCUnitSkillFailedExResponse extends ReCUnitSkillFailedResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.ReCUnitSkillFailedEx;
	
	/** 当前的种子序号 */
	public int seedIndex;
	
	public ReCUnitSkillFailedExResponse()
	{
		_dataID=GameResponseType.ReCUnitSkillFailedEx;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		me.system.setSeedIndex(seedIndex);
		
		super.execute();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ReCUnitSkillFailedExResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.seedIndex=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.seedIndex=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("seedIndex");
		writer.sb.append(':');
		writer.sb.append(this.seedIndex);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.seedIndex=0;
	}
	
}
