package com.home.commonClient.net.response.scene.unit;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.constlist.generate.MGameResponseType;
import com.home.commonClient.net.response.scene.base.SceneSResponse;
import com.home.commonClient.net.response.scene.base.UnitSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 回复C单位技能失败(generated by shine) */
public class ReCUnitSkillFailedResponse extends UnitSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.ReCUnitSkillFailed;
	
	/** 技能ID */
	public int skillID;
	
	public ReCUnitSkillFailedResponse()
	{
		_dataID=GameResponseType.ReCUnitSkillFailed;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		scene.getFightUnitAbs(instanceID).fight.onServerSkillFailed(skillID);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ReCUnitSkillFailedResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.skillID=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.skillID=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("skillID");
		writer.sb.append(':');
		writer.sb.append(this.skillID);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.skillID=0;
	}
	
}
