package com.home.commonSceneBase.net.sceneBaseRequest.scene;
import com.home.commonSceneBase.constlist.generate.SceneBaseRequestType;
import com.home.commonSceneBase.net.sceneBaseRequest.base.SceneSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送场景广播消息(generated by shine) */
public class SceneRadioRequest extends SceneSRequest
{
	/** 数据类型ID */
	public static final int dataID=SceneBaseRequestType.SceneRadio;
	
	/** 数据 */
	public BaseData data;
	
	public SceneRadioRequest()
	{
		_dataID=SceneBaseRequestType.SceneRadio;
		setDontCopy();
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		BaseData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(BaseData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SceneRadioRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("BaseData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		if(this.data!=null)
		{
			stream.writeDataFullNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data=null;
	}
	
	/** 创建实例 */
	public static SceneRadioRequest create(BaseData data)
	{
		SceneRadioRequest re=(SceneRadioRequest)BytesControl.createRequest(dataID);
		re.data=data;
		return re;
	}
	
}
