package com.home.commonGame.net.serverRequest.game.func.auction;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.item.auction.AuctionItemData;
import com.home.commonGame.net.serverRequest.game.func.base.FuncToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送拍卖行出售物品到源服(generated by shine) */
public class FuncSendAuctionSellItemToSourceGameServerRequest extends FuncToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncSendAuctionSellItemToSourceGame;
	
	/** 出售物品 */
	public AuctionItemData data;
	
	public FuncSendAuctionSellItemToSourceGameServerRequest()
	{
		_dataID=ServerMessageType.FuncSendAuctionSellItemToSourceGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		AuctionItemData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(AuctionItemData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendAuctionSellItemToSourceGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("AuctionItemData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static FuncSendAuctionSellItemToSourceGameServerRequest create(int funcID,AuctionItemData data)
	{
		FuncSendAuctionSellItemToSourceGameServerRequest re=(FuncSendAuctionSellItemToSourceGameServerRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.data=data;
		return re;
	}
	
}
