package com.home.shine.net.response;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.constlist.generate.ShineResponseType;
import com.home.shine.net.base.ShineResponse;

/** 连接主动关闭(阻止重连)(generated by shine) */
public class SocketCloseResponse extends ShineResponse
{
	/** 数据类型ID */
	public static final int dataID=ShineResponseType.SocketClose;
	
	public SocketCloseResponse()
	{
		_dataID=ShineResponseType.SocketClose;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SocketCloseResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		//关闭重连，并等待连接关闭
		socket.setOpenReconnect(false);
	}
	
}
