package com.home.shine.net.response;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.constlist.generate.ShineResponseType;
import com.home.shine.ctrl.Ctrl;
import com.home.shine.net.base.ShineResponse;
import com.home.shine.net.socket.SendSocket;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 连接成功消息(generated by shine) */
public class SocketConnectSuccessResponse extends ShineResponse
{
	/** 数据类型ID */
	public static final int dataID=ShineResponseType.SocketConnectSuccess;
	
	/** 连接id */
	public int id;
	
	/** 重连令牌 */
	public int token;
	
	public SocketConnectSuccessResponse()
	{
		_dataID=ShineResponseType.SocketConnectSuccess;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SocketConnectSuccessResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.id=stream.readInt();
		
		this.token=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		this.token=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("id");
		writer.sb.append(':');
		writer.sb.append(this.id);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("token");
		writer.sb.append(':');
		writer.sb.append(this.token);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		SendSocket sendSocket=(SendSocket)socket;
		
		//有值
		if(sendSocket!=null)
		{
			sendSocket.setReceiveInfo(id,token);
		}
		else
		{
			Ctrl.errorLog("居然不是SendSocket");
		}
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.id=0;
		this.token=0;
	}
	
}
