package com.home.commonBase.data.social.roleGroup;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.social.roleGroup.RoleGroupSimpleData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 角色申请玩家群自身数据(generated by shine) */
public class PlayerApplyRoleGroupSelfData extends BaseData
{
	/** 简版数据 */
	public RoleGroupSimpleData data;
	
	/** 数据类型ID */
	public static final int dataID=BaseDataType.PlayerApplyRoleGroupSelf;
	
	/** 申请时间 */
	public long time;
	
	/** 失效时间 */
	public long disableTime;
	
	/** 结果 */
	public int result;
	
	public PlayerApplyRoleGroupSelfData()
	{
		_dataID=BaseDataType.PlayerApplyRoleGroupSelf;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "PlayerApplyRoleGroupSelfData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		BaseData dataT=stream.readDataFullNotNull();
		if(dataT!=null)
		{
			if(dataT instanceof RoleGroupSimpleData)
			{
				this.data=(RoleGroupSimpleData)dataT;
			}
			else
			{
				this.data=new RoleGroupSimpleData();
				if(!(dataT.getClass().isAssignableFrom(RoleGroupSimpleData.class)))
				{
					stream.throwTypeReadError(RoleGroupSimpleData.class,dataT.getClass());
				}
				this.data.shadowCopy(dataT);
			}
		}
		else
		{
			this.data=null;
		}
		
		this.time=stream.readLong();
		
		this.result=stream.readInt();
		
		this.disableTime=stream.readLong();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		if(this.data!=null)
		{
			stream.writeDataFullNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
		stream.writeLong(this.time);
		
		stream.writeInt(this.result);
		
		stream.writeLong(this.disableTime);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.data=(RoleGroupSimpleData)stream.readDataSimpleNotNull();
		
		this.time=stream.readLong();
		
		this.result=stream.readInt();
		
		this.disableTime=stream.readLong();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
		stream.writeLong(this.time);
		
		stream.writeInt(this.result);
		
		stream.writeLong(this.disableTime);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof PlayerApplyRoleGroupSelfData))
			return;
		
		PlayerApplyRoleGroupSelfData mData=(PlayerApplyRoleGroupSelfData)data;
		
		this.data=mData.data;
		this.time=mData.time;
		this.result=mData.result;
		this.disableTime=mData.disableTime;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof PlayerApplyRoleGroupSelfData))
			return;
		
		PlayerApplyRoleGroupSelfData mData=(PlayerApplyRoleGroupSelfData)data;
		
		if(mData.data!=null)
		{
			this.data=(RoleGroupSimpleData)mData.data.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
		this.time=mData.time;
		
		this.result=mData.result;
		
		this.disableTime=mData.disableTime;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		PlayerApplyRoleGroupSelfData mData=(PlayerApplyRoleGroupSelfData)data;
		if(mData.data!=null)
		{
			if(this.data==null)
				return false;
			if(!this.data.dataEquals(mData.data))
				return false;
		}
		else
		{
			if(this.data!=null)
				return false;
		}
		
		if(this.time!=mData.time)
			return false;
		
		if(this.result!=mData.result)
			return false;
		
		if(this.disableTime!=mData.disableTime)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RoleGroupSimpleData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("time");
		writer.sb.append(':');
		writer.sb.append(this.time);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("result");
		writer.sb.append(':');
		writer.sb.append(this.result);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("disableTime");
		writer.sb.append(':');
		writer.sb.append(this.disableTime);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.data=new RoleGroupSimpleData();
		this.data.initDefault();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.data=null;
		this.time=0L;
		this.result=0;
		this.disableTime=0L;
	}
	
}
