package com.home.commonBase.data.social.roleGroup;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.func.FuncToolData;
import com.home.commonBase.data.social.roleGroup.PlayerApplyRoleGroupData;
import com.home.commonBase.data.social.roleGroup.RoleGroupMemberData;
import com.home.commonBase.data.system.InfoLogData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.IntObjectMap;
import com.home.shine.support.collection.LongObjectMap;
import com.home.shine.support.collection.SQueue;
import com.home.shine.support.pool.DataPool;

/** 玩家群数据(单个群)(generated by shine) */
public class RoleGroupData extends BaseData
{
	/** 群id */
	public long groupID;
	
	/** 数据类型ID */
	public static final int dataID=BaseDataType.RoleGroup;
	
	/** 等级 */
	public int level;
	
	/** 公告 */
	public String notice="";
	
	/** 群名 */
	public String name="";
	
	/** 申请加入组 */
	public LongObjectMap<PlayerApplyRoleGroupData> applyDic;
	
	/** 申请时是否可直接入群(无需同意) */
	public boolean canApplyInAbs;
	
	/** 经验值 */
	public long exp;
	
	/** 日志信息队列 */
	public SQueue<InfoLogData> logQueue;
	
	/** 下一个0点时刻 */
	public long nextDailyTime;
	
	/** 插件数据组(key1:funcToolType,key2:funcID) */
	public IntObjectMap<IntObjectMap<FuncToolData>> funcTools;
	
	/** 成员组 */
	public LongObjectMap<RoleGroupMemberData> members;
	
	public RoleGroupData()
	{
		_dataID=BaseDataType.RoleGroup;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "RoleGroupData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.groupID=stream.readLong();
		
		this.level=stream.readInt();
		
		int membersLen=stream.readLen();
		if(this.members!=null)
		{
			this.members.clear();
			this.members.ensureCapacity(membersLen);
		}
		else
		{
			this.members=new LongObjectMap<RoleGroupMemberData>(RoleGroupMemberData[]::new,membersLen);
		}
		
		LongObjectMap<RoleGroupMemberData> membersT=this.members;
		for(int membersI=membersLen-1;membersI>=0;--membersI)
		{
			RoleGroupMemberData membersV;
			BaseData membersVT=stream.readDataFullNotNull();
			if(membersVT!=null)
			{
				if(membersVT instanceof RoleGroupMemberData)
				{
					membersV=(RoleGroupMemberData)membersVT;
				}
				else
				{
					membersV=new RoleGroupMemberData();
					if(!(membersVT.getClass().isAssignableFrom(RoleGroupMemberData.class)))
					{
						stream.throwTypeReadError(RoleGroupMemberData.class,membersVT.getClass());
					}
					membersV.shadowCopy(membersVT);
				}
			}
			else
			{
				membersV=null;
			}
			
			membersT.put(membersV.playerID,membersV);
		}
		
		this.name=stream.readUTF();
		
		this.notice=stream.readUTF();
		
		int applyDicLen=stream.readLen();
		if(this.applyDic!=null)
		{
			this.applyDic.clear();
			this.applyDic.ensureCapacity(applyDicLen);
		}
		else
		{
			this.applyDic=new LongObjectMap<PlayerApplyRoleGroupData>(PlayerApplyRoleGroupData[]::new,applyDicLen);
		}
		
		LongObjectMap<PlayerApplyRoleGroupData> applyDicT=this.applyDic;
		for(int applyDicI=applyDicLen-1;applyDicI>=0;--applyDicI)
		{
			long applyDicK;
			PlayerApplyRoleGroupData applyDicV;
			applyDicK=stream.readLong();
			
			BaseData applyDicVT=stream.readDataFullNotNull();
			if(applyDicVT!=null)
			{
				if(applyDicVT instanceof PlayerApplyRoleGroupData)
				{
					applyDicV=(PlayerApplyRoleGroupData)applyDicVT;
				}
				else
				{
					applyDicV=new PlayerApplyRoleGroupData();
					if(!(applyDicVT.getClass().isAssignableFrom(PlayerApplyRoleGroupData.class)))
					{
						stream.throwTypeReadError(PlayerApplyRoleGroupData.class,applyDicVT.getClass());
					}
					applyDicV.shadowCopy(applyDicVT);
				}
			}
			else
			{
				applyDicV=null;
			}
			
			applyDicT.put(applyDicK,applyDicV);
		}
		
		this.canApplyInAbs=stream.readBoolean();
		
		this.exp=stream.readLong();
		
		int logQueueLen=stream.readLen();
		if(this.logQueue!=null)
		{
			this.logQueue.clear();
			this.logQueue.ensureCapacity(logQueueLen);
		}
		else
		{
			this.logQueue=new SQueue<InfoLogData>(InfoLogData[]::new,logQueueLen);
		}
		
		SQueue<InfoLogData> logQueueT=this.logQueue;
		for(int logQueueI=logQueueLen-1;logQueueI>=0;--logQueueI)
		{
			InfoLogData logQueueV;
			BaseData logQueueVT=stream.readDataFullNotNull();
			if(logQueueVT!=null)
			{
				if(logQueueVT instanceof InfoLogData)
				{
					logQueueV=(InfoLogData)logQueueVT;
				}
				else
				{
					logQueueV=new InfoLogData();
					if(!(logQueueVT.getClass().isAssignableFrom(InfoLogData.class)))
					{
						stream.throwTypeReadError(InfoLogData.class,logQueueVT.getClass());
					}
					logQueueV.shadowCopy(logQueueVT);
				}
			}
			else
			{
				logQueueV=null;
			}
			
			logQueueT.offer(logQueueV);
		}
		
		this.nextDailyTime=stream.readLong();
		
		if(stream.readBoolean())
		{
			int funcToolsLen=stream.readLen();
			if(this.funcTools!=null)
			{
				this.funcTools.clear();
				this.funcTools.ensureCapacity(funcToolsLen);
			}
			else
			{
				this.funcTools=new IntObjectMap<IntObjectMap<FuncToolData>>(IntObjectMap[]::new,funcToolsLen);
			}
			
			IntObjectMap<IntObjectMap<FuncToolData>> funcToolsT=this.funcTools;
			for(int funcToolsI=funcToolsLen-1;funcToolsI>=0;--funcToolsI)
			{
				int funcToolsK;
				IntObjectMap<FuncToolData> funcToolsV;
				funcToolsK=stream.readInt();
				
				if(stream.readBoolean())
				{
					int funcToolsVLen=stream.readLen();
					funcToolsV=new IntObjectMap<FuncToolData>(FuncToolData[]::new,funcToolsVLen);
					IntObjectMap<FuncToolData> funcToolsVT=funcToolsV;
					for(int funcToolsVI=funcToolsVLen-1;funcToolsVI>=0;--funcToolsVI)
					{
						int funcToolsVK;
						FuncToolData funcToolsVV;
						funcToolsVK=stream.readInt();
						
						if(stream.readBoolean())
						{
							BaseData funcToolsVVT=stream.readDataFullNotNull();
							if(funcToolsVVT!=null)
							{
								if(funcToolsVVT instanceof FuncToolData)
								{
									funcToolsVV=(FuncToolData)funcToolsVVT;
								}
								else
								{
									funcToolsVV=new FuncToolData();
									if(!(funcToolsVVT.getClass().isAssignableFrom(FuncToolData.class)))
									{
										stream.throwTypeReadError(FuncToolData.class,funcToolsVVT.getClass());
									}
									funcToolsVV.shadowCopy(funcToolsVVT);
								}
							}
							else
							{
								funcToolsVV=null;
							}
						}
						else
						{
							funcToolsVV=null;
						}
						
						funcToolsVT.put(funcToolsVK,funcToolsVV);
					}
				}
				else
				{
					funcToolsV=null;
				}
				
				funcToolsT.put(funcToolsK,funcToolsV);
			}
		}
		else
		{
			this.funcTools=null;
		}
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeLong(this.groupID);
		
		stream.writeInt(this.level);
		
		if(this.members!=null)
		{
			stream.writeLen(this.members.size());
			if(!this.members.isEmpty())
			{
				Object[] membersVValues=this.members.getValues();
				for(int membersVI=membersVValues.length-1;membersVI>=0;--membersVI)
				{
					if(membersVValues[membersVI]!=null)
					{
						RoleGroupMemberData membersV=(RoleGroupMemberData)membersVValues[membersVI];
						if(membersV!=null)
						{
							stream.writeDataFullNotNull(membersV);
						}
						else
						{
							nullObjError("membersV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("members");
		}
		
		stream.writeUTF(this.name);
		
		stream.writeUTF(this.notice);
		
		if(this.applyDic!=null)
		{
			stream.writeLen(this.applyDic.size());
			if(!this.applyDic.isEmpty())
			{
				long applyDicKFreeValue=this.applyDic.getFreeValue();
				long[] applyDicKKeys=this.applyDic.getKeys();
				Object[] applyDicVValues=this.applyDic.getValues();
				for(int applyDicKI=applyDicKKeys.length-1;applyDicKI>=0;--applyDicKI)
				{
					long applyDicK=applyDicKKeys[applyDicKI];
					if(applyDicK!=applyDicKFreeValue)
					{
						PlayerApplyRoleGroupData applyDicV=(PlayerApplyRoleGroupData)applyDicVValues[applyDicKI];
						stream.writeLong(applyDicK);
						
						if(applyDicV!=null)
						{
							stream.writeDataFullNotNull(applyDicV);
						}
						else
						{
							nullObjError("applyDicV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("applyDic");
		}
		
		stream.writeBoolean(this.canApplyInAbs);
		
		stream.writeLong(this.exp);
		
		if(this.logQueue!=null)
		{
			stream.writeLen(this.logQueue.size());
			if(!this.logQueue.isEmpty())
			{
				Object[] logQueueVValues=this.logQueue.getValues();
				int logQueueVMark=this.logQueue.getMark();
				int logQueueVStart=this.logQueue.getStart();
				for(int logQueueVI=0,logQueueVLen=this.logQueue.length();logQueueVI<logQueueVLen;++logQueueVI)
				{
					InfoLogData logQueueV=(InfoLogData)logQueueVValues[(logQueueVI+logQueueVStart)&logQueueVMark];
					if(logQueueV!=null)
					{
						stream.writeDataFullNotNull(logQueueV);
					}
					else
					{
						nullObjError("logQueueV");
					}
					
				}
			}
		}
		else
		{
			nullObjError("logQueue");
		}
		
		stream.writeLong(this.nextDailyTime);
		
		if(this.funcTools!=null)
		{
			stream.writeBoolean(true);
			stream.writeLen(this.funcTools.size());
			if(!this.funcTools.isEmpty())
			{
				int funcToolsKFreeValue=this.funcTools.getFreeValue();
				int[] funcToolsKKeys=this.funcTools.getKeys();
				Object[] funcToolsVValues=this.funcTools.getValues();
				for(int funcToolsKI=funcToolsKKeys.length-1;funcToolsKI>=0;--funcToolsKI)
				{
					int funcToolsK=funcToolsKKeys[funcToolsKI];
					if(funcToolsK!=funcToolsKFreeValue)
					{
						IntObjectMap<FuncToolData> funcToolsV=(IntObjectMap<FuncToolData>)funcToolsVValues[funcToolsKI];
						stream.writeInt(funcToolsK);
						
						if(funcToolsV!=null)
						{
							stream.writeBoolean(true);
							stream.writeLen(funcToolsV.size());
							if(!funcToolsV.isEmpty())
							{
								int funcToolsVKFreeValue=funcToolsV.getFreeValue();
								int[] funcToolsVKKeys=funcToolsV.getKeys();
								Object[] funcToolsVVValues=funcToolsV.getValues();
								for(int funcToolsVKI=funcToolsVKKeys.length-1;funcToolsVKI>=0;--funcToolsVKI)
								{
									int funcToolsVK=funcToolsVKKeys[funcToolsVKI];
									if(funcToolsVK!=funcToolsVKFreeValue)
									{
										FuncToolData funcToolsVV=(FuncToolData)funcToolsVVValues[funcToolsVKI];
										stream.writeInt(funcToolsVK);
										
										if(funcToolsVV!=null)
										{
											stream.writeBoolean(true);
											stream.writeDataFullNotNull(funcToolsVV);
										}
										else
										{
											stream.writeBoolean(false);
										}
										
									}
								}
							}
						}
						else
						{
							stream.writeBoolean(false);
						}
						
					}
				}
			}
		}
		else
		{
			stream.writeBoolean(false);
		}
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.groupID=stream.readLong();
		
		this.level=stream.readInt();
		
		int membersLen=stream.readLen();
		if(this.members!=null)
		{
			this.members.clear();
			this.members.ensureCapacity(membersLen);
		}
		else
		{
			this.members=new LongObjectMap<RoleGroupMemberData>(RoleGroupMemberData[]::new,membersLen);
		}
		
		LongObjectMap<RoleGroupMemberData> membersT=this.members;
		for(int membersI=membersLen-1;membersI>=0;--membersI)
		{
			RoleGroupMemberData membersV;
			membersV=(RoleGroupMemberData)stream.readDataSimpleNotNull();
			
			membersT.put(membersV.playerID,membersV);
		}
		
		this.name=stream.readUTF();
		
		this.notice=stream.readUTF();
		
		int applyDicLen=stream.readLen();
		if(this.applyDic!=null)
		{
			this.applyDic.clear();
			this.applyDic.ensureCapacity(applyDicLen);
		}
		else
		{
			this.applyDic=new LongObjectMap<PlayerApplyRoleGroupData>(PlayerApplyRoleGroupData[]::new,applyDicLen);
		}
		
		LongObjectMap<PlayerApplyRoleGroupData> applyDicT=this.applyDic;
		for(int applyDicI=applyDicLen-1;applyDicI>=0;--applyDicI)
		{
			long applyDicK;
			PlayerApplyRoleGroupData applyDicV;
			applyDicK=stream.readLong();
			
			applyDicV=(PlayerApplyRoleGroupData)stream.readDataSimpleNotNull();
			
			applyDicT.put(applyDicK,applyDicV);
		}
		
		this.canApplyInAbs=stream.readBoolean();
		
		this.exp=stream.readLong();
		
		int logQueueLen=stream.readLen();
		if(this.logQueue!=null)
		{
			this.logQueue.clear();
			this.logQueue.ensureCapacity(logQueueLen);
		}
		else
		{
			this.logQueue=new SQueue<InfoLogData>(InfoLogData[]::new,logQueueLen);
		}
		
		SQueue<InfoLogData> logQueueT=this.logQueue;
		for(int logQueueI=logQueueLen-1;logQueueI>=0;--logQueueI)
		{
			InfoLogData logQueueV;
			logQueueV=(InfoLogData)stream.readDataSimpleNotNull();
			
			logQueueT.offer(logQueueV);
		}
		
		this.nextDailyTime=stream.readLong();
		
		if(stream.readBoolean())
		{
			int funcToolsLen=stream.readLen();
			if(this.funcTools!=null)
			{
				this.funcTools.clear();
				this.funcTools.ensureCapacity(funcToolsLen);
			}
			else
			{
				this.funcTools=new IntObjectMap<IntObjectMap<FuncToolData>>(IntObjectMap[]::new,funcToolsLen);
			}
			
			IntObjectMap<IntObjectMap<FuncToolData>> funcToolsT=this.funcTools;
			for(int funcToolsI=funcToolsLen-1;funcToolsI>=0;--funcToolsI)
			{
				int funcToolsK;
				IntObjectMap<FuncToolData> funcToolsV;
				funcToolsK=stream.readInt();
				
				if(stream.readBoolean())
				{
					int funcToolsVLen=stream.readLen();
					funcToolsV=new IntObjectMap<FuncToolData>(FuncToolData[]::new,funcToolsVLen);
					IntObjectMap<FuncToolData> funcToolsVT=funcToolsV;
					for(int funcToolsVI=funcToolsVLen-1;funcToolsVI>=0;--funcToolsVI)
					{
						int funcToolsVK;
						FuncToolData funcToolsVV;
						funcToolsVK=stream.readInt();
						
						if(stream.readBoolean())
						{
							funcToolsVV=(FuncToolData)stream.readDataSimpleNotNull();
						}
						else
						{
							funcToolsVV=null;
						}
						
						funcToolsVT.put(funcToolsVK,funcToolsVV);
					}
				}
				else
				{
					funcToolsV=null;
				}
				
				funcToolsT.put(funcToolsK,funcToolsV);
			}
		}
		else
		{
			this.funcTools=null;
		}
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeLong(this.groupID);
		
		stream.writeInt(this.level);
		
		if(this.members!=null)
		{
			stream.writeLen(this.members.size());
			if(!this.members.isEmpty())
			{
				Object[] membersVValues=this.members.getValues();
				for(int membersVI=membersVValues.length-1;membersVI>=0;--membersVI)
				{
					if(membersVValues[membersVI]!=null)
					{
						RoleGroupMemberData membersV=(RoleGroupMemberData)membersVValues[membersVI];
						if(membersV!=null)
						{
							stream.writeDataSimpleNotNull(membersV);
						}
						else
						{
							nullObjError("membersV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("members");
		}
		
		stream.writeUTF(this.name);
		
		stream.writeUTF(this.notice);
		
		if(this.applyDic!=null)
		{
			stream.writeLen(this.applyDic.size());
			if(!this.applyDic.isEmpty())
			{
				long applyDicKFreeValue=this.applyDic.getFreeValue();
				long[] applyDicKKeys=this.applyDic.getKeys();
				Object[] applyDicVValues=this.applyDic.getValues();
				for(int applyDicKI=applyDicKKeys.length-1;applyDicKI>=0;--applyDicKI)
				{
					long applyDicK=applyDicKKeys[applyDicKI];
					if(applyDicK!=applyDicKFreeValue)
					{
						PlayerApplyRoleGroupData applyDicV=(PlayerApplyRoleGroupData)applyDicVValues[applyDicKI];
						stream.writeLong(applyDicK);
						
						if(applyDicV!=null)
						{
							stream.writeDataSimpleNotNull(applyDicV);
						}
						else
						{
							nullObjError("applyDicV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("applyDic");
		}
		
		stream.writeBoolean(this.canApplyInAbs);
		
		stream.writeLong(this.exp);
		
		if(this.logQueue!=null)
		{
			stream.writeLen(this.logQueue.size());
			if(!this.logQueue.isEmpty())
			{
				Object[] logQueueVValues=this.logQueue.getValues();
				int logQueueVMark=this.logQueue.getMark();
				int logQueueVStart=this.logQueue.getStart();
				for(int logQueueVI=0,logQueueVLen=this.logQueue.length();logQueueVI<logQueueVLen;++logQueueVI)
				{
					InfoLogData logQueueV=(InfoLogData)logQueueVValues[(logQueueVI+logQueueVStart)&logQueueVMark];
					if(logQueueV!=null)
					{
						stream.writeDataSimpleNotNull(logQueueV);
					}
					else
					{
						nullObjError("logQueueV");
					}
					
				}
			}
		}
		else
		{
			nullObjError("logQueue");
		}
		
		stream.writeLong(this.nextDailyTime);
		
		if(this.funcTools!=null)
		{
			stream.writeBoolean(true);
			stream.writeLen(this.funcTools.size());
			if(!this.funcTools.isEmpty())
			{
				int funcToolsKFreeValue=this.funcTools.getFreeValue();
				int[] funcToolsKKeys=this.funcTools.getKeys();
				Object[] funcToolsVValues=this.funcTools.getValues();
				for(int funcToolsKI=funcToolsKKeys.length-1;funcToolsKI>=0;--funcToolsKI)
				{
					int funcToolsK=funcToolsKKeys[funcToolsKI];
					if(funcToolsK!=funcToolsKFreeValue)
					{
						IntObjectMap<FuncToolData> funcToolsV=(IntObjectMap<FuncToolData>)funcToolsVValues[funcToolsKI];
						stream.writeInt(funcToolsK);
						
						if(funcToolsV!=null)
						{
							stream.writeBoolean(true);
							stream.writeLen(funcToolsV.size());
							if(!funcToolsV.isEmpty())
							{
								int funcToolsVKFreeValue=funcToolsV.getFreeValue();
								int[] funcToolsVKKeys=funcToolsV.getKeys();
								Object[] funcToolsVVValues=funcToolsV.getValues();
								for(int funcToolsVKI=funcToolsVKKeys.length-1;funcToolsVKI>=0;--funcToolsVKI)
								{
									int funcToolsVK=funcToolsVKKeys[funcToolsVKI];
									if(funcToolsVK!=funcToolsVKFreeValue)
									{
										FuncToolData funcToolsVV=(FuncToolData)funcToolsVVValues[funcToolsVKI];
										stream.writeInt(funcToolsVK);
										
										if(funcToolsVV!=null)
										{
											stream.writeBoolean(true);
											stream.writeDataSimpleNotNull(funcToolsVV);
										}
										else
										{
											stream.writeBoolean(false);
										}
										
									}
								}
							}
						}
						else
						{
							stream.writeBoolean(false);
						}
						
					}
				}
			}
		}
		else
		{
			stream.writeBoolean(false);
		}
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof RoleGroupData))
			return;
		
		RoleGroupData mData=(RoleGroupData)data;
		
		this.groupID=mData.groupID;
		this.level=mData.level;
		this.members=mData.members;
		this.name=mData.name;
		this.notice=mData.notice;
		this.applyDic=mData.applyDic;
		this.canApplyInAbs=mData.canApplyInAbs;
		this.exp=mData.exp;
		this.logQueue=mData.logQueue;
		this.nextDailyTime=mData.nextDailyTime;
		this.funcTools=mData.funcTools;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof RoleGroupData))
			return;
		
		RoleGroupData mData=(RoleGroupData)data;
		
		this.groupID=mData.groupID;
		
		this.level=mData.level;
		
		if(mData.members!=null)
		{
			if(this.members!=null)
			{
				this.members.clear();
				this.members.ensureCapacity(mData.members.size());
			}
			else
			{
				this.members=new LongObjectMap<RoleGroupMemberData>(RoleGroupMemberData[]::new,mData.members.size());
			}
			
			LongObjectMap<RoleGroupMemberData> membersT=this.members;
			if(!mData.members.isEmpty())
			{
				Object[] membersVValues=mData.members.getValues();
				for(int membersVI=membersVValues.length-1;membersVI>=0;--membersVI)
				{
					if(membersVValues[membersVI]!=null)
					{
						RoleGroupMemberData membersV=(RoleGroupMemberData)membersVValues[membersVI];
						RoleGroupMemberData membersU;
						if(membersV!=null)
						{
							membersU=(RoleGroupMemberData)membersV.clone();
						}
						else
						{
							membersU=null;
							nullObjError("membersU");
						}
						
						membersT.put(membersU.playerID,membersU);
					}
				}
			}
		}
		else
		{
			this.members=null;
			nullObjError("members");
		}
		
		this.name=mData.name;
		
		this.notice=mData.notice;
		
		if(mData.applyDic!=null)
		{
			if(this.applyDic!=null)
			{
				this.applyDic.clear();
				this.applyDic.ensureCapacity(mData.applyDic.size());
			}
			else
			{
				this.applyDic=new LongObjectMap<PlayerApplyRoleGroupData>(PlayerApplyRoleGroupData[]::new,mData.applyDic.size());
			}
			
			LongObjectMap<PlayerApplyRoleGroupData> applyDicT=this.applyDic;
			if(!mData.applyDic.isEmpty())
			{
				long applyDicKFreeValue=mData.applyDic.getFreeValue();
				long[] applyDicKKeys=mData.applyDic.getKeys();
				Object[] applyDicVValues=mData.applyDic.getValues();
				for(int applyDicKI=applyDicKKeys.length-1;applyDicKI>=0;--applyDicKI)
				{
					long applyDicK=applyDicKKeys[applyDicKI];
					if(applyDicK!=applyDicKFreeValue)
					{
						PlayerApplyRoleGroupData applyDicV=(PlayerApplyRoleGroupData)applyDicVValues[applyDicKI];
						long applyDicW;
						PlayerApplyRoleGroupData applyDicU;
						applyDicW=applyDicK;
						
						if(applyDicV!=null)
						{
							applyDicU=(PlayerApplyRoleGroupData)applyDicV.clone();
						}
						else
						{
							applyDicU=null;
							nullObjError("applyDicU");
						}
						
						applyDicT.put(applyDicW,applyDicU);
					}
				}
			}
		}
		else
		{
			this.applyDic=null;
			nullObjError("applyDic");
		}
		
		this.canApplyInAbs=mData.canApplyInAbs;
		
		this.exp=mData.exp;
		
		if(mData.logQueue!=null)
		{
			if(this.logQueue!=null)
			{
				this.logQueue.clear();
				this.logQueue.ensureCapacity(mData.logQueue.size());
			}
			else
			{
				this.logQueue=new SQueue<InfoLogData>(InfoLogData[]::new,mData.logQueue.size());
			}
			
			SQueue<InfoLogData> logQueueT=this.logQueue;
			if(!mData.logQueue.isEmpty())
			{
				Object[] logQueueVValues=mData.logQueue.getValues();
				int logQueueVMark=mData.logQueue.getMark();
				int logQueueVStart=mData.logQueue.getStart();
				for(int logQueueVI=0,logQueueVLen=mData.logQueue.length();logQueueVI<logQueueVLen;++logQueueVI)
				{
					InfoLogData logQueueV=(InfoLogData)logQueueVValues[(logQueueVI+logQueueVStart)&logQueueVMark];
					InfoLogData logQueueU;
					if(logQueueV!=null)
					{
						logQueueU=(InfoLogData)logQueueV.clone();
					}
					else
					{
						logQueueU=null;
						nullObjError("logQueueU");
					}
					
					logQueueT.offer(logQueueU);
				}
			}
		}
		else
		{
			this.logQueue=null;
			nullObjError("logQueue");
		}
		
		this.nextDailyTime=mData.nextDailyTime;
		
		if(mData.funcTools!=null)
		{
			if(this.funcTools!=null)
			{
				this.funcTools.clear();
				this.funcTools.ensureCapacity(mData.funcTools.size());
			}
			else
			{
				this.funcTools=new IntObjectMap<IntObjectMap<FuncToolData>>(IntObjectMap[]::new,mData.funcTools.size());
			}
			
			IntObjectMap<IntObjectMap<FuncToolData>> funcToolsT=this.funcTools;
			if(!mData.funcTools.isEmpty())
			{
				int funcToolsKFreeValue=mData.funcTools.getFreeValue();
				int[] funcToolsKKeys=mData.funcTools.getKeys();
				Object[] funcToolsVValues=mData.funcTools.getValues();
				for(int funcToolsKI=funcToolsKKeys.length-1;funcToolsKI>=0;--funcToolsKI)
				{
					int funcToolsK=funcToolsKKeys[funcToolsKI];
					if(funcToolsK!=funcToolsKFreeValue)
					{
						IntObjectMap<FuncToolData> funcToolsV=(IntObjectMap<FuncToolData>)funcToolsVValues[funcToolsKI];
						int funcToolsW;
						IntObjectMap<FuncToolData> funcToolsU;
						funcToolsW=funcToolsK;
						
						if(funcToolsV!=null)
						{
							funcToolsU=new IntObjectMap<FuncToolData>(FuncToolData[]::new,funcToolsV.size());
							IntObjectMap<FuncToolData> funcToolsUT=funcToolsU;
							if(!funcToolsV.isEmpty())
							{
								int funcToolsUKFreeValue=funcToolsV.getFreeValue();
								int[] funcToolsUKKeys=funcToolsV.getKeys();
								Object[] funcToolsUVValues=funcToolsV.getValues();
								for(int funcToolsUKI=funcToolsUKKeys.length-1;funcToolsUKI>=0;--funcToolsUKI)
								{
									int funcToolsUK=funcToolsUKKeys[funcToolsUKI];
									if(funcToolsUK!=funcToolsUKFreeValue)
									{
										FuncToolData funcToolsUV=(FuncToolData)funcToolsUVValues[funcToolsUKI];
										int funcToolsUW;
										FuncToolData funcToolsUU;
										funcToolsUW=funcToolsUK;
										
										if(funcToolsUV!=null)
										{
											funcToolsUU=(FuncToolData)funcToolsUV.clone();
										}
										else
										{
											funcToolsUU=null;
										}
										
										funcToolsUT.put(funcToolsUW,funcToolsUU);
									}
								}
							}
						}
						else
						{
							funcToolsU=null;
						}
						
						funcToolsT.put(funcToolsW,funcToolsU);
					}
				}
			}
		}
		else
		{
			this.funcTools=null;
		}
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		RoleGroupData mData=(RoleGroupData)data;
		if(this.groupID!=mData.groupID)
			return false;
		
		if(this.level!=mData.level)
			return false;
		
		if(mData.members!=null)
		{
			if(this.members==null)
				return false;
			if(this.members.size()!=mData.members.size())
				return false;
			LongObjectMap<RoleGroupMemberData> membersR=mData.members;
			if(!this.members.isEmpty())
			{
				long membersKFreeValue=this.members.getFreeValue();
				long[] membersKKeys=this.members.getKeys();
				Object[] membersVValues=this.members.getValues();
				for(int membersKI=membersKKeys.length-1;membersKI>=0;--membersKI)
				{
					long membersK=membersKKeys[membersKI];
					if(membersK!=membersKFreeValue)
					{
						RoleGroupMemberData membersV=(RoleGroupMemberData)membersVValues[membersKI];
						RoleGroupMemberData membersU=membersR.get(membersK);
						if(membersU!=null)
						{
							if(membersV==null)
								return false;
							if(!membersV.dataEquals(membersU))
								return false;
						}
						else
						{
							if(membersV!=null)
								return false;
						}
						
					}
				}
			}
		}
		else
		{
			if(this.members!=null)
				return false;
		}
		
		if(!this.name.equals(mData.name))
			return false;
		
		if(!this.notice.equals(mData.notice))
			return false;
		
		if(mData.applyDic!=null)
		{
			if(this.applyDic==null)
				return false;
			if(this.applyDic.size()!=mData.applyDic.size())
				return false;
			LongObjectMap<PlayerApplyRoleGroupData> applyDicR=mData.applyDic;
			if(!this.applyDic.isEmpty())
			{
				long applyDicKFreeValue=this.applyDic.getFreeValue();
				long[] applyDicKKeys=this.applyDic.getKeys();
				Object[] applyDicVValues=this.applyDic.getValues();
				for(int applyDicKI=applyDicKKeys.length-1;applyDicKI>=0;--applyDicKI)
				{
					long applyDicK=applyDicKKeys[applyDicKI];
					if(applyDicK!=applyDicKFreeValue)
					{
						PlayerApplyRoleGroupData applyDicV=(PlayerApplyRoleGroupData)applyDicVValues[applyDicKI];
						PlayerApplyRoleGroupData applyDicU=applyDicR.get(applyDicK);
						if(applyDicU!=null)
						{
							if(applyDicV==null)
								return false;
							if(!applyDicV.dataEquals(applyDicU))
								return false;
						}
						else
						{
							if(applyDicV!=null)
								return false;
						}
						
					}
				}
			}
		}
		else
		{
			if(this.applyDic!=null)
				return false;
		}
		
		if(this.canApplyInAbs!=mData.canApplyInAbs)
			return false;
		
		if(this.exp!=mData.exp)
			return false;
		
		if(mData.logQueue!=null)
		{
			if(this.logQueue==null)
				return false;
			if(this.logQueue.size()!=mData.logQueue.size())
				return false;
			SQueue<InfoLogData> logQueueT=this.logQueue;
			SQueue<InfoLogData> logQueueR=mData.logQueue;
			int logQueueLen=logQueueT.size();
			for(int logQueueI=0;logQueueI<logQueueLen;++logQueueI)
			{
				InfoLogData logQueueU=logQueueT.get(logQueueI);
				InfoLogData logQueueV=logQueueR.get(logQueueI);
				if(logQueueV!=null)
				{
					if(logQueueU==null)
						return false;
					if(!logQueueU.dataEquals(logQueueV))
						return false;
				}
				else
				{
					if(logQueueU!=null)
						return false;
				}
				
			}
		}
		else
		{
			if(this.logQueue!=null)
				return false;
		}
		
		if(this.nextDailyTime!=mData.nextDailyTime)
			return false;
		
		if(mData.funcTools!=null)
		{
			if(this.funcTools==null)
				return false;
			if(this.funcTools.size()!=mData.funcTools.size())
				return false;
			IntObjectMap<IntObjectMap<FuncToolData>> funcToolsR=mData.funcTools;
			if(!this.funcTools.isEmpty())
			{
				int funcToolsKFreeValue=this.funcTools.getFreeValue();
				int[] funcToolsKKeys=this.funcTools.getKeys();
				Object[] funcToolsVValues=this.funcTools.getValues();
				for(int funcToolsKI=funcToolsKKeys.length-1;funcToolsKI>=0;--funcToolsKI)
				{
					int funcToolsK=funcToolsKKeys[funcToolsKI];
					if(funcToolsK!=funcToolsKFreeValue)
					{
						IntObjectMap<FuncToolData> funcToolsV=(IntObjectMap<FuncToolData>)funcToolsVValues[funcToolsKI];
						IntObjectMap<FuncToolData> funcToolsU=funcToolsR.get(funcToolsK);
						if(funcToolsU!=null)
						{
							if(funcToolsV==null)
								return false;
							if(funcToolsV.size()!=funcToolsU.size())
								return false;
							IntObjectMap<FuncToolData> funcToolsVR=funcToolsU;
							if(!funcToolsV.isEmpty())
							{
								int funcToolsVKFreeValue=funcToolsV.getFreeValue();
								int[] funcToolsVKKeys=funcToolsV.getKeys();
								Object[] funcToolsVVValues=funcToolsV.getValues();
								for(int funcToolsVKI=funcToolsVKKeys.length-1;funcToolsVKI>=0;--funcToolsVKI)
								{
									int funcToolsVK=funcToolsVKKeys[funcToolsVKI];
									if(funcToolsVK!=funcToolsVKFreeValue)
									{
										FuncToolData funcToolsVV=(FuncToolData)funcToolsVVValues[funcToolsVKI];
										FuncToolData funcToolsVU=funcToolsVR.get(funcToolsVK);
										if(funcToolsVU!=null)
										{
											if(funcToolsVV==null)
												return false;
											if(!funcToolsVV.dataEquals(funcToolsVU))
												return false;
										}
										else
										{
											if(funcToolsVV!=null)
												return false;
										}
										
									}
								}
							}
						}
						else
						{
							if(funcToolsV!=null)
								return false;
						}
						
					}
				}
			}
		}
		else
		{
			if(this.funcTools!=null)
				return false;
		}
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("groupID");
		writer.sb.append(':');
		writer.sb.append(this.groupID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("level");
		writer.sb.append(':');
		writer.sb.append(this.level);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("members");
		writer.sb.append(':');
		writer.sb.append("Map<long,RoleGroupMemberData>");
		if(this.members!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.members.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.members.isEmpty())
			{
				long membersKFreeValue=this.members.getFreeValue();
				long[] membersKKeys=this.members.getKeys();
				Object[] membersVValues=this.members.getValues();
				for(int membersKI=membersKKeys.length-1;membersKI>=0;--membersKI)
				{
					long membersK=membersKKeys[membersKI];
					if(membersK!=membersKFreeValue)
					{
						RoleGroupMemberData membersV=(RoleGroupMemberData)membersVValues[membersKI];
						writer.writeTabs();
						writer.sb.append(membersK);
						
						writer.sb.append(':');
						if(membersV!=null)
						{
							membersV.writeDataString(writer);
						}
						else
						{
							writer.sb.append("RoleGroupMemberData=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("name");
		writer.sb.append(':');
		writer.sb.append(this.name);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("notice");
		writer.sb.append(':');
		writer.sb.append(this.notice);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("applyDic");
		writer.sb.append(':');
		writer.sb.append("Map<long,PlayerApplyRoleGroupData>");
		if(this.applyDic!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.applyDic.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.applyDic.isEmpty())
			{
				long applyDicKFreeValue=this.applyDic.getFreeValue();
				long[] applyDicKKeys=this.applyDic.getKeys();
				Object[] applyDicVValues=this.applyDic.getValues();
				for(int applyDicKI=applyDicKKeys.length-1;applyDicKI>=0;--applyDicKI)
				{
					long applyDicK=applyDicKKeys[applyDicKI];
					if(applyDicK!=applyDicKFreeValue)
					{
						PlayerApplyRoleGroupData applyDicV=(PlayerApplyRoleGroupData)applyDicVValues[applyDicKI];
						writer.writeTabs();
						writer.sb.append(applyDicK);
						
						writer.sb.append(':');
						if(applyDicV!=null)
						{
							applyDicV.writeDataString(writer);
						}
						else
						{
							writer.sb.append("PlayerApplyRoleGroupData=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("canApplyInAbs");
		writer.sb.append(':');
		writer.sb.append(this.canApplyInAbs);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("exp");
		writer.sb.append(':');
		writer.sb.append(this.exp);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("logQueue");
		writer.sb.append(':');
		writer.sb.append("Queue<InfoLogData>");
		if(this.logQueue!=null)
		{
			SQueue<InfoLogData> logQueueT=this.logQueue;
			int logQueueLen=logQueueT.size();
			writer.sb.append('(');
			writer.sb.append(logQueueLen);
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			for(int logQueueI=0;logQueueI<logQueueLen;++logQueueI)
			{
				InfoLogData logQueueV=logQueueT.get(logQueueI);
				writer.writeTabs();
				writer.sb.append(logQueueI);
				writer.sb.append(':');
				if(logQueueV!=null)
				{
					logQueueV.writeDataString(writer);
				}
				else
				{
					writer.sb.append("InfoLogData=null");
				}
				
				writer.writeEnter();
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("nextDailyTime");
		writer.sb.append(':');
		writer.sb.append(this.nextDailyTime);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("funcTools");
		writer.sb.append(':');
		writer.sb.append("Map<int,IntObjectMap<FuncToolData>>");
		if(this.funcTools!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.funcTools.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.funcTools.isEmpty())
			{
				int funcToolsKFreeValue=this.funcTools.getFreeValue();
				int[] funcToolsKKeys=this.funcTools.getKeys();
				Object[] funcToolsVValues=this.funcTools.getValues();
				for(int funcToolsKI=funcToolsKKeys.length-1;funcToolsKI>=0;--funcToolsKI)
				{
					int funcToolsK=funcToolsKKeys[funcToolsKI];
					if(funcToolsK!=funcToolsKFreeValue)
					{
						IntObjectMap<FuncToolData> funcToolsV=(IntObjectMap<FuncToolData>)funcToolsVValues[funcToolsKI];
						writer.writeTabs();
						writer.sb.append(funcToolsK);
						
						writer.sb.append(':');
						writer.sb.append("Map<int,FuncToolData>");
						if(funcToolsV!=null)
						{
							writer.sb.append('(');
							writer.sb.append(funcToolsV.size());
							writer.sb.append(')');
							writer.writeEnter();
							writer.writeLeftBrace();
							if(!funcToolsV.isEmpty())
							{
								int funcToolsVKFreeValue=funcToolsV.getFreeValue();
								int[] funcToolsVKKeys=funcToolsV.getKeys();
								Object[] funcToolsVVValues=funcToolsV.getValues();
								for(int funcToolsVKI=funcToolsVKKeys.length-1;funcToolsVKI>=0;--funcToolsVKI)
								{
									int funcToolsVK=funcToolsVKKeys[funcToolsVKI];
									if(funcToolsVK!=funcToolsVKFreeValue)
									{
										FuncToolData funcToolsVV=(FuncToolData)funcToolsVVValues[funcToolsVKI];
										writer.writeTabs();
										writer.sb.append(funcToolsVK);
										
										writer.sb.append(':');
										if(funcToolsVV!=null)
										{
											funcToolsVV.writeDataString(writer);
										}
										else
										{
											writer.sb.append("FuncToolData=null");
										}
										
										writer.writeEnter();
									}
								}
							}
							writer.writeRightBrace();
						}
						else
						{
							writer.sb.append("=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.members=new LongObjectMap<RoleGroupMemberData>(RoleGroupMemberData[]::new);
		this.applyDic=new LongObjectMap<PlayerApplyRoleGroupData>(PlayerApplyRoleGroupData[]::new);
		this.logQueue=new SQueue<InfoLogData>(InfoLogData[]::new);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.groupID=0L;
		this.level=0;
		this.members=null;
		this.name="";
		this.notice="";
		this.applyDic=null;
		this.canApplyInAbs=false;
		this.exp=0L;
		this.logQueue=null;
		this.nextDailyTime=0L;
		this.funcTools=null;
	}
	
}
