package com.home.commonClient.net.request.func.roleGroup;
import com.home.commonClient.constlist.generate.GameRequestType;
import com.home.commonClient.net.base.GameRequest;
import com.home.commonClient.net.request.func.base.FuncPlayerRoleGroupRRequest;
import com.home.commonClient.net.request.func.base.FuncRRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 更改被邀请时是否可直接入群(generated by shine) */
public class FuncChangeRoleGroupCanInviteInAbsRequest extends FuncRRequest
{
	/** 被邀请时是否可直接入群(无需同意) */
	public boolean canInviteInAbs;
	
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncChangeRoleGroupCanInviteInAbs;
	
	public FuncChangeRoleGroupCanInviteInAbsRequest()
	{
		_dataID=GameRequestType.FuncChangeRoleGroupCanInviteInAbs;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncChangeRoleGroupCanInviteInAbsRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeBoolean(this.canInviteInAbs);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeBoolean(this.canInviteInAbs);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("canInviteInAbs");
		writer.sb.append(':');
		writer.sb.append(this.canInviteInAbs);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.canInviteInAbs=false;
	}
	
	/** 创建实例 */
	public static FuncChangeRoleGroupCanInviteInAbsRequest create(int funcID,boolean canInviteInAbs)
	{
		FuncChangeRoleGroupCanInviteInAbsRequest re=(FuncChangeRoleGroupCanInviteInAbsRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.canInviteInAbs=canInviteInAbs;
		return re;
	}
	
}
