package com.home.commonClient.net.request.func.roleGroup;
import com.home.commonClient.constlist.generate.GameRequestType;
import com.home.commonClient.net.request.func.base.FuncPlayerRoleGroupRRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** 主动离开玩家群(generated by shine) */
public class FuncLeaveRoleGroupRequest extends FuncPlayerRoleGroupRRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncLeaveRoleGroup;
	
	public FuncLeaveRoleGroupRequest()
	{
		_dataID=GameRequestType.FuncLeaveRoleGroup;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncLeaveRoleGroupRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 创建实例 */
	public static FuncLeaveRoleGroupRequest create(int funcID,long groupID)
	{
		FuncLeaveRoleGroupRequest re=(FuncLeaveRoleGroupRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.groupID=groupID;
		return re;
	}
	
}
