using ShineEngine;

/// <summary>
/// UI实例类型(generated by shine)
/// </summary>
public class CUIInstanceType
{
	/// <summary>
	/// 背包
	/// </summary>
	public const int Bag=1;
	
	/// <summary>
	/// 长度
	/// </summary>
	public static int size=0;
	
}
