package com.home.commonGame.net.response.system;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.net.base.GameResponse;
import com.home.commonGame.net.serverRequest.center.system.CenterTransGameToCenterServerRequest;
import com.home.commonGame.part.player.Player;
import com.home.commonGame.server.GameReceiveSocket;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.net.base.BaseResponse;
import com.home.shine.server.BaseServer;

/** 客户端到中心服转发到game消息(generated by shine) */
public class CenterTransClientToGameResponse extends GameResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.CenterTransClientToGame;
	
	public CenterTransClientToGameResponse()
	{
		_dataID=GameResponseType.CenterTransClientToGame;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
	@Override
	public BaseResponse readFromStream(BytesReadStream stream,BaseServer server)
	{
		Player player;
		
		//角色在线
		if((player=((GameReceiveSocket)socket).player)!=null)
		{
			CenterTransGameToCenterServerRequest request=CenterTransGameToCenterServerRequest.create();
			request.setData(player.role.playerID,stream.clone());
			request.send();
		}
		
		return null;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CenterTransClientToGameResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
}
