package com.home.commonGame.net.request.system;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送带参信息码消息(generated by shine) */
public class SendInfoCodeWithArgsRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.SendInfoCodeWithArgs;
	
	/** 码 */
	public int code;
	
	/** 参数组 */
	public String[] args;
	
	public SendInfoCodeWithArgsRequest()
	{
		_dataID=GameRequestType.SendInfoCodeWithArgs;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		String[] argsTemp=args;
		if(argsTemp!=null)
		{
			String[] argsR=argsTemp;
			int argsLen=argsR.length;
			this.args=new String[argsLen];
			BytesControl.arrayCopy(argsTemp,this.args,argsLen);
		}
		else
		{
			this.args=null;
			nullObjError("args");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendInfoCodeWithArgsRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("code");
		writer.sb.append(':');
		writer.sb.append(this.code);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("args");
		writer.sb.append(':');
		writer.sb.append("Array<String>");
		if(this.args!=null)
		{
			String[] argsT=this.args;
			int argsLen=argsT.length;
			writer.sb.append('(');
			writer.sb.append(argsLen);
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			for(int argsI=0;argsI<argsLen;++argsI)
			{
				String argsV=argsT[argsI];
				writer.writeTabs();
				writer.sb.append(argsI);
				writer.sb.append(':');
				writer.sb.append(argsV);
				
				writer.writeEnter();
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.code);
		
		if(this.args!=null)
		{
			String[] argsT=this.args;
			stream.writeLen(argsT.length);
			for(int argsVI=0,argsVLen=argsT.length;argsVI<argsVLen;++argsVI)
			{
				String argsV=argsT[argsVI];
				stream.writeUTF(argsV);
				
			}
		}
		else
		{
			nullObjError("args");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.code);
		
		if(this.args!=null)
		{
			String[] argsT=this.args;
			stream.writeLen(argsT.length);
			for(int argsVI=0,argsVLen=argsT.length;argsVI<argsVLen;++argsVI)
			{
				String argsV=argsT[argsVI];
				stream.writeUTF(argsV);
				
			}
		}
		else
		{
			nullObjError("args");
		}
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.code=0;
	}
	
	/** 创建实例 */
	public static SendInfoCodeWithArgsRequest create(int code,String[] args)
	{
		SendInfoCodeWithArgsRequest re=(SendInfoCodeWithArgsRequest)BytesControl.createRequest(dataID);
		re.code=code;
		re.args=args;
		return re;
	}
	
}
