package com.home.commonLogin.net.serverResponse.login.login;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.login.ClientLoginData;
import com.home.commonLogin.global.LoginC;
import com.home.commonLogin.net.serverResponse.login.base.LoginToLoginServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 客户端登陆转移消息(generated by shine) */
public class ClientLoginTransferServerResponse extends LoginToLoginServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.ClientLoginTransfer;
	
	/** http消息ID */
	public int httpID;
	
	/** ip地址 */
	public String ip="";
	
	/** 登录数据 */
	public ClientLoginData data;
	
	public ClientLoginTransferServerResponse()
	{
		_dataID=ServerMessageType.ClientLoginTransfer;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ClientLoginTransferServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.data=(ClientLoginData)stream.readDataSimpleNotNull();
		
		this.httpID=stream.readInt();
		
		this.ip=stream.readUTF();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("ClientLoginData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("httpID");
		writer.sb.append(':');
		writer.sb.append(this.httpID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("ip");
		writer.sb.append(':');
		writer.sb.append(this.ip);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		LoginC.main.doLoginNext(data,fromLoginID,httpID,ip);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data=null;
		this.httpID=0;
		this.ip="";
	}
	
}
