package com.home.commonCenter.net.serverRequest.game.system;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonCenter.net.serverRequest.game.base.CenterToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** 关闭game服消息(generated by shine) */
public class GameExitServerRequest extends CenterToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.GameExit;
	
	public GameExitServerRequest()
	{
		_dataID=ServerMessageType.GameExit;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GameExitServerRequest";
	}
	
	/** 创建实例 */
	public static GameExitServerRequest create()
	{
		GameExitServerRequest re=(GameExitServerRequest)BytesControl.createRequest(dataID);
		return re;
	}
	
}
