namespace Shine
{
	/** 帧同步起始消息(generated by shine) */
	export class FrameSyncStartResponse extends SceneSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.FrameSyncStart;
		
		/** 数据组 */
		public list:SList<FrameSyncData>;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.FrameSyncStart;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "FrameSyncStartResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			var listLen:number=stream.readLen();
			if(this.list!=null)
			{
				this.list.clear();
				this.list.ensureCapacity(listLen);
			}
			else
			{
				this.list=new SList<FrameSyncData>();
			}
			
			var listT:SList<FrameSyncData>=this.list;
			for(var listI:number=listLen-1;listI>=0;--listI)
			{
				var listV:FrameSyncData;
				listV=stream.readDataSimpleNotNull() as FrameSyncData;
				
				listT.add(listV);
			}
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
