namespace Shine
{
	/** 单位确认选择(generated by shine) */
	export class UnitPreBattleSureResponse extends SceneSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.UnitPreBattleSure;
		
		/** 单位实例ID */
		public instanceID:number;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.UnitPreBattleSure;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "UnitPreBattleSureResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.instanceID=stream.readInt();
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
