package com.home.commonLogin.net.serverResponse.game.system;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.system.UserWorkData;
import com.home.commonLogin.global.LoginC;
import com.home.commonLogin.net.serverResponse.game.base.GameToLoginServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送user事务到登陆服消息(generated by shine) */
public class SendUserWorkToLoginServerResponse extends GameToLoginServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.SendUserWorkToLogin;
	
	public UserWorkData data;
	
	public SendUserWorkToLoginServerResponse()
	{
		_dataID=ServerMessageType.SendUserWorkToLogin;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendUserWorkToLoginServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.data=(UserWorkData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("UserWorkData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		LoginC.main.onReceiveUserWork(data);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data=null;
	}
	
}
