namespace Shine
{
	/** 创建队伍参数(generated by shine) */
	export class CreateTeamData extends CreateRoleGroupData
	{
		/** 数据类型ID */
		public static dataID:number=BaseDataType.CreateTeam;
		
		constructor()
		{
			super();
			this._dataID=BaseDataType.CreateTeam;
		}
		
	}
}
