package com.home.commonClient.net.response.scene.scene;
import com.home.commonBase.data.scene.scene.FieldItemBagBindData;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.base.GameResponse;
import com.home.commonClient.net.response.scene.base.SceneSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 添加掉落物品包绑定消息(generated by shine) */
public class AddFieldItemBagBindResponse extends SceneSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.AddFieldItemBagBind;
	
	/** 掉落物品包绑定消息 */
	public FieldItemBagBindData data;
	
	public AddFieldItemBagBindResponse()
	{
		_dataID=GameResponseType.AddFieldItemBagBind;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "AddFieldItemBagBindResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		BaseData dataT=stream.readDataFullNotNull();
		if(dataT!=null)
		{
			if(dataT instanceof FieldItemBagBindData)
			{
				this.data=(FieldItemBagBindData)dataT;
			}
			else
			{
				this.data=new FieldItemBagBindData();
				if(!(dataT.getClass().isAssignableFrom(FieldItemBagBindData.class)))
				{
					stream.throwTypeReadError(FieldItemBagBindData.class,dataT.getClass());
				}
				this.data.shadowCopy(dataT);
			}
		}
		else
		{
			this.data=null;
		}
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.data=(FieldItemBagBindData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("FieldItemBagBindData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data=null;
	}
	
}
