package com.home.commonClient.net.response.scene.scene;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.response.scene.base.SceneSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 移除单位协议(generated by shine) */
public class RemoveUnitResponse extends SceneSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.RemoveUnit;
	
	/** 实例ID */
	public int instanceID;
	
	public RemoveUnitResponse()
	{
		_dataID=GameResponseType.RemoveUnit;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "RemoveUnitResponse";
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		scene.removeUnit(instanceID);
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.instanceID=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.instanceID=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("instanceID");
		writer.sb.append(':');
		writer.sb.append(this.instanceID);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.instanceID=0;
	}
	
}
