namespace Shine
{
	/** 单位添加组CD百分比(generated by shine) */
	export class UnitAddGroupTimeMaxPercentResponse extends UnitSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.UnitAddGroupTimeMaxPercent;
		
		/** 组ID */
		public groupID:number;
		
		/** 值 */
		public value:number;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.UnitAddGroupTimeMaxPercent;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "UnitAddGroupTimeMaxPercentResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.groupID=stream.readInt();
			
			this.value=stream.readInt();
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
