namespace Shine
{
	/** 单位移除组CD(generated by shine) */
	export class UnitRemoveGroupCDResponse extends UnitSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.UnitRemoveGroupCD;
		
		/** 组ID */
		public groupID:number;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.UnitRemoveGroupCD;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "UnitRemoveGroupCDResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.groupID=stream.readInt();
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
