namespace Shine
{
	/** 单位移动位置(generated by shine) */
	export class UnitMovePosResponse extends UnitSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.UnitMovePos;
		
		/** 移动类型 */
		public type:number;
		
		/** 目标位置 */
		public targetPos:PosData;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.UnitMovePos;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "UnitMovePosResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.type=stream.readInt();
			
			this.targetPos=new PosData();
			this.targetPos.readBytesSimple(stream);
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
