namespace Shine
{
	/** 单位特殊移动消息(generated by shine) */
	export class UnitSpecialMoveResponse extends UnitSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.UnitSpecialMove;
		
		/** 特殊移动ID */
		public id:number;
		
		/** 当前位置 */
		public posDir:PosDirData;
		
		/** 基元移动点位置 */
		public baseMovePos:PosData;
		
		/** 特殊移动剩余时间 */
		public specialMoveLastTime:number;
		
		/** 参数组 */
		public args:number[];
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.UnitSpecialMove;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "UnitSpecialMoveResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.id=stream.readInt();
			
			this.posDir=new PosDirData();
			this.posDir.readBytesSimple(stream);
			
			if(stream.readBoolean())
			{
				var argsLen:number=stream.readLen();
				this.args=new Array<number>(argsLen);
				var argsT:number[]=this.args;
				for(var argsI:number=0;argsI<argsLen;++argsI)
				{
					var argsV:number;
					argsV=stream.readInt();
					
					argsT[argsI]=argsV;
				}
			}
			else
			{
				this.args=null;
			}
			
			this.specialMoveLastTime=stream.readInt();
			
			if(stream.readBoolean())
			{
				this.baseMovePos=new PosData();
				this.baseMovePos.readBytesSimple(stream);
			}
			else
			{
				this.baseMovePos=null;
			}
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
