package com.home.commonBase.data.scene.scene;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.item.ItemData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.SList;
import com.home.shine.support.pool.DataPool;

/** 掉落物品包绑定数据(generated by shine) */
public class FieldItemBagBindData extends BaseData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.FieldItemBagBind;
	
	/** 归属单位实例id */
	public int instanceID;
	
	/** 物品组 */
	public SList<ItemData> items;
	
	/** 移除时间 */
	public long removeTime;
	
	public FieldItemBagBindData()
	{
		_dataID=BaseDataType.FieldItemBagBind;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FieldItemBagBindData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.instanceID=stream.readInt();
		
		int itemsLen=stream.readLen();
		if(this.items!=null)
		{
			this.items.clear();
			this.items.ensureCapacity(itemsLen);
		}
		else
		{
			this.items=new SList<ItemData>(ItemData[]::new,itemsLen);
		}
		
		SList<ItemData> itemsT=this.items;
		for(int itemsI=itemsLen-1;itemsI>=0;--itemsI)
		{
			ItemData itemsV;
			BaseData itemsVT=stream.readDataFullNotNull();
			if(itemsVT!=null)
			{
				if(itemsVT instanceof ItemData)
				{
					itemsV=(ItemData)itemsVT;
				}
				else
				{
					itemsV=new ItemData();
					if(!(itemsVT.getClass().isAssignableFrom(ItemData.class)))
					{
						stream.throwTypeReadError(ItemData.class,itemsVT.getClass());
					}
					itemsV.shadowCopy(itemsVT);
				}
			}
			else
			{
				itemsV=null;
			}
			
			itemsT.add(itemsV);
		}
		
		this.removeTime=stream.readLong();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeInt(this.instanceID);
		
		if(this.items!=null)
		{
			stream.writeLen(this.items.size());
			if(!this.items.isEmpty())
			{
				Object[] itemsVValues=this.items.getValues();
				for(int itemsVI=0,itemsVLen=this.items.length();itemsVI<itemsVLen;++itemsVI)
				{
					ItemData itemsV=(ItemData)itemsVValues[itemsVI];
					if(itemsV!=null)
					{
						stream.writeDataFullNotNull(itemsV);
					}
					else
					{
						nullObjError("itemsV");
					}
					
				}
			}
		}
		else
		{
			nullObjError("items");
		}
		
		stream.writeLong(this.removeTime);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.instanceID=stream.readInt();
		
		int itemsLen=stream.readLen();
		if(this.items!=null)
		{
			this.items.clear();
			this.items.ensureCapacity(itemsLen);
		}
		else
		{
			this.items=new SList<ItemData>(ItemData[]::new,itemsLen);
		}
		
		SList<ItemData> itemsT=this.items;
		for(int itemsI=itemsLen-1;itemsI>=0;--itemsI)
		{
			ItemData itemsV;
			itemsV=(ItemData)stream.readDataSimpleNotNull();
			
			itemsT.add(itemsV);
		}
		
		this.removeTime=stream.readLong();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeInt(this.instanceID);
		
		if(this.items!=null)
		{
			stream.writeLen(this.items.size());
			if(!this.items.isEmpty())
			{
				Object[] itemsVValues=this.items.getValues();
				for(int itemsVI=0,itemsVLen=this.items.length();itemsVI<itemsVLen;++itemsVI)
				{
					ItemData itemsV=(ItemData)itemsVValues[itemsVI];
					if(itemsV!=null)
					{
						stream.writeDataSimpleNotNull(itemsV);
					}
					else
					{
						nullObjError("itemsV");
					}
					
				}
			}
		}
		else
		{
			nullObjError("items");
		}
		
		stream.writeLong(this.removeTime);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof FieldItemBagBindData))
			return;
		
		FieldItemBagBindData mData=(FieldItemBagBindData)data;
		
		this.instanceID=mData.instanceID;
		this.items=mData.items;
		this.removeTime=mData.removeTime;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof FieldItemBagBindData))
			return;
		
		FieldItemBagBindData mData=(FieldItemBagBindData)data;
		
		this.instanceID=mData.instanceID;
		
		if(mData.items!=null)
		{
			if(this.items!=null)
			{
				this.items.clear();
				this.items.ensureCapacity(mData.items.size());
			}
			else
			{
				this.items=new SList<ItemData>(ItemData[]::new,mData.items.size());
			}
			
			SList<ItemData> itemsT=this.items;
			if(!mData.items.isEmpty())
			{
				Object[] itemsVValues=mData.items.getValues();
				for(int itemsVI=0,itemsVLen=mData.items.length();itemsVI<itemsVLen;++itemsVI)
				{
					ItemData itemsV=(ItemData)itemsVValues[itemsVI];
					ItemData itemsU;
					if(itemsV!=null)
					{
						itemsU=(ItemData)itemsV.clone();
					}
					else
					{
						itemsU=null;
						nullObjError("itemsU");
					}
					
					itemsT.add(itemsU);
				}
			}
		}
		else
		{
			this.items=null;
			nullObjError("items");
		}
		
		this.removeTime=mData.removeTime;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		FieldItemBagBindData mData=(FieldItemBagBindData)data;
		if(this.instanceID!=mData.instanceID)
			return false;
		
		if(mData.items!=null)
		{
			if(this.items==null)
				return false;
			if(this.items.size()!=mData.items.size())
				return false;
			SList<ItemData> itemsT=this.items;
			SList<ItemData> itemsR=mData.items;
			int itemsLen=itemsT.size();
			for(int itemsI=0;itemsI<itemsLen;++itemsI)
			{
				ItemData itemsU=itemsT.get(itemsI);
				ItemData itemsV=itemsR.get(itemsI);
				if(itemsV!=null)
				{
					if(itemsU==null)
						return false;
					if(!itemsU.dataEquals(itemsV))
						return false;
				}
				else
				{
					if(itemsU!=null)
						return false;
				}
				
			}
		}
		else
		{
			if(this.items!=null)
				return false;
		}
		
		if(this.removeTime!=mData.removeTime)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("instanceID");
		writer.sb.append(':');
		writer.sb.append(this.instanceID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("items");
		writer.sb.append(':');
		writer.sb.append("List<ItemData>");
		if(this.items!=null)
		{
			SList<ItemData> itemsT=this.items;
			int itemsLen=itemsT.size();
			writer.sb.append('(');
			writer.sb.append(itemsLen);
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			for(int itemsI=0;itemsI<itemsLen;++itemsI)
			{
				ItemData itemsV=itemsT.get(itemsI);
				writer.writeTabs();
				writer.sb.append(itemsI);
				writer.sb.append(':');
				if(itemsV!=null)
				{
					itemsV.writeDataString(writer);
				}
				else
				{
					writer.sb.append("ItemData=null");
				}
				
				writer.writeEnter();
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("removeTime");
		writer.sb.append(':');
		writer.sb.append(this.removeTime);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.items=new SList<ItemData>(ItemData[]::new);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.instanceID=0;
		this.items=null;
		this.removeTime=0L;
	}
	
}
