package com.home.commonBase.data.scene.scene;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.scene.scene.SceneLocationData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 场景进入参数数据(generated by shine) */
public class SceneEnterArgData extends BaseData
{
	/** 是否使用当前缓存位置数据 */
	public boolean useCache;
	
	/** 进入点位置 */
	public int posID=-1;
	
	/** 场景位置数据 */
	public SceneLocationData location;
	
	/** 数据类型ID */
	public static final int dataID=BaseDataType.SceneEnterArg;
	
	public SceneEnterArgData()
	{
		_dataID=BaseDataType.SceneEnterArg;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SceneEnterArgData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		BaseData locationT=stream.readDataFullNotNull();
		if(locationT!=null)
		{
			if(locationT instanceof SceneLocationData)
			{
				this.location=(SceneLocationData)locationT;
			}
			else
			{
				this.location=new SceneLocationData();
				if(!(locationT.getClass().isAssignableFrom(SceneLocationData.class)))
				{
					stream.throwTypeReadError(SceneLocationData.class,locationT.getClass());
				}
				this.location.shadowCopy(locationT);
			}
		}
		else
		{
			this.location=null;
		}
		
		this.posID=stream.readInt();
		
		this.useCache=stream.readBoolean();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		if(this.location!=null)
		{
			stream.writeDataFullNotNull(this.location);
		}
		else
		{
			nullObjError("location");
		}
		
		stream.writeInt(this.posID);
		
		stream.writeBoolean(this.useCache);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.location=(SceneLocationData)stream.readDataSimpleNotNull();
		
		this.posID=stream.readInt();
		
		this.useCache=stream.readBoolean();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		if(this.location!=null)
		{
			stream.writeDataSimpleNotNull(this.location);
		}
		else
		{
			nullObjError("location");
		}
		
		stream.writeInt(this.posID);
		
		stream.writeBoolean(this.useCache);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof SceneEnterArgData))
			return;
		
		SceneEnterArgData mData=(SceneEnterArgData)data;
		
		this.location=mData.location;
		this.posID=mData.posID;
		this.useCache=mData.useCache;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof SceneEnterArgData))
			return;
		
		SceneEnterArgData mData=(SceneEnterArgData)data;
		
		if(mData.location!=null)
		{
			this.location=(SceneLocationData)mData.location.clone();
		}
		else
		{
			this.location=null;
			nullObjError("location");
		}
		
		this.posID=mData.posID;
		
		this.useCache=mData.useCache;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		SceneEnterArgData mData=(SceneEnterArgData)data;
		if(mData.location!=null)
		{
			if(this.location==null)
				return false;
			if(!this.location.dataEquals(mData.location))
				return false;
		}
		else
		{
			if(this.location!=null)
				return false;
		}
		
		if(this.posID!=mData.posID)
			return false;
		
		if(this.useCache!=mData.useCache)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("location");
		writer.sb.append(':');
		if(this.location!=null)
		{
			this.location.writeDataString(writer);
		}
		else
		{
			writer.sb.append("SceneLocationData=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("posID");
		writer.sb.append(':');
		writer.sb.append(this.posID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("useCache");
		writer.sb.append(':');
		writer.sb.append(this.useCache);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.location=new SceneLocationData();
		this.location.initDefault();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.location=null;
		this.posID=0;
		this.useCache=false;
	}
	
}
