using ShineEngine;

/// <summary>
/// 建筑建造成功(generated by shine)
/// </summary>
public class BuildingBuildCompleteResponse:UnitSResponse
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=SceneBaseResponseType.BuildingBuildComplete;
	
	public BuildingBuildCompleteResponse()
	{
		_dataID=SceneBaseResponseType.BuildingBuildComplete;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "BuildingBuildCompleteResponse";
	}
	
	/// <summary>
	/// 读取字节流(完整版)
	/// </summary>
	protected override void toReadBytesFull(BytesReadStream stream)
	{
		base.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/// <summary>
	/// 执行
	/// </summary>
	protected override void execute()
	{
		
	}
	
}
