namespace Shine
{
	/** 客户端请求结果数据类型(generated by shine) */
	export class ClientLoginHttpResultType
	{
		/** 成功了 */
		public static Success:number=0;
		
		/** 网络问题(网络不通) */
		public static NetworkBarrier:number=-1;
		
		/** 正在登录 */
		public static IsLogining:number=1;
		
		/** 服务器没准备好 */
		public static ServerNotReady:number=2;
		
		/** 平台校验失败 */
		public static PlatformCheckFailed:number=3;
		
		/** 中心服阶段登陆失败 */
		public static CenterLoginFaied:number=4;
		
		/** 代码版本校验失败 */
		public static VersionCheckFailed:number=5;
		
		/** 超时 */
		public static TimeOut:number=6;
		
		/** 长度 */
		public static size:number=7;
		
	}
}
