namespace Shine
{
	/** 战斗判定阶段(generated by shine) */
	export class FightMomentType
	{
		/** 击杀后(目标死亡但存在) */
		public static AfterKill:number=1;
		
		/** 被击杀前 */
		public static BeforeBeKill:number=2;
		
		/** 长度 */
		public static size:number=3;
		
	}
}
