namespace Shine
{
	/** 跳转UI类型(generated by shine) */
	export class JumpUIType
	{
		/** 功能 */
		public static Function:number=1;
		
		/** 活动 */
		public static Activity:number=2;
		
		/** 长度 */
		public static size:number=3;
		
	}
}
