namespace Shine
{
	/** 任务提交类型(generated by shine) */
	export class QuestCommitType
	{
		/** 不可主动提交 */
		public static Passive:number=0;
		
		/** 找npc提交 */
		public static ByNPC:number=1;
		
		/** 自动提交(客户端)(如包满会暂停流程) */
		public static Auto:number=2;
		
		/** 自动提交(服务器)(包满邮件) */
		public static ServerAuto:number=3;
		
		/** 客户端提交 */
		public static Client:number=4;
		
		/** 长度 */
		public static size:number=5;
		
	}
}
