namespace Shine
{
	/** 属性公式类型(generated by shine) */
	export class RewardLevelFormulaType
	{
		/** 单值 value */
		public static Single:number=1;
		
		/** 标准线性公式 arg1:标准等级,arg2:线性成长参 */
		public static Line:number=2;
		
		/** 长度 */
		public static size:number=3;
		
	}
}
