namespace Shine
{
	/** 角色行为类型(generated by shine) */
	export class RoleActionType
	{
		/** 主角添加固定属性 arg1:属性类型,arg2:属性值(当前属性) */
		public static HeroAddAttribute:number=1;
		
		/** 主角添加变量属性 arg1:属性类型,arg2:变量ID(当前属性) */
		public static HeroAddAttributeVar:number=2;
		
		/** 主角添加buff arg1:buffID arg2:buff等级 */
		public static HeroAddBuff:number=3;
		
		/** 添加货币 arg1:货币类型 arg2:数目 */
		public static AddCurrency:number=4;
		
		/** 添加奖励 arg1:奖励id */
		public static AddReward:number=5;
		
		/** 移除道具 arg1:道具id  arg2:道具数量 */
		public static RemoveItem:number=6;
		
		/** 长度 */
		public static size:number=7;
		
	}
}
