namespace Shine
{
	/** 技能指令输入类型(generated by shine) */
	export class SkillCommandInputType
	{
		/** 按下攻击键 */
		public static PressAttack:number=1;
		
		/** 按下技能1键 */
		public static PressSkill1:number=2;
		
		/** 按下技能2键 */
		public static PressSkill2:number=3;
		
		/** 长度 */
		public static size:number=4;
		
	}
}
