namespace Shine
{
	/** 单位模型位置类型(generated by shine) */
	export class UnitModelSlotType
	{
		/** 脚 */
		public static Root:number=1;
		
		/** 头 */
		public static Head:number=2;
		
		/** 长度 */
		public static size:number=3;
		
	}
}
