namespace Shine
{
	/** 动作地面状态类型(generated by shine) */
	export class UnitActGroundStateType
	{
		/** 地面 */
		public static Ground:number=1;
		
		/** 倒地 */
		public static Lie:number=2;
		
		/** 浮空(自由下落) */
		public static Blow:number=3;
		
		/** 飞行(漂浮) */
		public static Fly:number=4;
		
		/** 长度 */
		public static size:number=5;
		
	}
}
