using ShineEngine;

/// <summary>
/// 上架拍卖行物品消息(generated by shine)
/// </summary>
public class FuncAuctionSellItemRequest:FuncRRequest
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=GameRequestType.FuncAuctionSellItem;
	
	/// <summary>
	/// 物品id
	/// </summary>
	public int itemID;
	
	/// <summary>
	/// 物品格子
	/// </summary>
	public int index;
	
	/// <summary>
	/// 上架数目
	/// </summary>
	public int num;
	
	/// <summary>
	/// 单价
	/// </summary>
	public int onePrice;
	
	public FuncAuctionSellItemRequest()
	{
		_dataID=GameRequestType.FuncAuctionSellItem;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "FuncAuctionSellItemRequest";
	}
	
	/// <summary>
	/// 写入字节流(完整版)
	/// </summary>
	protected override void toWriteBytesFull(BytesWriteStream stream)
	{
		base.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.index);
		
		stream.writeInt(this.itemID);
		
		stream.writeInt(this.num);
		
		stream.writeInt(this.onePrice);
		
		stream.endWriteObj();
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		stream.writeInt(this.index);
		
		stream.writeInt(this.itemID);
		
		stream.writeInt(this.num);
		
		stream.writeInt(this.onePrice);
		
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("index");
		writer.sb.Append(':');
		writer.sb.Append(this.index);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("itemID");
		writer.sb.Append(':');
		writer.sb.Append(this.itemID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("num");
		writer.sb.Append(':');
		writer.sb.Append(this.num);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("onePrice");
		writer.sb.Append(':');
		writer.sb.Append(this.onePrice);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		this.index=0;
		this.itemID=0;
		this.num=0;
		this.onePrice=0;
	}
	
	protected override void copyData()
	{
		base.copyData();
	}
	
	/// <summary>
	/// 创建实例
	/// </summary>
	public static FuncAuctionSellItemRequest create(int funcID,int index,int itemID,int num,int onePrice)
	{
		FuncAuctionSellItemRequest re=(FuncAuctionSellItemRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.index=index;
		re.itemID=itemID;
		re.num=num;
		re.onePrice=onePrice;
		return re;
	}
	
}
