package com.home.commonGame.net.response.role;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.logic.unit.MUnitUseLogic;
import com.home.commonGame.net.base.GameResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 主单位消息基类(generated by shine) */
public class MUnitRResponse extends GameResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.MUnitR;
	
	/** 单位序号 */
	public int mIndex;
	
	/** 主单位使用逻辑 */
	protected MUnitUseLogic mLogic;
	
	public MUnitRResponse()
	{
		_dataID=GameResponseType.MUnitR;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "MUnitRResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.mIndex=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.mIndex=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("mIndex");
		writer.sb.append(':');
		writer.sb.append(this.mIndex);
		
		writer.writeEnter();
	}
	
	@Override
	protected void preExecute()
	{
		if(me==null)
			return;
		
		if((mLogic=me.character.getMUnitUseLogic(mIndex))==null)
			return;
		
		doExecute();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.mIndex=0;
	}
	
}
