package com.home.commonGame.net.response.role;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.net.response.role.MUnitRResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 主单位切换属性开关(generated by shine) */
public class MUnitAttributeSwitchNormalSendResponse extends MUnitRResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.MUnitAttributeSwitchNormalSend;
	
	/** 是否开启 */
	public boolean isOpen;
	
	public MUnitAttributeSwitchNormalSendResponse()
	{
		_dataID=GameResponseType.MUnitAttributeSwitchNormalSend;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		mLogic.getFightLogic().setNormalSendOpen(isOpen);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "MUnitAttributeSwitchNormalSendResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.isOpen=stream.readBoolean();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.isOpen=stream.readBoolean();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("isOpen");
		writer.sb.append(':');
		writer.sb.append(this.isOpen);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.isOpen=false;
	}
	
}
