package com.home.commonBase.data.system;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 游戏服运行数据(generated by shine) */
public class GameServerRunData extends BaseData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.GameServerRun;
	
	/** 在线人数 */
	public int onlineNum;
	
	/** gameID */
	public int id;
	
	public GameServerRunData()
	{
		_dataID=BaseDataType.GameServerRun;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GameServerRunData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.id=stream.readInt();
		
		this.onlineNum=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeInt(this.id);
		
		stream.writeInt(this.onlineNum);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.id=stream.readInt();
		
		this.onlineNum=stream.readInt();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeInt(this.id);
		
		stream.writeInt(this.onlineNum);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof GameServerRunData))
			return;
		
		GameServerRunData mData=(GameServerRunData)data;
		
		this.id=mData.id;
		this.onlineNum=mData.onlineNum;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof GameServerRunData))
			return;
		
		GameServerRunData mData=(GameServerRunData)data;
		
		this.id=mData.id;
		
		this.onlineNum=mData.onlineNum;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		GameServerRunData mData=(GameServerRunData)data;
		if(this.id!=mData.id)
			return false;
		
		if(this.onlineNum!=mData.onlineNum)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("id");
		writer.sb.append(':');
		writer.sb.append(this.id);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("onlineNum");
		writer.sb.append(':');
		writer.sb.append(this.onlineNum);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.id=0;
		this.onlineNum=0;
	}
	
}
