package com.home.commonBase.data.system;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.system.WorkData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** 游戏服(角色)离线事务数据(废弃)(generated by shine) */
public class GameGlobalWorkData extends WorkData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.GameGlobalWork;
	
	public GameGlobalWorkData()
	{
		_dataID=BaseDataType.GameGlobalWork;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GameGlobalWorkData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
}
