package com.home.commonBase.data.system;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.system.WorkData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 角色事务数据(generated by shine) */
public class PlayerWorkData extends WorkData
{
	/** 接受者playerID */
	public long receivePlayerID;
	
	/** 数据类型ID */
	public static final int dataID=BaseDataType.PlayerWork;
	
	public PlayerWorkData()
	{
		_dataID=BaseDataType.PlayerWork;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "PlayerWorkData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.receivePlayerID=stream.readLong();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeLong(this.receivePlayerID);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.receivePlayerID=stream.readLong();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.receivePlayerID);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		super.toShadowCopy(data);
		
		if(!(data instanceof PlayerWorkData))
			return;
		
		PlayerWorkData mData=(PlayerWorkData)data;
		
		this.receivePlayerID=mData.receivePlayerID;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		super.toCopy(data);
		
		if(!(data instanceof PlayerWorkData))
			return;
		
		PlayerWorkData mData=(PlayerWorkData)data;
		
		this.receivePlayerID=mData.receivePlayerID;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		if(!super.toDataEquals(data))
			return false;
		
		PlayerWorkData mData=(PlayerWorkData)data;
		if(this.receivePlayerID!=mData.receivePlayerID)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("receivePlayerID");
		writer.sb.append(':');
		writer.sb.append(this.receivePlayerID);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		super.initDefault();
		
	}
	
	public PlayerWorkCompleteData createCompleteData()
	{
		PlayerWorkCompleteData re=new PlayerWorkCompleteData();
		re.workInstanceID=this.workInstanceID;
		re.senderIndex=this.senderIndex;
		re.receivePlayerID=this.receivePlayerID;
		return re;
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.receivePlayerID=0L;
	}
	
}
