package com.home.commonBase.constlist.generate;

/** aoi优先级类型(generated by shine) */
public class AOIPriorityType
{
	/** 最高优先级(自己的单位,组队成员) */
	public static final int Self=0;
	
	/** 优先级高(好友,工会,boss,服务器npc) */
	public static final int High=1;
	
	/** 怪物 */
	public static final int Normal=2;
	
	/** 辅助单位 */
	public static final int Low=3;
	
	/** 长度 */
	public static int size=4;
	
}
