package com.home.commonBase.constlist.generate;

/** 攻击行为类型(generated by shine) */
public class AttackActionType
{
	/** 攻击 arg1:攻击ID arg2:攻击等级 */
	public static final int Attack=1;
	
	/** 子弹 arg1:子弹等级 arg2:子弹等级 */
	public static final int Bullet=2;
	
	/** 自身添加固定属性 arg1:属性类型,arg2:属性值 */
	public static final int SelfAddAttribute=3;
	
	/** 目标添加固定属性 arg1:属性类型,arg2:属性值 */
	public static final int TargetAddAttribute=4;
	
	/** 自身添加变量属性 arg1:属性类型,arg2:变量ID */
	public static final int SelfAddAttributeVar=5;
	
	/** 目标添加变量属性 arg1:属性类型,arg2:变量ID */
	public static final int TargetAddAttributeVar=6;
	
	/** 自身特殊移动 arg1:特殊移动ID */
	public static final int SelfSpecialMove=7;
	
	/** 目标特殊移动 arg1:特殊移动ID */
	public static final int TargetSpecialMove=8;
	
	/** 自身添加buff arg1:id arg2:level */
	public static final int SelfAddBuff=9;
	
	/** 目标添加buff arg1:id arg2:level */
	public static final int TargetAddBuff=10;
	
	/** 自身增加当前组CD时间经过 arg1:组ID arg2:时间(ms) */
	public static final int AddGroupTimePass=11;
	
	/** 自身移除组CD arg1:组ID */
	public static final int RemoveGroupCD=12;
	
	/** 在目标点创建傀儡 arg1:傀儡ID arg2:傀儡等级 */
	public static final int AddPuppetAtTarget=13;
	
	/** 自杀 */
	public static final int KillSelf=14;
	
	/** 击杀目标 */
	public static final int KillTarget=15;
	
	/** 直接移除某组buff arg1:组ID */
	public static final int SelfRemoveGroupBuff=16;
	
	/** 目标移除某组buff arg1:组ID */
	public static final int TargetRemoveGroupBuff=17;
	
	/** 打断在某组中的正在释放的技能 arg1:组ID */
	public static final int BreakSkill=18;
	
	/** 长度 */
	public static int size=19;
	
}
