package com.home.commonBase.constlist.generate;

/** (generated by shine) */
public class BaseDataType
{
	/** 起始 */
	public static final int off=200;
	
	/** 计数 */
	public static final int count=450;
	
	/** 成就完成数据 */
	public static final int AchievementComplete=200;
	
	/** 成就数据 */
	public static final int Achievement=201;
	
	/** 成就存库数据 */
	public static final int AchievementSave=202;
	
	/** 活动数据(个人)(与存库数据一致) */
	public static final int Activity=203;
	
	/** 活动服务器保存数据 */
	public static final int ActivityServer=204;
	
	/** 添加被好友离线事务 */
	public static final int AddBeFriendOW=205;
	
	/** 添加好友失败 */
	public static final int AddFriendFailedForOvonicAW=206;
	
	/** 添加好友(双向)立即事务 */
	public static final int AddFriendForOvonicAW=207;
	
	/** 添加邮件离线事务 */
	public static final int AddMailOW=208;
	
	/** 申请添加好友数据 */
	public static final int ApplyAddFriend=209;
	
	/** 申请添加好友离线事务 */
	public static final int ApplyAddFriendOW=210;
	
	/** 区服客户端数据 */
	public static final int AreaClient=211;
	
	/** 场景服进入数据 */
	public static final int SceneServerEnter=212;
	
	/** buff数据 */
	public static final int Buff=213;
	
	/** 子弹数据 */
	public static final int Bullet=214;
	
	/** 冷却数据 */
	public static final int CD=215;
	
	/** 角色身份数据基类 */
	public static final int CharacterIdentity=216;
	
	/** 角色保存数据 */
	public static final int CharacterSave=217;
	
	/** 角色使用数据 */
	public static final int CharacterUse=218;
	
	/** 聊天数据 */
	public static final int Chat=219;
	
	/** 聊天元素数据 */
	public static final int ChatElement=220;
	
	/** 客户端登录缓存数据 */
	public static final int ClientLoginCache=221;
	
	/** 客户端登录数据(可以有继承) */
	public static final int ClientLogin=222;
	
	/** 客户端登录扩展数据 */
	public static final int ClientLoginEx=223;
	
	/** 客户端离线事务数据 */
	public static final int ClientOfflineWork=224;
	
	/** 客户端离线事务组消息 */
	public static final int ClientOfflineWorkList=225;
	
	/** 客户端本地角色缓存数据 */
	public static final int ClientPlayerLocalCache=226;
	
	/** 客户端版本数据 */
	public static final int ClientVersion=227;
	
	/** 联系人数据 */
	public static final int Contact=228;
	
	/** 创建角色数据 */
	public static final int CreatePlayer=229;
	
	/** 单个伤害数据 */
	public static final int DamageOne=230;
	
	/** 朝向数据 */
	public static final int Dir=231;
	
	/** 帧同步指令数据 */
	public static final int FrameSyncCommand=232;
	
	/** 帧同步数据 */
	public static final int FrameSync=233;
	
	/** 好友数据(maybeExtends) */
	public static final int Friend=234;
	
	/** 功能插件数据 */
	public static final int FuncTool=235;
	
	/** gm添加货币离线事务 */
	public static final int GMAddCurrencyOW=236;
	
	/** 游戏服(角色)离线事务数据(废弃) */
	public static final int GameGlobalWork=237;
	
	/** 游戏服登录中心服返回数据 */
	public static final int GameLogin=238;
	
	/** 游戏服给客户端的简版数据 */
	public static final int GameServerClientSimple=239;
	
	/** 游戏服信息数据 */
	public static final int GameServerInfo=240;
	
	/** 游戏服运行数据 */
	public static final int GameServerRun=241;
	
	/** 简版游戏服信息数据 */
	public static final int GameServerSimpleInfo=242;
	
	/** int查询结果数据 */
	public static final int IntQueryResult=243;
	
	/** 道具容器数据 */
	public static final int ItemContainer=244;
	
	/** 物品数据 */
	public static final int Item=245;
	
	/** 物品装备数据 */
	public static final int ItemEquip=246;
	
	/** 物品身份数据(extends) */
	public static final int ItemIdentity=247;
	
	/** 保存数据(启动main过程用) */
	public static final int KeepSave=248;
	
	/** key数据 */
	public static final int Key=249;
	
	/** 主单位缓存数据 */
	public static final int MUnitCache=250;
	
	/** 主单位(可脱离场景存在的)使用数据 */
	public static final int MUnitUse=251;
	
	/** 邮件数据 */
	public static final int Mail=252;
	
	/** 怪物身份数据 */
	public static final int MonsterIdentity=253;
	
	/** npc身份数据 */
	public static final int NPCIdentity=254;
	
	/** 主单位身份数据 */
	public static final int MUnitIdentity=255;
	
	public static final int PetUse=256;
	
	public static final int GameAuctionTool=257;
	
	/** 角色登录数据 */
	public static final int PlayerLogin=258;
	
	/** 玩家邮件 */
	public static final int PlayerMail=259;
	
	/** 角色匹配数据 */
	public static final int PlayerMatch=260;
	
	/** 角色离线缓存附加数据 */
	public static final int PlayerOfflineCacheEx=261;
	
	/** 角色主键数据 */
	public static final int PlayerPrimaryKey=262;
	
	/** 角色排行数据 */
	public static final int PlayerRank=263;
	
	/** 角色排行工具数据 */
	public static final int PlayerRankTool=264;
	
	/** 角色切换游戏服额外传输数据(在PlayerList之外) */
	public static final int PlayerSwitchGame=265;
	
	/** 角色事务数据 */
	public static final int PlayerWork=266;
	
	/** 角色事务组数据 */
	public static final int PlayerWorkList=267;
	
	/** 位置数据 */
	public static final int Pos=268;
	
	/** 位置朝向数据 */
	public static final int PosDir=269;
	
	/** 傀儡单位身份数据 */
	public static final int PuppetIdentity=270;
	
	/** 查询角色等级事务(测试) */
	public static final int QueryPlayerLevelW=271;
	
	/** 任务完成数据(周期类用) */
	public static final int QuestComplete=272;
	
	/** 任务数据(已接) */
	public static final int Quest=273;
	
	/** 排行榜基础数据 */
	public static final int Rank=274;
	
	/** 简单排名数据 */
	public static final int RankSimple=275;
	
	/** 排行榜数据(存库数据) */
	public static final int RankTool=276;
	
	/** 回复获取角色社交数据在线数据 */
	public static final int ReGetRoleSocialDataW=277;
	
	/** 刷新部分角色数据在线事务数据 */
	public static final int RefreshPartRoleShowDataW=278;
	
	/** 移除被好友离线事务 */
	public static final int RemoveBeFriendOW=279;
	
	/** 执行移除好友离线事务 */
	public static final int RemoveFriendOW=280;
	
	/** 角色显示改变数据(maybeExtends) */
	public static final int RoleShowChange=281;
	
	/** 玩家展示数据 */
	public static final int RoleShow=282;
	
	/** 角色社交数据 */
	public static final int RoleSocial=283;
	
	/** 存库数据版本 */
	public static final int SaveVersion=284;
	
	/** 场景特效身份数据 */
	public static final int SceneEffectIdentity=285;
	
	/** 场景进入参数数据 */
	public static final int SceneEnterArg=286;
	
	/** 场景进入数据 */
	public static final int SceneEnter=287;
	
	/** 场景预备信息数据 */
	public static final int ScenePreInfo=288;
	
	/** 服务器启动信息 */
	public static final int ServerInfo=289;
	
	/** 中心服简版连接数据 */
	public static final int ServerSimpleInfo=290;
	
	/** 技能数据 */
	public static final int Skill=291;
	
	/** 技能目标数据 */
	public static final int SkillTarget=292;
	
	/** 任务目标数据(extends) */
	public static final int Task=293;
	
	public static final int Test2=294;
	
	/** 测试数据 */
	public static final int Test=295;
	
	/** 单位AI数据 */
	public static final int UnitAI=296;
	
	/** 单位造型数据 */
	public static final int UnitAvatar=297;
	
	/** 单位数据 */
	public static final int Unit=298;
	
	/** 战斗基础数据(4元素+cd) */
	public static final int UnitFight=299;
	
	/** 附加战斗数据 */
	public static final int UnitFightEx=300;
	
	/** 单位身份数据 */
	public static final int UnitIdentity=301;
	
	/** 单位信息数据 */
	public static final int UnitInfo=302;
	
	/** 单位位置数据 */
	public static final int UnitPos=303;
	
	/** 使用物品参数数据 */
	public static final int UseItemArg=304;
	
	/** 载具身份数据 */
	public static final int VehicleIdentity=305;
	
	/** 基础事务数据(用dataID区分) */
	public static final int Work=306;
	
	/** 事务接收者数据 */
	public static final int WorkReceiver=307;
	
	/** 事务发起者数据 */
	public static final int WorkSender=308;
	
	/** 拍卖行回复出售结果事务数据 */
	public static final int AuctionReSellItemOW=309;
	
	/** 邀请玩家群接收数据 */
	public static final int InviteRoleGroupReceive=310;
	
	/** 拍卖行临时购买物品数据 */
	public static final int AuctionBuyItem=311;
	
	/** 物品列表容器工具数据 */
	public static final int ItemDicContainer=312;
	
	/** 拍卖行回复购买物品数据 */
	public static final int AuctionReBuyItemOW=313;
	
	/** 角色社交池数据 */
	public static final int RoleSocialPool=314;
	
	/** 角色社交数据池工具数据 */
	public static final int RoleSocialPoolTool=315;
	
	/** 查询角色abs事务 */
	public static final int QueryPlayerAW=316;
	
	/** 查询角色结果数据 */
	public static final int QueryPlayerResult=317;
	
	/** 回复查询角色在线数据 */
	public static final int ReQueryPlayerOW=318;
	
	/** 更新出售物品数目 */
	public static final int AuctionSoldItemOW=319;
	
	/** 大浮点数 */
	public static final int BigFloat=320;
	
	public static final int FuncInfoLog=321;
	
	/** 拍卖行移除上架物品 */
	public static final int AuctionRemoveSellItemOW=322;
	
	/** 操作体身份数据 */
	public static final int OperationIdentity=323;
	
	/** 掉落物品身份数据 */
	public static final int FieldItemIdentity=324;
	
	/** 战斗单位身份数据 */
	public static final int FightUnitIdentity=325;
	
	/** 装备容器数据 */
	public static final int EquipContainer=326;
	
	/** 主单位存库数据 */
	public static final int MUnitSave=327;
	
	/** 宠物存库数据 */
	public static final int PetSave=328;
	
	/** 玩家属性数据 */
	public static final int RoleAttribute=329;
	
	/** 场景角色数据 */
	public static final int SceneRole=330;
	
	/** 建筑身份数据 */
	public static final int BuildingIdentity=331;
	
	/** 角色势力数据 */
	public static final int RoleForce=332;
	
	/** 分段排行榜数据(存库数据) */
	public static final int SubsectionRankTool=333;
	
	/** 客户端登陆服务器地址信息 */
	public static final int ClientLoginServerInfo=334;
	
	/** 玩家身上的玩家群工具数据 */
	public static final int PlayerRoleGroupTool=335;
	
	/** 玩家群数据(单个群) */
	public static final int RoleGroup=336;
	
	/** 玩家群成员数据 */
	public static final int RoleGroupMember=337;
	
	/** 玩家群数据 */
	public static final int RoleGroupTool=338;
	
	/** 客户端登陆结果数据 */
	public static final int ClientLoginResult=339;
	
	/** 区服服务器数据 */
	public static final int AreaServer=340;
	
	/** 角色绑定平台事务 */
	public static final int PlayerBindPlatformAW=341;
	
	/** 简单排名数据 */
	public static final int SubsectionRankSimple=342;
	
	/** 角色排行工具数据 */
	public static final int PlayerSubsectionRankTool=343;
	
	/** 角色登录到其他逻辑服的数据 */
	public static final int PlayerLoginToEachGame=344;
	
	public static final int RePlayerLoginFromEachGame=345;
	
	/** 宠物身份数据 */
	public static final int PetIdentity=346;
	
	/** 角色事务完成数据 */
	public static final int PlayerWorkComplete=347;
	
	/** 事务完成数据 */
	public static final int WorkComplete=348;
	
	/** 中心服初始化服务器数据 */
	public static final int CenterInitServer=349;
	
	/** 区服全局数据 */
	public static final int AreaGlobalWork=350;
	
	public static final int SceneInitServer=351;
	
	/** 副本类场景进入数据 */
	public static final int BattleScene=352;
	
	/** 区服完成事务 */
	public static final int AreaGlobalWorkComplete=353;
	
	/** 创建玩家群参数 */
	public static final int CreateRoleGroup=354;
	
	/** 角色自身玩家群存库数据 */
	public static final int PlayerRoleGroupSave=355;
	
	/** 场景服离开数据 */
	public static final int SceneServerExit=356;
	
	/** 角色玩家群数据(推送客户端的) */
	public static final int PlayerRoleGroup=357;
	
	/** 玩家申请进入玩家群数据(如需可补申请语) */
	public static final int PlayerApplyRoleGroup=358;
	
	/** 匹配后的场景信息 */
	public static final int MatchScene=359;
	
	/** 玩家群简版数据 */
	public static final int RoleGroupSimple=360;
	
	/** 创建玩家群结果消息(退回cost用) */
	public static final int CreateRoleGroupResultOW=361;
	
	/** 创建玩家群事务 */
	public static final int CreateRoleGroupW=362;
	
	/** 邀请进入玩家群消息 */
	public static final int InviteRoleGroupW=363;
	
	/** 角色功能事务数据 */
	public static final int PlayerFuncWork=364;
	
	/** 角色申请玩家群自身数据 */
	public static final int PlayerApplyRoleGroupSelf=365;
	
	/** 添加自身申请玩家群事务 */
	public static final int AddApplyRoleGroupSelfW=366;
	
	/** 处理申请结果事务 */
	public static final int HandleApplyRoleGroupW=367;
	
	/** 玩家群变更数据 */
	public static final int RoleGroupChange=368;
	
	/** 玩家群客户端工具数据 */
	public static final int PlayerRoleGroupClientTool=369;
	
	/** 角色身上工会数据 */
	public static final int PlayerUnion=370;
	
	/** 工会数据 */
	public static final int Union=371;
	
	/** 工会成员数据 */
	public static final int UnionMember=372;
	
	/** 创建工会数据 */
	public static final int CreateUnion=373;
	
	/** 工会简版数据 */
	public static final int UnionSimple=374;
	
	/** 角色工会存储数据 */
	public static final int PlayerUnionSave=375;
	
	/** 加入玩家群事务 */
	public static final int JoinRoleGroupW=376;
	
	/** 离开玩家群事务 */
	public static final int LeaveRoleGroupW=377;
	
	/** 使用激活码成功 */
	public static final int UseActivationCodeSuccessOW=378;
	
	/** 队伍数据 */
	public static final int Team=379;
	
	/** 创建队伍参数 */
	public static final int CreateTeam=380;
	
	public static final int PlayerTeam=381;
	
	/** 玩家匹配成功事务 */
	public static final int PlayerMatchSuccessW=382;
	
	/** 队伍成员数据 */
	public static final int TeamMember=383;
	
	/** 队伍简版数据 */
	public static final int TeamSimple=384;
	
	/** 角色创建事务 */
	public static final int PlayerCreatedW=385;
	
	/** 用户事务(login服执行,要求事务本身幂等，因为login上目前没做事务序号存储) */
	public static final int UserWork=386;
	
	public static final int PlayerDeletedW=387;
	
	/** 信息日志数据 */
	public static final int InfoLog=388;
	
	/** 带角色外线日志数据 */
	public static final int RoleShowLog=389;
	
	/** 信息日志事务数据 */
	public static final int InfoLogW=390;
	
	/** 逻辑服初始化服务器数据 */
	public static final int GameInitServer=391;
	
	/** 登陆服初始化服务器数据 */
	public static final int LoginInitServer=392;
	
	/** 逻辑服登陆返回给中心服数据 */
	public static final int GameLoginToCenter=393;
	
	/** 逻辑服登陆到逻辑服消息(发过去) */
	public static final int GameLoginToGame=396;
	
	/** 玩家到玩家tcc事务基类 */
	public static final int PlayerToPlayerTCCW=397;
	
	/** 角色到玩家群tcc事务基类 */
	public static final int PlayerToRoleGroupTCCW=398;
	
	/** 玩家群事务 */
	public static final int RoleGroupWork=399;
	
	/** 角色到玩家群TCC事务结果 */
	public static final int PlayerToRoleGroupTCCResultW=400;
	
	/** 玩家到玩家TCC结果数据 */
	public static final int PlayerToPlayerTCCResultW=401;
	
	/** 玩家展示日志数据 */
	public static final int RoleShowInfoLog=402;
	
	/** 创建场景数据 */
	public static final int CreateScene=403;
	
	/** 玩家群创建场景数据 */
	public static final int RoleGroupCreateScene=404;
	
	/** 角色玩家群成员数据 */
	public static final int PlayerRoleGroupMember=405;
	
	/** 玩家群成员变更数据 */
	public static final int RoleGroupMemberChange=406;
	
	/** 玩家群补充数据(不实时推送的部分) */
	public static final int PlayerRoleGroupEx=407;
	
	/** 单位功能数据 */
	public static final int UnitFunc=408;
	
	/** 单位移动数据 */
	public static final int UnitMove=409;
	
	/** 掉落包身份数据 */
	public static final int FieldItemBagIdentity=410;
	
	/** 单位通用数据 */
	public static final int UnitNormal=412;
	
	/** 掉落物品包绑定数据 */
	public static final int FieldItemBagBind=413;
	
	/** 矩形数据 */
	public static final int Rect=414;
	
	/** 物品聊天元素数据 */
	public static final int ItemChatElement=416;
	
	/** 聊天频道数据 */
	public static final int ChatChannel=417;
	
	/** 角色聊天数据 */
	public static final int RoleChat=418;
	
	/** 角色简版外显数据(聊天等使用) */
	public static final int RoleSimpleShow=419;
	
	/** 推送玩家聊天 */
	public static final int SendPlayerChatOW=420;
	
	/** 场景位置数据 */
	public static final int SceneLocation=423;
	
	/** 场景位置社交改变数据 */
	public static final int SceneLocationRoleShowChange=425;
	
	/** 区域数据 */
	public static final int Region=426;
	
	/** 单位简版数据(只位置,血量,身份) */
	public static final int UnitSimple=427;
	
	/** 中心服玩家群工具数据 */
	public static final int CenterRoleGroupTool=430;
	
	/** 创建玩家群到中心服事务 */
	public static final int CreateRoleGroupToCenterW=431;
	
	/** 中心服事务数据 */
	public static final int CenterGlobalWork=432;
	
	/** 移除玩家群到中心服事务 */
	public static final int RemoveRoleGroupToCenterW=433;
	
	/** 玩集群排行数据 */
	public static final int RoleGroupRank=434;
	
	/** 驾驶数据 */
	public static final int Drive=435;
	
	/** 玩家删除到中心服消息 */
	public static final int PlayerDeletedToCenterW=438;
	
	/** 拍卖物品数据 */
	public static final int AuctionItem=439;
	
	/** 拍卖行出售物品日志 */
	public static final int AuctionSoldLog=442;
	
	/** 拍卖行物品记录数据 */
	public static final int AuctionItemRecord=444;
	
	/** 拍卖行工具数据 */
	public static final int AuctionTool=445;
	
	/** 计数数据 */
	public static final int Count=446;
	
	/** 拍卖行查询条件基类 */
	public static final int AuctionQueryCondition=447;
	
	/** 整形拍卖行查询条件 */
	public static final int IntAuctionQueryCondition=448;
	
	/** 玩家拍卖行工具数据 */
	public static final int PlayerAuctionTool=449;
	
}
