package com.home.commonBase.constlist.generate;

/** 客户端游戏类型(generated by shine) */
public class GameEventType
{
	/** 前后台切换事件 */
	public static final int ApplicationPause=2;
	
	/** 刷新服务器时间 */
	public static final int RefreshServerOffTime=5;
	
	/** 配置热更 */
	public static final int ReloadConfig=6;
	
	/** 刷新货币(data:type) */
	public static final int RefreshCurrency=7;
	
	/** 刷新角色经验 */
	public static final int RefreshExp=8;
	
	/** 角色升级(data:oldLevel) */
	public static final int RoleLevelUp=9;
	
	/** 角色改名 */
	public static final int RoleChangeName=10;
	
	/** 红点更新(data:type) */
	public static final int RefreshRedPoint=11;
	
	/** 绑定平台成功 */
	public static final int BindPlatformSuccess=12;
	
	/** 初始化全部客户端数据(离线游戏用) */
	public static final int InitClient=13;
	
	/** 刷新角色战斗力 */
	public static final int RefreshFightForce=14;
	
	/** 信息日志更新(data:InfoLogData) */
	public static final int RefreshInfoLog=15;
	
	/** 进入场景消息(data:sceneID) */
	public static final int EnterScene=19;
	
	/** 退出当前场景(data:sceneID) */
	public static final int LeaveScene=20;
	
	/** 退出最后场景结束 */
	public static final int LeaveLastSceneOver=21;
	
	/** 主角单位状态变化(arg0:index,arg1:changeSet) */
	public static final int MUnitStatusChange=22;
	
	/** 主角单位属性变化(arg0:index,arg1:changeSet) */
	public static final int MUnitAttributeChange=23;
	
	/** 主角单位CD(arg0:index) */
	public static final int MUnitCDChange=24;
	
	/** 主角单位buff组更新(add/remove/refresh) */
	public static final int MUnitBuffChange=25;
	
	/** 主角造型模型变化 */
	public static final int MUnitAvatarModelChange=26;
	
	/** 主角造型部件变化 */
	public static final int MUnitAvatarPartChange=27;
	
	/** 主角单位技能组更新(add/remove/refresh) */
	public static final int MUnitSkillChange=28;
	
	/** 主角色属性变化(arg1:changeSet) */
	public static final int MRoleAttributeChange=29;
	
	/** 单位驾驶状态改变 */
	public static final int OnUnitDriveChange=30;
	
	/** 载具驾驶状态改变 */
	public static final int OnVehicleDriveChange=31;
	
	/** 功能开启(data:functionID) */
	public static final int FunctionOpen=35;
	
	/** 功能关闭(data:functionID) */
	public static final int FunctionClose=36;
	
	/** 活动开启(data:activityID) */
	public static final int ActivityOpen=37;
	
	/** 活动关闭(data:activityID) */
	public static final int ActivityClose=38;
	
	/** 活动重置(data:activityID) */
	public static final int ActivityReset=39;
	
	/** 活动可见(data:activityID) */
	public static final int ActivitySee=40;
	
	/** 活动不可见(data:activityID) */
	public static final int ActivityCantSee=41;
	
	/** 活动完成一次(data:activityID) */
	public static final int ActivityCompleteOnce=42;
	
	/** 副本状态更新 */
	public static final int BattleStateChange=45;
	
	/** 开始匹配消息 */
	public static final int StartMatch=48;
	
	/** 其他人同意匹配消息(playerID) */
	public static final int PlayerAcceptMatch=49;
	
	/** 取消匹配消息 */
	public static final int CancelMatch=50;
	
	/** 结束匹配消息 */
	public static final int MatchOver=51;
	
	/** 翻页插件数据更新(data:[funcID,page]) */
	public static final int FuncRefreshPageShow=54;
	
	/** 排行插件数据更新(data:funcID) */
	public static final int FuncRefreshRank=55;
	
	/** 分段翻页插件数据更新(data:[subsectionIndex,subsectionSubIndex,funcID,page]) */
	public static final int FuncRefreshSubsectionPageShow=56;
	
	/** 背包容器更新单格(data:[funcID,index]) */
	public static final int FuncItemContainerRefreshGrid=59;
	
	/** 背包容器全刷(整理)(data:funcID) */
	public static final int FuncItemContainerRefreshAll=60;
	
	/** 背包容器变化(data:funcID) */
	public static final int FuncItemContainerChange=61;
	
	/** 主背包容器更新单格(data:index) */
	public static final int MainBagRefreshGrid=62;
	
	/** 主背包容器全更新(整理) */
	public static final int MainBagRefreshAll=63;
	
	/** 主背包容器变化 */
	public static final int MainBagChange=64;
	
	/** 主背包某物品Id变化(data:itemID) */
	public static final int MainBagItemChange=65;
	
	/** 获得道具提示(data:List<ItemData>) */
	public static final int AddItemNotice=66;
	
	/** 获得奖励(data:RewardShowData) */
	public static final int AddReward=67;
	
	/** 装备容器更新(data:[funcID,slot]) */
	public static final int FuncEquipContainerRefreshGrid=70;
	
	/** 更新语言(国际化) */
	public static final int RefreshLanguage=73;
	
	/** 刷新全部邮件内容 */
	public static final int RefreshAllMails=76;
	
	/** 添加新邮件(data:index) */
	public static final int AddNewMail=77;
	
	/** 刷新新邮件数目 */
	public static final int RefreshNewMailNum=78;
	
	/** 更新一封邮件(data:index) */
	public static final int RefreshOneMail=79;
	
	/** 删除一封邮件(data:index) */
	public static final int DeleteOneMail=80;
	
	/** 领取一封邮件(data:index) */
	public static final int RewardOneMail=81;
	
	/** 刷新全部任务 */
	public static final int RefreshAllQuest=84;
	
	/** 刷新单个任务显示 */
	public static final int RefreshOneQuest=85;
	
	/** 刷新可接任务列表 */
	public static final int RefreshCanAcceptQuests=86;
	
	/** 刷新可视任务列表 */
	public static final int RefreshCanSeeQuests=87;
	
	/** 接收任务(data:id) */
	public static final int AcceptQuest=88;
	
	/** 提交任务(任务完成)(data:id) */
	public static final int CommitQuest=89;
	
	/** 任务失败(data:id) */
	public static final int QuestFaied=90;
	
	/** 放弃任务(data:id) */
	public static final int GiveUpQuest=91;
	
	/** 移除已接任务(data:id) */
	public static final int RemoveAcceptQuest=92;
	
	/** 刷新成就显示(data:id) */
	public static final int RefreshAchievement=95;
	
	/** 完成成就(data:id) */
	public static final int CompleteAchievement=96;
	
	/** 领取成就奖励成功(data:id) */
	public static final int GetAchievementReward=97;
	
	/** 社交数据更新 */
	public static final int UpdateSocialData=101;
	
	/** 收到聊天消息(data:NormalEvt,int0=channel,long0=key) */
	public static final int ReceiveChat=102;
	
	/** 添加好友(data:playerID) */
	public static final int AddFriend=105;
	
	/** 移除好友(data:playerID) */
	public static final int RemoveFriend=106;
	
	/** 收到好友申请(data:playerID) */
	public static final int ReceiveApplyFriend=107;
	
	/** 好友申请列表更新 */
	public static final int RefreshApplyFriendList=108;
	
	/** 添加好友黑名单(data:playerID) */
	public static final int AddFriendBlackList=109;
	
	/** 移除好友黑名单(data:playerID) */
	public static final int RemoveFriendBlackList=110;
	
	/** 加入玩家群(data:RoleGroupEvt->groupID,type) */
	public static final int JoinRoleGroup=113;
	
	/** 离开玩家群(data:RoleGroupEvt->groupID,type) */
	public static final int LeaveRoleGroup=114;
	
	/** 添加玩家群成员(data:RoleGroupEvt->groupID,targetID,type) */
	public static final int AddRoleGroupMember=115;
	
	/** 移除玩家群成员(data:RoleGroupEvt->groupID,targetID,type) */
	public static final int RemoveRoleGroupMember=116;
	
	/** 更新玩家群职位(data:RoleGroupEvt->groupID,targetID,oldTitle,newTitle) */
	public static final int RefreshRoleGroupTitle=117;
	
	/** 改变玩家群群主(data:RoleGroupEvt->groupID,targetID) */
	public static final int ChangeRoleGroupLeader=118;
	
	/** 改变玩家群数据(data:RoleGroupEvt->groupID,changeData) */
	public static final int ChangeRoleGroupData=119;
	
	/** 改变玩家群成员数据(data:RoleGroupEvt->groupID,targetID,changeData) */
	public static final int ChangeRoleGroupMemberData=120;
	
	/** 收到邀请进入玩家群(data:InviteRoleGroupTempData) */
	public static final int ReceiveInviteRoleGroup=121;
	
	/** 玩家群收到新的申请(data:RoleGroupEvt->groupID,applyData) */
	public static final int RoleGroupReceiveApply=122;
	
	/** 玩家群申请信息变化(data:RoleGroupEvt->groupID,applyData) */
	public static final int RoleGroupApplyChange=123;
	
	/** 玩家群自身申请信息变化(data:RoleGroupEvt->groupID) */
	public static final int RoleGroupSelfApplyChange=124;
	
	/** 玩家群自身申请信息结果(data:RoleGroupEvt->groupID) */
	public static final int RoleGroupSelfApplyResult=125;
	
	/** 玩家群邀请结果(data:RoleGroupEvt->groupID,roleShowData,result) */
	public static final int RoleGroupInviteResult=126;
	
	/** 玩家群更新信息日志(data:RoleGroupEvt->groupID) */
	public static final int RoleGroupRefreshInfoLog=127;
	
	/** 更新玩家群附加数据(data:RoleGroupEvt->groupID) */
	public static final int RefreshRoleGroupEx=128;
	
	/** 改变玩家群成员角色显示数据(data:RoleGroupEvt->groupID,targetID,type) */
	public static final int ChangeRoleGroupMemberRoleShowData=129;
	
	/** 长度 */
	public static int size=0;
	
}
