package com.home.commonBase.constlist.generate;

/** 技能变量公式类型(generated by shine) */
public class SkillVarFormulaType
{
	/** 单值 arg1 */
	public static final int Single=1;
	
	/** 默认2项 arg1*r(arg2) */
	public static final int Normal2=2;
	
	/** 默认3项 arg1*r(arg2)+arg3 */
	public static final int Normal3=3;
	
	/** 默认4项 (arg1*r(arg2)+arg3)*r(arg4) */
	public static final int Normal4=4;
	
	/** 两项和 arg1+arg2 */
	public static final int TwoPlus=5;
	
	/** 长度 */
	public static int size=6;
	
}
