package com.home.commonBase.constlist.generate;

/** 技能消耗类型(generated by shine) */
public class SkillCostType
{
	/** 血 */
	public static final int Hp=1;
	
	/** 蓝 */
	public static final int Mp=2;
	
	/** 长度 */
	public static int size=3;
	
}
