package com.home.commonCenter.net.serverResponse.game.social;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.social.RoleSocialData;
import com.home.commonCenter.global.CenterC;
import com.home.commonCenter.net.serverResponse.game.base.PlayerToCenterServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.IntObjectMap;
import com.home.shine.support.pool.DataPool;

/** 提交自定义社交数据到中心服(generated by shine) */
public class CommitCustomRoleSocialToCenterServerResponse extends PlayerToCenterServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.CommitCustomRoleSocialToCenter;
	
	/** 数据组(key:funcID) */
	public IntObjectMap<RoleSocialData> datas;
	
	public CommitCustomRoleSocialToCenterServerResponse()
	{
		_dataID=ServerMessageType.CommitCustomRoleSocialToCenter;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CommitCustomRoleSocialToCenterServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		int datasLen=stream.readLen();
		if(this.datas!=null)
		{
			this.datas.clear();
			this.datas.ensureCapacity(datasLen);
		}
		else
		{
			this.datas=new IntObjectMap<RoleSocialData>(RoleSocialData[]::new,datasLen);
		}
		
		IntObjectMap<RoleSocialData> datasT=this.datas;
		for(int datasI=datasLen-1;datasI>=0;--datasI)
		{
			int datasK;
			RoleSocialData datasV;
			datasK=stream.readInt();
			
			datasV=(RoleSocialData)stream.readDataSimpleNotNull();
			
			datasT.put(datasK,datasV);
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("datas");
		writer.sb.append(':');
		writer.sb.append("Map<int,RoleSocialData>");
		if(this.datas!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.datas.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.datas.isEmpty())
			{
				int datasKFreeValue=this.datas.getFreeValue();
				int[] datasKKeys=this.datas.getKeys();
				Object[] datasVValues=this.datas.getValues();
				for(int datasKI=datasKKeys.length-1;datasKI>=0;--datasKI)
				{
					int datasK=datasKKeys[datasKI];
					if(datasK!=datasKFreeValue)
					{
						RoleSocialData datasV=(RoleSocialData)datasVValues[datasKI];
						writer.writeTabs();
						writer.sb.append(datasK);
						
						writer.sb.append(':');
						if(datasV!=null)
						{
							datasV.writeDataString(writer);
						}
						else
						{
							writer.sb.append("RoleSocialData=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		CenterC.global.func.addCustomRoleSocialDatas(datas);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.datas=null;
	}
	
}
