package com.home.commonClient.net.response.role.munit;
import com.home.commonClient.constlist.generate.GameResponseType;
import com.home.commonClient.net.base.GameResponse;
import com.home.commonClient.net.response.role.munit.MUnitSResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.IntIntMap;
import com.home.shine.support.pool.DataPool;

/** 控制单位改变显示部件(generated by shine) */
public class MUnitRefreshAvatarPartResponse extends MUnitSResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.MUnitRefreshAvatarPart;
	
	/** 改变组 */
	public IntIntMap parts;
	
	public MUnitRefreshAvatarPartResponse()
	{
		_dataID=GameResponseType.MUnitRefreshAvatarPart;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		mLogic.getFightLogic().avatar.setAvatarPartByServer(parts);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "MUnitRefreshAvatarPartResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		int partsLen=stream.readLen();
		if(this.parts!=null)
		{
			this.parts.clear();
			this.parts.ensureCapacity(partsLen);
		}
		else
		{
			this.parts=new IntIntMap(partsLen);
		}
		
		IntIntMap partsT=this.parts;
		for(int partsI=partsLen-1;partsI>=0;--partsI)
		{
			int partsK;
			int partsV;
			partsK=stream.readInt();
			
			partsV=stream.readInt();
			
			partsT.put(partsK,partsV);
		}
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		int partsLen=stream.readLen();
		if(this.parts!=null)
		{
			this.parts.clear();
			this.parts.ensureCapacity(partsLen);
		}
		else
		{
			this.parts=new IntIntMap(partsLen);
		}
		
		IntIntMap partsT=this.parts;
		for(int partsI=partsLen-1;partsI>=0;--partsI)
		{
			int partsK;
			int partsV;
			partsK=stream.readInt();
			
			partsV=stream.readInt();
			
			partsT.put(partsK,partsV);
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("parts");
		writer.sb.append(':');
		writer.sb.append("Map<int,int>");
		if(this.parts!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.parts.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.parts.isEmpty())
			{
				int partsKFreeValue=this.parts.getFreeValue();
				long[] partsKTable=this.parts.getTable();
				long partsKEntry;
				for(int partsKI=partsKTable.length-1;partsKI>=0;--partsKI)
				{
					partsKEntry=partsKTable[partsKI];
					int partsK=(int)partsKEntry;
					if(partsK!=partsKFreeValue)
					{
						int partsV=(int)(partsKEntry>>>32);
						writer.writeTabs();
						writer.sb.append(partsK);
						
						writer.sb.append(':');
						writer.sb.append(partsV);
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.parts=null;
	}
	
}
