package com.home.commonBase.data.scene.unit.identity;
import com.home.commonBase.config.game.MonsterConfig;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.scene.unit.UnitIdentityData;
import com.home.commonBase.data.scene.unit.identity.FightUnitIdentityData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;

/** 怪物身份数据(generated by shine) */
public class MonsterIdentityData extends FightUnitIdentityData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.MonsterIdentity;
	
	public MonsterIdentityData()
	{
		_dataID=BaseDataType.MonsterIdentity;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "MonsterIdentityData";
	}
	
	@Override
	public int getFightUnitID()
	{
		return MonsterConfig.get(id).fightUnitID;
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
}
