package com.home.commonBase.config.game;
import com.home.commonBase.config.base.BaseConfig;
import com.home.commonBase.config.game.enumT.BuffActionTypeConfig;
import com.home.commonBase.constlist.generate.BuffActionType;
import com.home.commonBase.global.CommonSetting;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.ctrl.Ctrl;
import com.home.shine.global.ShineSetting;
import com.home.shine.support.collection.LongObjectMap;
import com.home.shine.support.collection.SMap;

/** buff等级表(generated by shine) */
public class BuffLevelConfig extends BaseConfig
{
	/** 存储集合 */
	private static LongObjectMap<BuffLevelConfig> _dic;
	
	/** 攻击id */
	public int id;
	
	/** 等级 */
	public int level;
	
	/** 动作组 */
	public int[][] actions;
	
	/** 持续时间(ms) */
	public int lastTime;
	
	/** 到(时间/次数)动作组 */
	public int[][] overActions;
	
	/** 到叠加次数动作组(只有叠层的有意义) */
	public int[][] plusMaxActions;
	
	/** 持续次数 */
	public int lastNum;
	
	/** 获取 */
	public static BuffLevelConfig get(int id,int level)
	{
		return _dic.get((long)id << 16 | (long)level);
	}
	
	/** 设置字典 */
	public static void setDic(LongObjectMap<BuffLevelConfig> dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static LongObjectMap<BuffLevelConfig> getDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		this.level=stream.readShort();
		
		int actionsLen=stream.readLen();
		if(this.actions==null || this.actions.length!=actionsLen)
		{
			this.actions=new int[actionsLen][];
		}
		int[][] actionsT=this.actions;
		for(int actionsI=0;actionsI<actionsLen;++actionsI)
		{
			int[] actionsV;
			int actionsVLen=stream.readLen();
			actionsV=new int[actionsVLen];
			int[] actionsVT=actionsV;
			for(int actionsVI=0;actionsVI<actionsVLen;++actionsVI)
			{
				int actionsVV;
				actionsVV=stream.readInt();
				
				actionsVT[actionsVI]=actionsVV;
			}
			
			actionsT[actionsI]=actionsV;
		}
		
		this.lastTime=stream.readInt();
		
		this.lastNum=stream.readShort();
		
		int overActionsLen=stream.readLen();
		if(this.overActions==null || this.overActions.length!=overActionsLen)
		{
			this.overActions=new int[overActionsLen][];
		}
		int[][] overActionsT=this.overActions;
		for(int overActionsI=0;overActionsI<overActionsLen;++overActionsI)
		{
			int[] overActionsV;
			int overActionsVLen=stream.readLen();
			overActionsV=new int[overActionsVLen];
			int[] overActionsVT=overActionsV;
			for(int overActionsVI=0;overActionsVI<overActionsVLen;++overActionsVI)
			{
				int overActionsVV;
				overActionsVV=stream.readInt();
				
				overActionsVT[overActionsVI]=overActionsVV;
			}
			
			overActionsT[overActionsI]=overActionsV;
		}
		
		int plusMaxActionsLen=stream.readLen();
		if(this.plusMaxActions==null || this.plusMaxActions.length!=plusMaxActionsLen)
		{
			this.plusMaxActions=new int[plusMaxActionsLen][];
		}
		int[][] plusMaxActionsT=this.plusMaxActions;
		for(int plusMaxActionsI=0;plusMaxActionsI<plusMaxActionsLen;++plusMaxActionsI)
		{
			int[] plusMaxActionsV;
			int plusMaxActionsVLen=stream.readLen();
			plusMaxActionsV=new int[plusMaxActionsVLen];
			int[] plusMaxActionsVT=plusMaxActionsV;
			for(int plusMaxActionsVI=0;plusMaxActionsVI<plusMaxActionsVLen;++plusMaxActionsVI)
			{
				int plusMaxActionsVV;
				plusMaxActionsVV=stream.readInt();
				
				plusMaxActionsVT[plusMaxActionsVI]=plusMaxActionsVV;
			}
			
			plusMaxActionsT[plusMaxActionsI]=plusMaxActionsV;
		}
		
	}
	
	/** 读完表后处理 */
	@Override
	protected void afterReadConfig()
	{
		super.afterReadConfig();
		
		if(ShineSetting.openCheck)
		{
			if(actions.length>= CommonSetting.buffActionIndexMax)
			{
				Ctrl.throwError("buffAction长度超出限制");
			}
		}
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		if(ShineSetting.openCheck)
		{
			boolean[] bSet=new boolean[BuffActionType.size];
			
			BuffLevelConfig[] values;
			BuffLevelConfig v;
			
			for(int i=(values=_dic.getValues()).length-1;i>=0;--i)
			{
				if((v=values[i])!=null)
				{
					for(int[] arr:v.actions)
					{
						int type=arr[0];
						
						if(BuffActionTypeConfig.get(type).isSingle)
						{
							if(bSet[type])
							{
								Ctrl.errorLog("单一BuffAction类型,配置了多个",type,v.id);
							}
							
							bSet[type]=true;
						}
					}
					
					for(int[] arr:v.actions)
					{
						int type=arr[0];
						if(BuffActionTypeConfig.get(type).isSingle)
						{
							bSet[type]=false;
						}
					}
				}
			}
		}
	}
	
	/** 获取 */
	public static BuffLevelConfig get(int id,short level)
	{
		return _dic.get((long)id << 16 | (long)level);
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
		stream.writeShort(this.level);
		
		if(this.actions!=null)
		{
			int[][] actionsT=this.actions;
			stream.writeLen(actionsT.length);
			for(int actionsVI=0,actionsVLen=actionsT.length;actionsVI<actionsVLen;++actionsVI)
			{
				int[] actionsV=actionsT[actionsVI];
				if(actionsV!=null)
				{
					int[] actionsVT=actionsV;
					stream.writeLen(actionsVT.length);
					for(int actionsVVI=0,actionsVVLen=actionsVT.length;actionsVVI<actionsVVLen;++actionsVVI)
					{
						int actionsVV=actionsVT[actionsVVI];
						stream.writeInt(actionsVV);
						
					}
				}
				else
				{
					nullObjError("actionsV");
				}
				
			}
		}
		else
		{
			nullObjError("actions");
		}
		
		stream.writeInt(this.lastTime);
		
		stream.writeShort(this.lastNum);
		
		if(this.overActions!=null)
		{
			int[][] overActionsT=this.overActions;
			stream.writeLen(overActionsT.length);
			for(int overActionsVI=0,overActionsVLen=overActionsT.length;overActionsVI<overActionsVLen;++overActionsVI)
			{
				int[] overActionsV=overActionsT[overActionsVI];
				if(overActionsV!=null)
				{
					int[] overActionsVT=overActionsV;
					stream.writeLen(overActionsVT.length);
					for(int overActionsVVI=0,overActionsVVLen=overActionsVT.length;overActionsVVI<overActionsVVLen;++overActionsVVI)
					{
						int overActionsVV=overActionsVT[overActionsVVI];
						stream.writeInt(overActionsVV);
						
					}
				}
				else
				{
					nullObjError("overActionsV");
				}
				
			}
		}
		else
		{
			nullObjError("overActions");
		}
		
		if(this.plusMaxActions!=null)
		{
			int[][] plusMaxActionsT=this.plusMaxActions;
			stream.writeLen(plusMaxActionsT.length);
			for(int plusMaxActionsVI=0,plusMaxActionsVLen=plusMaxActionsT.length;plusMaxActionsVI<plusMaxActionsVLen;++plusMaxActionsVI)
			{
				int[] plusMaxActionsV=plusMaxActionsT[plusMaxActionsVI];
				if(plusMaxActionsV!=null)
				{
					int[] plusMaxActionsVT=plusMaxActionsV;
					stream.writeLen(plusMaxActionsVT.length);
					for(int plusMaxActionsVVI=0,plusMaxActionsVVLen=plusMaxActionsVT.length;plusMaxActionsVVI<plusMaxActionsVVLen;++plusMaxActionsVVI)
					{
						int plusMaxActionsVV=plusMaxActionsVT[plusMaxActionsVVI];
						stream.writeInt(plusMaxActionsVV);
						
					}
				}
				else
				{
					nullObjError("plusMaxActionsV");
				}
				
			}
		}
		else
		{
			nullObjError("plusMaxActions");
		}
		
	}
	
}
