package com.home.commonBase.config.game;
import com.home.commonBase.config.base.BaseConfig;
import com.home.commonBase.config.game.enumT.SkillInfluenceTypeConfig;
import com.home.commonBase.constlist.generate.BuffSubNumType;
import com.home.commonBase.global.CommonSetting;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.support.collection.IntObjectMap;

/** buff表(generated by shine) */
public class BuffConfig extends BaseConfig
{
	/** 存储集合 */
	private static IntObjectMap<BuffConfig> _dic;
	
	/** 组ID */
	public int[] groups;
	
	/** 收益类型 */
	public int gainType;
	
	/** buffID */
	public int id;
	
	/** 叠加方式 */
	public int plusType;
	
	/** 叠加上限 */
	public int plusMax;
	
	/** 推送类型 */
	public int sendType;
	
	/** 是否死亡移除 */
	public boolean removeAtDead;
	
	/** 次数消耗类型 */
	public int[][] subNums;
	
	/** 次数消耗类型转 */
	public int[] subNumsDicT;
	
	/** 目标影响类型 */
	public int[] influenceType;
	
	/** 目标影响类型转 */
	public boolean[] influenceTypeT;
	
	/** 保留类型 */
	public int keepType;
	
	/** 获取 */
	public static BuffConfig get(int id)
	{
		return _dic.get(id);
	}
	
	/** 设置字典 */
	public static void setDic(IntObjectMap<BuffConfig> dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static IntObjectMap<BuffConfig> getDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		int groupsLen=stream.readLen();
		if(this.groups==null || this.groups.length!=groupsLen)
		{
			this.groups=new int[groupsLen];
		}
		int[] groupsT=this.groups;
		for(int groupsI=0;groupsI<groupsLen;++groupsI)
		{
			int groupsV;
			groupsV=stream.readInt();
			
			groupsT[groupsI]=groupsV;
		}
		
		this.gainType=stream.readInt();
		
		this.plusType=stream.readInt();
		
		this.plusMax=stream.readInt();
		
		this.sendType=stream.readInt();
		
		this.keepType=stream.readInt();
		
		this.removeAtDead=stream.readBoolean();
		
		int subNumsLen=stream.readLen();
		if(this.subNums==null || this.subNums.length!=subNumsLen)
		{
			this.subNums=new int[subNumsLen][];
		}
		int[][] subNumsT=this.subNums;
		for(int subNumsI=0;subNumsI<subNumsLen;++subNumsI)
		{
			int[] subNumsV;
			int subNumsVLen=stream.readLen();
			subNumsV=new int[subNumsVLen];
			int[] subNumsVT=subNumsV;
			for(int subNumsVI=0;subNumsVI<subNumsVLen;++subNumsVI)
			{
				int subNumsVV;
				subNumsVV=stream.readInt();
				
				subNumsVT[subNumsVI]=subNumsVV;
			}
			
			subNumsT[subNumsI]=subNumsV;
		}
		
		int influenceTypeLen=stream.readLen();
		if(this.influenceType==null || this.influenceType.length!=influenceTypeLen)
		{
			this.influenceType=new int[influenceTypeLen];
		}
		int[] influenceTypeT=this.influenceType;
		for(int influenceTypeI=0;influenceTypeI<influenceTypeLen;++influenceTypeI)
		{
			int influenceTypeV;
			influenceTypeV=stream.readInt();
			
			influenceTypeT[influenceTypeI]=influenceTypeV;
		}
		
	}
	
	@Override
	protected void afterReadConfig()
	{
		super.afterReadConfig();
		
		if(subNums.length>0)
		{
			subNumsDicT=new int[BuffSubNumType.size];
			
			int[] arr;
			
			for(int i=0;i<subNums.length;i++)
			{
				arr=subNums[i];
				
				if(arr.length>1)
				{
					subNumsDicT[arr[0]]=arr[1];
				}
			}
		}
		
		influenceTypeT=SkillInfluenceTypeConfig.getInfluenceSet(influenceType);
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		
	}
	
	/** 是否包含某组 */
	public boolean hasGroup(int groupID)
	{
		int[] groups;
		
		for(int i=(groups=this.groups).length-1;i>=0;--i)
		{
			if(groups[i]==groupID)
				return true;
		}
		
		return false;
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
		if(this.groups!=null)
		{
			int[] groupsT=this.groups;
			stream.writeLen(groupsT.length);
			for(int groupsVI=0,groupsVLen=groupsT.length;groupsVI<groupsVLen;++groupsVI)
			{
				int groupsV=groupsT[groupsVI];
				stream.writeInt(groupsV);
				
			}
		}
		else
		{
			nullObjError("groups");
		}
		
		stream.writeInt(this.gainType);
		
		stream.writeInt(this.plusType);
		
		stream.writeInt(this.plusMax);
		
		stream.writeInt(this.sendType);
		
		stream.writeInt(this.keepType);
		
		stream.writeBoolean(this.removeAtDead);
		
		if(this.subNums!=null)
		{
			int[][] subNumsT=this.subNums;
			stream.writeLen(subNumsT.length);
			for(int subNumsVI=0,subNumsVLen=subNumsT.length;subNumsVI<subNumsVLen;++subNumsVI)
			{
				int[] subNumsV=subNumsT[subNumsVI];
				if(subNumsV!=null)
				{
					int[] subNumsVT=subNumsV;
					stream.writeLen(subNumsVT.length);
					for(int subNumsVVI=0,subNumsVVLen=subNumsVT.length;subNumsVVI<subNumsVVLen;++subNumsVVI)
					{
						int subNumsVV=subNumsVT[subNumsVVI];
						stream.writeInt(subNumsVV);
						
					}
				}
				else
				{
					nullObjError("subNumsV");
				}
				
			}
		}
		else
		{
			nullObjError("subNums");
		}
		
		if(this.influenceType!=null)
		{
			int[] influenceTypeT=this.influenceType;
			stream.writeLen(influenceTypeT.length);
			for(int influenceTypeVI=0,influenceTypeVLen=influenceTypeT.length;influenceTypeVI<influenceTypeVLen;++influenceTypeVI)
			{
				int influenceTypeV=influenceTypeT[influenceTypeVI];
				stream.writeInt(influenceTypeV);
				
			}
		}
		else
		{
			nullObjError("influenceType");
		}
		
	}
	
}
