package com.home.commonBase.config.game;
import com.home.commonBase.config.base.BaseConfig;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.DIntData;
import com.home.shine.support.collection.LongObjectMap;
import com.home.shine.support.collection.SMap;

/** 战斗单位等级表(generated by shine) */
public class FightUnitLevelConfig extends BaseConfig
{
	/** 存储集合 */
	private static LongObjectMap<FightUnitLevelConfig> _dic;
	
	/** id */
	public int id;
	
	/** 等级 */
	public int level;
	
	/** 属性组 */
	public DIntData[] attributes;
	
	/** 技能组 */
	public DIntData[] skills;
	
	/** buff组 */
	public DIntData[] buffs;
	
	/** 获取 */
	public static FightUnitLevelConfig get(int id,int level)
	{
		return _dic.get((long)id << 16 | (long)level);
	}
	
	/** 设置字典 */
	public static void setDic(LongObjectMap<FightUnitLevelConfig> dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static LongObjectMap<FightUnitLevelConfig> getDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		this.level=stream.readShort();
		
		int attributesLen=stream.readLen();
		if(this.attributes==null || this.attributes.length!=attributesLen)
		{
			this.attributes=new DIntData[attributesLen];
		}
		DIntData[] attributesT=this.attributes;
		for(int attributesI=0;attributesI<attributesLen;++attributesI)
		{
			DIntData attributesV;
			attributesV=new DIntData();
			attributesV.readBytesSimple(stream);
			
			attributesT[attributesI]=attributesV;
		}
		
		int skillsLen=stream.readLen();
		if(this.skills==null || this.skills.length!=skillsLen)
		{
			this.skills=new DIntData[skillsLen];
		}
		DIntData[] skillsT=this.skills;
		for(int skillsI=0;skillsI<skillsLen;++skillsI)
		{
			DIntData skillsV;
			skillsV=new DIntData();
			skillsV.readBytesSimple(stream);
			
			skillsT[skillsI]=skillsV;
		}
		
		int buffsLen=stream.readLen();
		if(this.buffs==null || this.buffs.length!=buffsLen)
		{
			this.buffs=new DIntData[buffsLen];
		}
		DIntData[] buffsT=this.buffs;
		for(int buffsI=0;buffsI<buffsLen;++buffsI)
		{
			DIntData buffsV;
			buffsV=new DIntData();
			buffsV.readBytesSimple(stream);
			
			buffsT[buffsI]=buffsV;
		}
		
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		FightUnitConfig fConfig;
		
		FightUnitLevelConfig[] values;
		FightUnitLevelConfig v;
		
		for(int i=(values=_dic.getValues()).length-1;i>=0;--i)
		{
			if((v=values[i])!=null)
			{
				if((fConfig=FightUnitConfig.get(v.id)).levelMax<v.level)
					fConfig.levelMax=v.level;
			}
		}
	}
	
	/** 获取 */
	public static FightUnitLevelConfig get(int id,short level)
	{
		return _dic.get((long)id << 16 | (long)level);
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
		stream.writeShort(this.level);
		
		if(this.attributes!=null)
		{
			DIntData[] attributesT=this.attributes;
			stream.writeLen(attributesT.length);
			for(int attributesVI=0,attributesVLen=attributesT.length;attributesVI<attributesVLen;++attributesVI)
			{
				DIntData attributesV=attributesT[attributesVI];
				if(attributesV!=null)
				{
					attributesV.writeBytesSimple(stream);
				}
				else
				{
					nullObjError("attributesV");
				}
				
			}
		}
		else
		{
			nullObjError("attributes");
		}
		
		if(this.skills!=null)
		{
			DIntData[] skillsT=this.skills;
			stream.writeLen(skillsT.length);
			for(int skillsVI=0,skillsVLen=skillsT.length;skillsVI<skillsVLen;++skillsVI)
			{
				DIntData skillsV=skillsT[skillsVI];
				if(skillsV!=null)
				{
					skillsV.writeBytesSimple(stream);
				}
				else
				{
					nullObjError("skillsV");
				}
				
			}
		}
		else
		{
			nullObjError("skills");
		}
		
		if(this.buffs!=null)
		{
			DIntData[] buffsT=this.buffs;
			stream.writeLen(buffsT.length);
			for(int buffsVI=0,buffsVLen=buffsT.length;buffsVI<buffsVLen;++buffsVI)
			{
				DIntData buffsV=buffsT[buffsVI];
				if(buffsV!=null)
				{
					buffsV.writeBytesSimple(stream);
				}
				else
				{
					nullObjError("buffsV");
				}
				
			}
		}
		else
		{
			nullObjError("buffs");
		}
		
	}
	
}
