package com.home.commonBase.config.game;
import com.home.commonBase.config.base.BaseConfig;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.DIntData;
import com.home.shine.support.collection.IntObjectMap;
import com.home.shine.support.collection.LongObjectMap;
import com.home.shine.support.collection.SMap;

/** 傀儡等级表(generated by shine) */
public class PuppetLevelConfig extends BaseConfig
{
	/** 存储集合 */
	private static LongObjectMap<PuppetLevelConfig> _dic;
	
	/** id */
	public int id;
	
	/** 等级 */
	public int level;
	
	/** 时间结束动作组 */
	public int[][] timeUpActions;
	
	/** 获取 */
	public static PuppetLevelConfig get(int id,int level)
	{
		return _dic.get((long)id << 16 | (long)level);
	}
	
	/** 设置字典 */
	public static void setDic(LongObjectMap<PuppetLevelConfig> dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static LongObjectMap<PuppetLevelConfig> getDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		this.level=stream.readShort();
		
		int timeUpActionsLen=stream.readLen();
		if(this.timeUpActions==null || this.timeUpActions.length!=timeUpActionsLen)
		{
			this.timeUpActions=new int[timeUpActionsLen][];
		}
		int[][] timeUpActionsT=this.timeUpActions;
		for(int timeUpActionsI=0;timeUpActionsI<timeUpActionsLen;++timeUpActionsI)
		{
			int[] timeUpActionsV;
			int timeUpActionsVLen=stream.readLen();
			timeUpActionsV=new int[timeUpActionsVLen];
			int[] timeUpActionsVT=timeUpActionsV;
			for(int timeUpActionsVI=0;timeUpActionsVI<timeUpActionsVLen;++timeUpActionsVI)
			{
				int timeUpActionsVV;
				timeUpActionsVV=stream.readInt();
				
				timeUpActionsVT[timeUpActionsVI]=timeUpActionsVV;
			}
			
			timeUpActionsT[timeUpActionsI]=timeUpActionsV;
		}
		
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		
	}
	
	/** 获取 */
	public static PuppetLevelConfig get(int id,short level)
	{
		return _dic.get((long)id << 16 | (long)level);
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
		stream.writeShort(this.level);
		
		if(this.timeUpActions!=null)
		{
			int[][] timeUpActionsT=this.timeUpActions;
			stream.writeLen(timeUpActionsT.length);
			for(int timeUpActionsVI=0,timeUpActionsVLen=timeUpActionsT.length;timeUpActionsVI<timeUpActionsVLen;++timeUpActionsVI)
			{
				int[] timeUpActionsV=timeUpActionsT[timeUpActionsVI];
				if(timeUpActionsV!=null)
				{
					int[] timeUpActionsVT=timeUpActionsV;
					stream.writeLen(timeUpActionsVT.length);
					for(int timeUpActionsVVI=0,timeUpActionsVVLen=timeUpActionsVT.length;timeUpActionsVVI<timeUpActionsVVLen;++timeUpActionsVVI)
					{
						int timeUpActionsVV=timeUpActionsVT[timeUpActionsVVI];
						stream.writeInt(timeUpActionsVV);
						
					}
				}
				else
				{
					nullObjError("timeUpActionsV");
				}
				
			}
		}
		else
		{
			nullObjError("timeUpActions");
		}
		
	}
	
}
