package com.home.commonBase.config.game;
import com.home.commonBase.config.base.BaseConfig;
import com.home.commonBase.config.game.LanguageConfig;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.support.collection.IntObjectMap;

/** 玩家群表(generated by shine) */
public class RoleGroupConfig extends BaseConfig
{
	/** 存储集合 */
	private static IntObjectMap<RoleGroupConfig> _dic;
	
	/** id */
	public int id;
	
	/** 加入者给予职位 */
	public int joinTitle;
	
	/** 默认公告 */
	public String defaultNotice="";
	
	/** 默认名字 */
	public String defaultName="";
	
	/** 是否禁止重名 */
	public boolean needUniqueName;
	
	/** 公告字符数限制 */
	public int noticeCharLimit;
	
	/** 名字字符数限制 */
	public int nameCharLimit;
	
	/** 创建条件 */
	public int[][] createConditions;
	
	/** 创建开销 */
	public int createCostID;
	
	/** 加入/邀请/申请条件 */
	public int[][] joinConditions;
	
	/** 是否只是本服玩家群(不可与其他服角色同群) */
	public boolean isOnlyLocalGame;
	
	/** 是否存库 */
	public boolean needSave;
	
	/** 申请保留上限 */
	public int applyKeepMax;
	
	/** 是否允许申请入群 */
	public boolean canApply;
	
	/** 初始化客户端时是否包含成员组 */
	public boolean initClientContainsMembers;
	
	/** 邀请保留上限 */
	public int inviteKeepMax;
	
	/** 是否可以邀请直接创建 */
	public boolean canInviteCreate;
	
	/** 拒绝申请间隔时间(s) */
	public int refuseApplyTime;
	
	/** 申请有效时间(s) */
	public int applyEnableTime;
	
	/** 邀请有效时间(s) */
	public int inviteEnableTime;
	
	/** 重复申请间隔时间(s) */
	public int applyRepeatTime;
	
	/** 只剩一人时是否解散玩家群(剩两人时，一旦离开解散队伍) */
	public boolean removeWithOnlyOne;
	
	/** 是否需要简版信息列表 */
	public boolean needSimpleList;
	
	/** 每个玩家可入群数 */
	public int eachPlayerGroupNum;
	
	/** 默认名字原值 */
	private String _defaultName;
	
	/** 日志保留数目 */
	public int infoLogKeepNum;
	
	/** 日志保留时间(day) */
	public int infoLogKeepTime;
	
	/** 专属场景id */
	public int ownSceneID;
	
	/** 是否实时更新角色社交数据 */
	public boolean isUpdateRoleSocialAbs;
	
	/** 是否需要中心服保存玩家群数据 */
	public boolean needCenterSaveRoleGroup;
	
	/** 是否保留离线邀请 */
	public boolean needKeepOfflineInvite;
	
	/** 默认公告原值 */
	private String _defaultNotice;
	
	/** 邀请时是否可直接入群(无需同意) */
	public boolean defaultCanInviteInAbs;
	
	/** 申请时是否可直接入群(无需同意) */
	public boolean defaultCanApplyInAbs;
	
	/** 等级上限 */
	public int levelMax;
	
	/** 获取 */
	public static RoleGroupConfig get(int id)
	{
		return _dic.get(id);
	}
	
	/** 设置字典 */
	public static void setDic(IntObjectMap<RoleGroupConfig> dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static IntObjectMap<RoleGroupConfig> getDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		this.eachPlayerGroupNum=stream.readInt();
		
		this.joinTitle=stream.readInt();
		
		this.defaultName=stream.readUTF();
		
		this.defaultNotice=stream.readUTF();
		
		this.needUniqueName=stream.readBoolean();
		
		this.nameCharLimit=stream.readInt();
		
		this.noticeCharLimit=stream.readInt();
		
		this.createCostID=stream.readInt();
		
		int createConditionsLen=stream.readLen();
		if(this.createConditions==null || this.createConditions.length!=createConditionsLen)
		{
			this.createConditions=new int[createConditionsLen][];
		}
		int[][] createConditionsT=this.createConditions;
		for(int createConditionsI=0;createConditionsI<createConditionsLen;++createConditionsI)
		{
			int[] createConditionsV;
			int createConditionsVLen=stream.readLen();
			createConditionsV=new int[createConditionsVLen];
			int[] createConditionsVT=createConditionsV;
			for(int createConditionsVI=0;createConditionsVI<createConditionsVLen;++createConditionsVI)
			{
				int createConditionsVV;
				createConditionsVV=stream.readInt();
				
				createConditionsVT[createConditionsVI]=createConditionsVV;
			}
			
			createConditionsT[createConditionsI]=createConditionsV;
		}
		
		int joinConditionsLen=stream.readLen();
		if(this.joinConditions==null || this.joinConditions.length!=joinConditionsLen)
		{
			this.joinConditions=new int[joinConditionsLen][];
		}
		int[][] joinConditionsT=this.joinConditions;
		for(int joinConditionsI=0;joinConditionsI<joinConditionsLen;++joinConditionsI)
		{
			int[] joinConditionsV;
			int joinConditionsVLen=stream.readLen();
			joinConditionsV=new int[joinConditionsVLen];
			int[] joinConditionsVT=joinConditionsV;
			for(int joinConditionsVI=0;joinConditionsVI<joinConditionsVLen;++joinConditionsVI)
			{
				int joinConditionsVV;
				joinConditionsVV=stream.readInt();
				
				joinConditionsVT[joinConditionsVI]=joinConditionsVV;
			}
			
			joinConditionsT[joinConditionsI]=joinConditionsV;
		}
		
		this.needSave=stream.readBoolean();
		
		this.isOnlyLocalGame=stream.readBoolean();
		
		this.initClientContainsMembers=stream.readBoolean();
		
		this.inviteKeepMax=stream.readInt();
		
		this.applyKeepMax=stream.readInt();
		
		this.canApply=stream.readBoolean();
		
		this.canInviteCreate=stream.readBoolean();
		
		this.defaultCanInviteInAbs=stream.readBoolean();
		
		this.defaultCanApplyInAbs=stream.readBoolean();
		
		this.inviteEnableTime=stream.readInt();
		
		this.applyEnableTime=stream.readInt();
		
		this.applyRepeatTime=stream.readInt();
		
		this.refuseApplyTime=stream.readInt();
		
		this.removeWithOnlyOne=stream.readBoolean();
		
		this.needSimpleList=stream.readBoolean();
		
		this.infoLogKeepTime=stream.readInt();
		
		this.infoLogKeepNum=stream.readInt();
		
		this.ownSceneID=stream.readInt();
		
		this.isUpdateRoleSocialAbs=stream.readBoolean();
		
		this.needCenterSaveRoleGroup=stream.readBoolean();
		
		this.needKeepOfflineInvite=stream.readBoolean();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
		stream.writeInt(this.eachPlayerGroupNum);
		
		stream.writeInt(this.joinTitle);
		
		stream.writeUTF(this.defaultName);
		
		stream.writeUTF(this.defaultNotice);
		
		stream.writeBoolean(this.needUniqueName);
		
		stream.writeInt(this.nameCharLimit);
		
		stream.writeInt(this.noticeCharLimit);
		
		stream.writeInt(this.createCostID);
		
		if(this.createConditions!=null)
		{
			int[][] createConditionsT=this.createConditions;
			stream.writeLen(createConditionsT.length);
			for(int createConditionsVI=0,createConditionsVLen=createConditionsT.length;createConditionsVI<createConditionsVLen;++createConditionsVI)
			{
				int[] createConditionsV=createConditionsT[createConditionsVI];
				if(createConditionsV!=null)
				{
					int[] createConditionsVT=createConditionsV;
					stream.writeLen(createConditionsVT.length);
					for(int createConditionsVVI=0,createConditionsVVLen=createConditionsVT.length;createConditionsVVI<createConditionsVVLen;++createConditionsVVI)
					{
						int createConditionsVV=createConditionsVT[createConditionsVVI];
						stream.writeInt(createConditionsVV);
						
					}
				}
				else
				{
					nullObjError("createConditionsV");
				}
				
			}
		}
		else
		{
			nullObjError("createConditions");
		}
		
		if(this.joinConditions!=null)
		{
			int[][] joinConditionsT=this.joinConditions;
			stream.writeLen(joinConditionsT.length);
			for(int joinConditionsVI=0,joinConditionsVLen=joinConditionsT.length;joinConditionsVI<joinConditionsVLen;++joinConditionsVI)
			{
				int[] joinConditionsV=joinConditionsT[joinConditionsVI];
				if(joinConditionsV!=null)
				{
					int[] joinConditionsVT=joinConditionsV;
					stream.writeLen(joinConditionsVT.length);
					for(int joinConditionsVVI=0,joinConditionsVVLen=joinConditionsVT.length;joinConditionsVVI<joinConditionsVVLen;++joinConditionsVVI)
					{
						int joinConditionsVV=joinConditionsVT[joinConditionsVVI];
						stream.writeInt(joinConditionsVV);
						
					}
				}
				else
				{
					nullObjError("joinConditionsV");
				}
				
			}
		}
		else
		{
			nullObjError("joinConditions");
		}
		
		stream.writeBoolean(this.needSave);
		
		stream.writeBoolean(this.isOnlyLocalGame);
		
		stream.writeBoolean(this.initClientContainsMembers);
		
		stream.writeInt(this.inviteKeepMax);
		
		stream.writeInt(this.applyKeepMax);
		
		stream.writeBoolean(this.canApply);
		
		stream.writeBoolean(this.canInviteCreate);
		
		stream.writeBoolean(this.defaultCanInviteInAbs);
		
		stream.writeBoolean(this.defaultCanApplyInAbs);
		
		stream.writeInt(this.inviteEnableTime);
		
		stream.writeInt(this.applyEnableTime);
		
		stream.writeInt(this.applyRepeatTime);
		
		stream.writeInt(this.refuseApplyTime);
		
		stream.writeBoolean(this.removeWithOnlyOne);
		
		stream.writeBoolean(this.needSimpleList);
		
		stream.writeInt(this.infoLogKeepTime);
		
		stream.writeInt(this.infoLogKeepNum);
		
		stream.writeInt(this.ownSceneID);
		
		stream.writeBoolean(this.isUpdateRoleSocialAbs);
		
		stream.writeBoolean(this.needCenterSaveRoleGroup);
		
		stream.writeBoolean(this.needKeepOfflineInvite);
		
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		
	}
	
	/** 是否只可加入1个群 */
	public boolean isSingleJoin()
	{
		return eachPlayerGroupNum==1;
	}
	
	/** 生成刷新配置 */
	@Override
	protected void generateRefresh()
	{
		if(_defaultName==null)
			_defaultName=defaultName;
		defaultName=LanguageConfig.getText(_defaultName);
		
		if(_defaultNotice==null)
			_defaultNotice=defaultNotice;
		defaultNotice=LanguageConfig.getText(_defaultNotice);
		
	}
	
}
