package com.home.commonBase.config.game;
import com.home.commonBase.config.base.BaseConfig;
import com.home.commonBase.config.game.LanguageConfig;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;

/** 队伍目标表(generated by shine) */
public class TeamTargetConfig extends BaseConfig
{
	/** 存储集合 */
	private static TeamTargetConfig[] _dic;
	
	/** 需要等级 */
	public int needLevel;
	
	/** id */
	public int id;
	
	/** 描述原值 */
	private String _name;
	
	/** 获取 */
	public static TeamTargetConfig get(int id)
	{
		return id>=0 && id<_dic.length ? _dic[id] : null;
	}
	
	/** 设置字典 */
	public static void setDic(TeamTargetConfig[] dic)
	{
		_dic=dic;
	}
	
	/** 获取全部 */
	public static TeamTargetConfig[] getDic()
	{
		return _dic;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.id=stream.readInt();
		
		this.needLevel=stream.readInt();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.id);
		
		stream.writeInt(this.needLevel);
		
	}
	
	/** 读完所有表后处理 */
	public static void afterReadConfigAll()
	{
		
	}
	
}
