package com.home.commonClient.net.request.scene.unit.building;
import com.home.commonClient.constlist.generate.GameRequestType;
import com.home.commonClient.net.request.scene.base.CUnitRRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** 建筑取消升级消息(generated by shine) */
public class CBuildingCancelLevelUpRequest extends CUnitRRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.CBuildingCancelLevelUp;
	
	public CBuildingCancelLevelUpRequest()
	{
		_dataID=GameRequestType.CBuildingCancelLevelUp;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CBuildingCancelLevelUpRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 创建实例 */
	public static CBuildingCancelLevelUpRequest create(int instanceID)
	{
		CBuildingCancelLevelUpRequest re=(CBuildingCancelLevelUpRequest)BytesControl.createRequest(dataID);
		re.instanceID=instanceID;
		return re;
	}
	
}
