package com.home.commonGame.net.request.func.roleGroup;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.request.func.base.FuncSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 推送玩家离开玩家群消息(generated by shine) */
public class FuncSendPlayerLeaveRoleGroupRequest extends FuncSRequest
{
	/** 方式 */
	public int type;
	
	public long groupID;
	
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncSendPlayerLeaveRoleGroup;
	
	public FuncSendPlayerLeaveRoleGroupRequest()
	{
		_dataID=GameRequestType.FuncSendPlayerLeaveRoleGroup;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendPlayerLeaveRoleGroupRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeLong(this.groupID);
		
		stream.writeInt(this.type);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.groupID);
		
		stream.writeInt(this.type);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("groupID");
		writer.sb.append(':');
		writer.sb.append(this.groupID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("type");
		writer.sb.append(':');
		writer.sb.append(this.type);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.groupID=0L;
		this.type=0;
	}
	
	/** 创建实例 */
	public static FuncSendPlayerLeaveRoleGroupRequest create(int funcID,long groupID,int type)
	{
		FuncSendPlayerLeaveRoleGroupRequest re=(FuncSendPlayerLeaveRoleGroupRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.groupID=groupID;
		re.type=type;
		return re;
	}
	
}
