using ShineEngine;

/// <summary>
/// 主单位消息基类(generated by shine)
/// </summary>
public class MUnitRRequest:GameRequest
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=GameRequestType.MUnitR;
	
	/// <summary>
	/// 单位序号
	/// </summary>
	public int mIndex;
	
	public MUnitRRequest()
	{
		_dataID=GameRequestType.MUnitR;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "MUnitRRequest";
	}
	
	/// <summary>
	/// 写入字节流(完整版)
	/// </summary>
	protected override void toWriteBytesFull(BytesWriteStream stream)
	{
		base.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.mIndex);
		
		stream.endWriteObj();
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		stream.writeInt(this.mIndex);
		
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("mIndex");
		writer.sb.Append(':');
		writer.sb.Append(this.mIndex);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		this.mIndex=0;
	}
	
	protected override void copyData()
	{
		base.copyData();
	}
	
	/// <summary>
	/// 创建实例
	/// </summary>
	public static MUnitRRequest create(int mIndex)
	{
		MUnitRRequest re=(MUnitRRequest)BytesControl.createRequest(dataID);
		re.mIndex=mIndex;
		return re;
	}
	
}
