package com.home.commonGame.net.request.login;
import com.home.commonBase.data.login.ClientVersionData;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.IntObjectMap;
import com.home.shine.support.pool.DataPool;

/** 客户端版本热更新消息(generated by shine) */
public class ClientHotfixRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.ClientHotfix;
	
	/** 客户端版本 */
	public ClientVersionData clientVersion;
	
	public ClientHotfixRequest()
	{
		_dataID=GameRequestType.ClientHotfix;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		ClientVersionData clientVersionTemp=clientVersion;
		if(clientVersionTemp!=null)
		{
			this.clientVersion=new ClientVersionData();
			this.clientVersion.copy(clientVersionTemp);
		}
		else
		{
			this.clientVersion=null;
			nullObjError("clientVersion");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ClientHotfixRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("clientVersion");
		writer.sb.append(':');
		if(this.clientVersion!=null)
		{
			this.clientVersion.writeDataString(writer);
		}
		else
		{
			writer.sb.append("ClientVersionData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		if(this.clientVersion!=null)
		{
			this.clientVersion.writeBytesFull(stream);
		}
		else
		{
			nullObjError("clientVersion");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.clientVersion!=null)
		{
			this.clientVersion.writeBytesSimple(stream);
		}
		else
		{
			nullObjError("clientVersion");
		}
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.clientVersion.release(pool);
		this.clientVersion=null;
	}
	
	/** 创建实例 */
	public static ClientHotfixRequest create(ClientVersionData clientVersion)
	{
		ClientHotfixRequest re=(ClientHotfixRequest)BytesControl.createRequest(dataID);
		re.clientVersion=clientVersion;
		return re;
	}
	
}
