namespace Shine
{
	/** 建筑取消升级消息(generated by shine) */
	export class CBuildingCancelLevelUpRequest extends CUnitRRequest
	{
		/** 数据类型ID */
		public static dataID:number=GameRequestType.CBuildingCancelLevelUp;
		
		constructor()
		{
			super();
			this._dataID=GameRequestType.CBuildingCancelLevelUp;
		}
		
		protected copyData():void
		{
			super.copyData();
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "CBuildingCancelLevelUpRequest";
		}
		
		/** 创建实例 */
		public static createCBuildingCancelLevelUp(instanceID:number):CBuildingCancelLevelUpRequest
		{
			var re:CBuildingCancelLevelUpRequest=new CBuildingCancelLevelUpRequest();
			re.instanceID=instanceID;
			return re;
		}
		
	}
}
