package com.home.commonGame.net.serverRequest.game.func.roleGroup;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.social.RoleSocialData;
import com.home.commonGame.net.serverRequest.game.func.base.FuncRoleGroupToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 申请加入玩家群(generated by shine) */
public class FuncApplyRoleGroupToGameServerRequest extends FuncRoleGroupToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncApplyRoleGroupToGame;
	
	public RoleSocialData data;
	
	public FuncApplyRoleGroupToGameServerRequest()
	{
		_dataID=ServerMessageType.FuncApplyRoleGroupToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		RoleSocialData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(RoleSocialData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncApplyRoleGroupToGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RoleSocialData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static FuncApplyRoleGroupToGameServerRequest create(int funcID,long groupID,RoleSocialData data)
	{
		FuncApplyRoleGroupToGameServerRequest re=(FuncApplyRoleGroupToGameServerRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.groupID=groupID;
		re.data=data;
		return re;
	}
	
}
