package com.home.commonGame.net.serverRequest.game.func.roleGroup;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.social.roleGroup.RoleGroupSimpleData;
import com.home.commonGame.net.serverRequest.game.func.base.FuncToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 添加玩家群简版信息到其他逻辑服(generated by shine) */
public class FuncAddRoleGroupSimpleToGameServerRequest extends FuncToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncAddRoleGroupSimpleToGame;
	
	public RoleGroupSimpleData data;
	
	public FuncAddRoleGroupSimpleToGameServerRequest()
	{
		_dataID=ServerMessageType.FuncAddRoleGroupSimpleToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		RoleGroupSimpleData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(RoleGroupSimpleData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncAddRoleGroupSimpleToGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RoleGroupSimpleData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static FuncAddRoleGroupSimpleToGameServerRequest create(int funcID,RoleGroupSimpleData data)
	{
		FuncAddRoleGroupSimpleToGameServerRequest re=(FuncAddRoleGroupSimpleToGameServerRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.data=data;
		return re;
	}
	
}
