package com.home.commonGame.net.serverRequest.game.func.roleGroup;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.net.serverRequest.game.func.base.FuncPlayerRoleGroupGameToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 更新职位到角色(generated by shine) */
public class FuncRefreshTitleRoleGroupToPlayerServerRequest extends FuncPlayerRoleGroupGameToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncRefreshTitleRoleGroupToPlayer;
	
	/** 成员id */
	public long memberID;
	
	/** 职位 */
	public int title;
	
	public FuncRefreshTitleRoleGroupToPlayerServerRequest()
	{
		_dataID=ServerMessageType.FuncRefreshTitleRoleGroupToPlayer;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncRefreshTitleRoleGroupToPlayerServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.memberID);
		
		stream.writeInt(this.title);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("memberID");
		writer.sb.append(':');
		writer.sb.append(this.memberID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("title");
		writer.sb.append(':');
		writer.sb.append(this.title);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.memberID=0L;
		this.title=0;
	}
	
	/** 创建实例 */
	public static FuncRefreshTitleRoleGroupToPlayerServerRequest create(int funcID,long groupID,long memberID,int title)
	{
		FuncRefreshTitleRoleGroupToPlayerServerRequest re=(FuncRefreshTitleRoleGroupToPlayerServerRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.groupID=groupID;
		re.memberID=memberID;
		re.title=title;
		return re;
	}
	
}
