package com.home.commonCenter.net.serverResponse.game.func.match;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.scene.match.PlayerMatchData;
import com.home.commonCenter.global.CenterC;
import com.home.commonCenter.net.serverResponse.game.base.PlayerToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.base.FuncPlayerToCenterServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 申请匹配到中心服(generated by shine) */
public class FuncApplyMatchToCenterServerResponse extends FuncPlayerToCenterServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncApplyMatchToCenter;
	
	/** 匹配数据 */
	public PlayerMatchData matchData;
	
	public FuncApplyMatchToCenterServerResponse()
	{
		_dataID=ServerMessageType.FuncApplyMatchToCenter;
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.matchData=(PlayerMatchData)stream.readDataSimpleNotNull();
		
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		//加入匹配
		CenterC.global.func.getMatchTool(funcID).add(matchData);
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncApplyMatchToCenterServerResponse";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("matchData");
		writer.sb.append(':');
		if(this.matchData!=null)
		{
			this.matchData.writeDataString(writer);
		}
		else
		{
			writer.sb.append("PlayerMatchData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.matchData=null;
	}
	
}
