package com.home.commonBase.data.scene.base;
import com.home.commonBase.config.game.CDConfig;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 冷却数据(generated by shine) */
public class CDData extends BaseData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.CD;
	
	/** id */
	public int id;
	
	/** 时间上限 */
	public int timeMax;
	
	/** 经过时间 */
	public int timePass;
	
	/** 配置 */
	public CDConfig config;
	
	public CDData()
	{
		_dataID=BaseDataType.CD;
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.id=stream.readInt();
		
		this.timePass=stream.readInt();
		
		this.timeMax=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeInt(this.id);
		
		stream.writeInt(this.timePass);
		
		stream.writeInt(this.timeMax);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.id=stream.readInt();
		
		this.timePass=stream.readInt();
		
		this.timeMax=stream.readInt();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeInt(this.id);
		
		stream.writeInt(this.timePass);
		
		stream.writeInt(this.timeMax);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof CDData))
			return;
		
		CDData mData=(CDData)data;
		
		this.id=mData.id;
		this.timePass=mData.timePass;
		this.timeMax=mData.timeMax;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof CDData))
			return;
		
		CDData mData=(CDData)data;
		
		this.id=mData.id;
		
		this.timePass=mData.timePass;
		
		this.timeMax=mData.timeMax;
		
	}
	
	/** 获取剩余时间 */
	public int getLastTime()
	{
		int re=timeMax - timePass;
		return re<0 ? 0 : re;
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		CDData mData=(CDData)data;
		if(this.id!=mData.id)
			return false;
		
		if(this.timePass!=mData.timePass)
			return false;
		
		if(this.timeMax!=mData.timeMax)
			return false;
		
		return true;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CDData";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("id");
		writer.sb.append(':');
		writer.sb.append(this.id);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("timePass");
		writer.sb.append(':');
		writer.sb.append(this.timePass);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("timeMax");
		writer.sb.append(':');
		writer.sb.append(this.timeMax);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		
	}
	
	@Override
	public void clear()
	{
		config=null;
	}
	
	public void reloadConfig()
	{
		config=CDConfig.get(id);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.id=0;
		this.timePass=0;
		this.timeMax=0;
	}
	
}
