namespace Shine
{
	/** buff数据(generated by shine) */
	export class BuffData extends BaseData
	{
		/** 数据类型ID */
		public static dataID:number=BaseDataType.Buff;
		
		/** 实例ID */
		public instanceID:number;
		
		/** id */
		public id:number;
		
		/** 等级 */
		public level:number;
		
		/** 剩余时间 */
		public lastTime:number;
		
		/** 剩余数目(叠层数) */
		public lastNum:number;
		
		/** 添加者(攻击者) */
		public adderInstanceID:number;
		
		constructor()
		{
			super();
			this._dataID=BaseDataType.Buff;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "BuffData";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			this.instanceID=stream.readInt();
			
			this.id=stream.readInt();
			
			this.level=stream.readInt();
			
			this.lastTime=stream.readInt();
			
			this.lastNum=stream.readInt();
			
			this.adderInstanceID=stream.readInt();
			
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			stream.writeInt(this.instanceID);
			
			stream.writeInt(this.id);
			
			stream.writeInt(this.level);
			
			stream.writeInt(this.lastTime);
			
			stream.writeInt(this.lastNum);
			
			stream.writeInt(this.adderInstanceID);
			
		}
		
		/** 复制(潜拷贝) */
		protected toShadowCopy(data:BaseData):void
		{
			if(!(data instanceof BuffData))
				return;
			
			var mData:BuffData=data as BuffData;
			
			this.instanceID=mData.instanceID;
			this.id=mData.id;
			this.level=mData.level;
			this.lastTime=mData.lastTime;
			this.lastNum=mData.lastNum;
			this.adderInstanceID=mData.adderInstanceID;
		}
		
		/** 复制(深拷贝) */
		protected toCopy(data:BaseData):void
		{
			if(!(data instanceof BuffData))
				return;
			
			var mData:BuffData=data as BuffData;
			
			this.instanceID=mData.instanceID;
			
			this.id=mData.id;
			
			this.level=mData.level;
			
			this.lastTime=mData.lastTime;
			
			this.lastNum=mData.lastNum;
			
			this.adderInstanceID=mData.adderInstanceID;
			
		}
		
		/** 初始化初值 */
		public initDefault():void
		{
			
		}
		
	}
}
