namespace Shine
{
	/** 位置朝向数据(generated by shine) */
	export class PosDirData extends BaseData
	{
		/** 数据类型ID */
		public static dataID:number=BaseDataType.PosDir;
		
		/** 位置 */
		public pos:PosData;
		
		/** 朝向 */
		public dir:DirData;
		
		constructor()
		{
			super();
			this._dataID=BaseDataType.PosDir;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "PosDirData";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			this.pos=new PosData();
			this.pos.readBytesSimple(stream);
			
			this.dir=new DirData();
			this.dir.readBytesSimple(stream);
			
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			this.pos.writeBytesSimple(stream);
			
			this.dir.writeBytesSimple(stream);
			
		}
		
		/** 复制(潜拷贝) */
		protected toShadowCopy(data:BaseData):void
		{
			if(!(data instanceof PosDirData))
				return;
			
			var mData:PosDirData=data as PosDirData;
			
			this.pos=mData.pos;
			this.dir=mData.dir;
		}
		
		/** 复制(深拷贝) */
		protected toCopy(data:BaseData):void
		{
			if(!(data instanceof PosDirData))
				return;
			
			var mData:PosDirData=data as PosDirData;
			
			this.pos=new PosData();
			this.pos.copy(mData.pos);
			
			this.dir=new DirData();
			this.dir.copy(mData.dir);
			
		}
		
		/** 初始化初值 */
		public initDefault():void
		{
			this.pos=new PosData();
			this.pos.initDefault();
			this.dir=new DirData();
			this.dir.initDefault();
		}
		
	}
}
