namespace Shine
{
	/** 客户端控制单位子弹命中(generated by shine) */
	export class CUnitBulletHitRequest extends CUnitRRequest
	{
		/** 数据类型ID */
		public static dataID:number=GameRequestType.CUnitBulletHit;
		
		/** 子弹ID */
		public bulletID:number;
		
		/** 子弹等级 */
		public bulletLevel:number;
		
		/** 目标 */
		public target:SkillTargetData;
		
		constructor()
		{
			super();
			this._dataID=GameRequestType.CUnitBulletHit;
		}
		
		protected copyData():void
		{
			super.copyData();
			var targetTemp:SkillTargetData=this.target;
			this.target=targetTemp.clone() as SkillTargetData;
			
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "CUnitBulletHitRequest";
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			super.toWriteBytesSimple(stream);
			
			stream.writeInt(this.bulletID);
			
			stream.writeInt(this.bulletLevel);
			
			stream.writeDataSimpleNotNull(this.target);
			
		}
		
		/** 创建实例 */
		public static createCUnitBulletHit(instanceID:number,bulletID:number,bulletLevel:number,target:SkillTargetData):CUnitBulletHitRequest
		{
			var re:CUnitBulletHitRequest=new CUnitBulletHitRequest();
			re.instanceID=instanceID;
			re.bulletID=bulletID;
			re.bulletLevel=bulletLevel;
			re.target=target;
			return re;
		}
		
	}
}
