package com.home.commonLogin.net.serverRequest.game.login;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.login.ClientLoginExData;
import com.home.commonLogin.net.serverRequest.game.base.LoginToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** (generated by shine) */
public class UserLoginToGameServerRequest extends LoginToGameServerRequest
{
	/** 登陆数据 */
	public ClientLoginExData data;
	
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.UserLoginToGame;
	
	public UserLoginToGameServerRequest()
	{
		_dataID=ServerMessageType.UserLoginToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		ClientLoginExData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(ClientLoginExData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "UserLoginToGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("ClientLoginExData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static UserLoginToGameServerRequest create(ClientLoginExData data)
	{
		UserLoginToGameServerRequest re=(UserLoginToGameServerRequest)BytesControl.createRequest(dataID);
		re.data=data;
		return re;
	}
	
}
