using ShineEngine;

/// <summary>
/// (generated by shine)
/// </summary>
public class CodeCheckRecord
{
	/// <summary>
	/// 配置文件代码版本校验值
	/// </summary>
	public const string configMD5="e3b6fbcf13fe4df174f8f58da5602db1";
	
	/// <summary>
	/// 通信存库数据结构校验
	/// </summary>
	public const string msgDataMD5="7362f566b92909f31414ac84d0a01596";
	
	/// <summary>
	/// 客户端存库数据结构校验
	/// </summary>
	public const string dbDataMD5="139b3887fad318bc680691e41ffcd84e";
	
	/// <summary>
	/// 客户端数据结构版本号(只记录不兼容修改)
	/// </summary>
	public const int dbDataVersion=98495579;
	
	/// <summary>
	/// 通信数据结构版本号(只记录不兼容修改)
	/// </summary>
	public const int msgDataVersion=24158829;
	
	/// <summary>
	/// 配置文件代码数据结构版本号
	/// </summary>
	public const int configVersion=24309349;
	
}
