package com.home.commonGame.net.request.func.auction;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.request.func.base.FuncSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 拍卖行更新自己出售物品数目消息(generated by shine) */
public class FuncAuctionRefreshSaleItemRequest extends FuncSRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncAuctionRefreshSaleItem;
	
	/** 实例ID */
	public long instanceID;
	
	/** 更新后的数目 */
	public int num;
	
	public FuncAuctionRefreshSaleItemRequest()
	{
		_dataID=GameRequestType.FuncAuctionRefreshSaleItem;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncAuctionRefreshSaleItemRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeLong(this.instanceID);
		
		stream.writeInt(this.num);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.instanceID);
		
		stream.writeInt(this.num);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("instanceID");
		writer.sb.append(':');
		writer.sb.append(this.instanceID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("num");
		writer.sb.append(':');
		writer.sb.append(this.num);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.instanceID=0L;
		this.num=0;
	}
	
	/** 创建实例 */
	public static FuncAuctionRefreshSaleItemRequest create(int funcID,long instanceID,int num)
	{
		FuncAuctionRefreshSaleItemRequest re=(FuncAuctionRefreshSaleItemRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.instanceID=instanceID;
		re.num=num;
		return re;
	}
	
}
