package com.home.commonGame.net.request.func.match;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.commonGame.net.request.func.base.FuncSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** 重新加入匹配队列消息(generated by shine) */
public class FuncReAddMatchRequest extends FuncSRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncReAddMatch;
	
	public FuncReAddMatchRequest()
	{
		_dataID=GameRequestType.FuncReAddMatch;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncReAddMatchRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.endWriteObj();
	}
	
	/** 创建实例 */
	public static FuncReAddMatchRequest create(int funcID)
	{
		FuncReAddMatchRequest re=(FuncReAddMatchRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		return re;
	}
	
}
