namespace Shine
{
	/** 删除邮件消息(generated by shine) */
	export class DeleteMailRequest extends GameRequest
	{
		/** 数据类型ID */
		public static dataID:number=GameRequestType.DeleteMail;
		
		/** 邮件序号 */
		public index:number;
		
		/** 邮件实例ID */
		public instanceID:number;
		
		constructor()
		{
			super();
			this._dataID=GameRequestType.DeleteMail;
		}
		
		protected copyData():void
		{
			super.copyData();
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "DeleteMailRequest";
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			super.toWriteBytesSimple(stream);
			
			stream.writeInt(this.index);
			
			stream.writeInt(this.instanceID);
			
		}
		
		/** 创建实例 */
		public static createDeleteMail(index:number,instanceID:number):DeleteMailRequest
		{
			var re:DeleteMailRequest=new DeleteMailRequest();
			re.index=index;
			re.instanceID=instanceID;
			return re;
		}
		
	}
}
