package com.home.commonGame.net.serverRequest.center.system;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.net.serverRequest.center.base.GameToCenterServerRequest;
import com.home.commonGame.net.serverRequest.center.base.PlayerToCenterServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 客户端GM指令到中心服(generated by shine) */
public class ClientGMToCenterServerRequest extends PlayerToCenterServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.ClientGMToCenter;
	
	/** 指令 */
	public String cmd="";
	
	public ClientGMToCenterServerRequest()
	{
		_dataID=ServerMessageType.ClientGMToCenter;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeUTF(this.cmd);
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ClientGMToCenterServerRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("cmd");
		writer.sb.append(':');
		writer.sb.append(this.cmd);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.cmd="";
	}
	
	/** 创建实例 */
	public static ClientGMToCenterServerRequest create(long playerID,String cmd)
	{
		ClientGMToCenterServerRequest re=(ClientGMToCenterServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.cmd=cmd;
		return re;
	}
	
}
