package com.home.commonGame.net.response.mail;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.net.base.GameResponse;
import com.home.shine.bytes.BytesReadStream;

/** 获取全部邮件消息(generated by shine) */
public class GetAllMailResponse extends GameResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.GetAllMail;
	
	public GetAllMailResponse()
	{
		_dataID=GameResponseType.GetAllMail;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		me.mail.getAllMail();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "GetAllMailResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
}
