package com.home.commonCenter.tool.generate;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonCenter.net.serverResponse.game.activity.UseActivationCodeToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.base.FuncToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.base.PlayerToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.auction.FuncSendAuctionBuyItemToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.auction.FuncSendAuctionCancelSellItemToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.auction.FuncSendAuctionSellItemToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.base.FuncPlayerToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.match.FuncAcceptMatchToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.match.FuncApplyCancelMatchToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.match.FuncApplyMatchToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.pageShow.FuncSendGetPageShowToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.rank.FuncCommitRankValueToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.rank.FuncRemoveRankToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.rank.subsection.FuncCommitSubsectionRankValueToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.rank.subsection.FuncRemoveSubsectionRankToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.func.social.FuncGetRandomPlayerListFromRoleSocialPoolToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.scene.ReCreateSignedSceneToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.social.CommitCustomRoleSocialToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.social.CommitRoleGroupToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.social.CommitRoleSocialToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.social.FuncRoleGroupChangeSimpleToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.social.RefreshRoleSocialToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.BeGameToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.CenterTransGameToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.ClientGMToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.GameLoginToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.ReceiptWorkToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.SendCenterWorkCompleteToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.SendCenterWorkToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.SendMQueryPlayerWorkResultToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.SendPlayerOnlineNumToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.game.system.SendPlayerWorkToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.manager.CenterExitServerResponse;
import com.home.commonCenter.net.serverResponse.manager.MAddPlayerWorkToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.manager.MQueryPlayerWorkToCenterServerResponse;
import com.home.commonCenter.net.serverResponse.manager.ManagerToCenterCommandServerResponse;
import com.home.commonCenter.net.serverResponse.manager.ReBeCenterToManagerServerResponse;
import com.home.commonCenter.net.serverResponse.manager.ReloadServerConfigToCenterServerResponse;
import com.home.shine.data.BaseData;
import com.home.shine.tool.CreateDataFunc;
import com.home.shine.tool.DataMaker;

/** (generated by shine) */
public class CenterServerResponseMaker extends DataMaker
{
	public CenterServerResponseMaker()
	{
		offSet=ServerMessageType.off;
		list=new CreateDataFunc[ServerMessageType.count-offSet];
		list[ServerMessageType.CenterExit-offSet]=this::createCenterExitServerResponse;
		list[ServerMessageType.MAddPlayerWorkToCenter-offSet]=this::createMAddPlayerWorkToCenterServerResponse;
		list[ServerMessageType.MQueryPlayerWorkToCenter-offSet]=this::createMQueryPlayerWorkToCenterServerResponse;
		list[ServerMessageType.ManagerToCenterCommand-offSet]=this::createManagerToCenterCommandServerResponse;
		list[ServerMessageType.ReBeCenterToManager-offSet]=this::createReBeCenterToManagerServerResponse;
		list[ServerMessageType.ReloadServerConfigToCenter-offSet]=this::createReloadServerConfigToCenterServerResponse;
		list[ServerMessageType.BeGameToCenter-offSet]=this::createBeGameToCenterServerResponse;
		list[ServerMessageType.CenterTransGameToCenter-offSet]=this::createCenterTransGameToCenterServerResponse;
		list[ServerMessageType.ClientGMToCenter-offSet]=this::createClientGMToCenterServerResponse;
		list[ServerMessageType.CommitCustomRoleSocialToCenter-offSet]=this::createCommitCustomRoleSocialToCenterServerResponse;
		list[ServerMessageType.CommitRoleGroupToCenter-offSet]=this::createCommitRoleGroupToCenterServerResponse;
		list[ServerMessageType.CommitRoleSocialToCenter-offSet]=this::createCommitRoleSocialToCenterServerResponse;
		list[ServerMessageType.FuncAcceptMatchToCenter-offSet]=this::createFuncAcceptMatchToCenterServerResponse;
		list[ServerMessageType.FuncApplyCancelMatchToCenter-offSet]=this::createFuncApplyCancelMatchToCenterServerResponse;
		list[ServerMessageType.FuncApplyMatchToCenter-offSet]=this::createFuncApplyMatchToCenterServerResponse;
		list[ServerMessageType.FuncCommitRankValueToCenter-offSet]=this::createFuncCommitRankValueToCenterServerResponse;
		list[ServerMessageType.FuncCommitSubsectionRankValueToCenter-offSet]=this::createFuncCommitSubsectionRankValueToCenterServerResponse;
		list[ServerMessageType.FuncGetRandomPlayerListFromRoleSocialPoolToCenter-offSet]=this::createFuncGetRandomPlayerListFromRoleSocialPoolToCenterServerResponse;
		list[ServerMessageType.FuncPlayerToCenter-offSet]=this::createFuncPlayerToCenterServerResponse;
		list[ServerMessageType.FuncRemoveRankToCenter-offSet]=this::createFuncRemoveRankToCenterServerResponse;
		list[ServerMessageType.FuncRemoveSubsectionRankToCenter-offSet]=this::createFuncRemoveSubsectionRankToCenterServerResponse;
		list[ServerMessageType.FuncRoleGroupChangeSimpleToCenter-offSet]=this::createFuncRoleGroupChangeSimpleToCenterServerResponse;
		list[ServerMessageType.FuncSendAuctionBuyItemToCenter-offSet]=this::createFuncSendAuctionBuyItemToCenterServerResponse;
		list[ServerMessageType.FuncSendAuctionCancelSellItemToCenter-offSet]=this::createFuncSendAuctionCancelSellItemToCenterServerResponse;
		list[ServerMessageType.FuncSendAuctionSellItemToCenter-offSet]=this::createFuncSendAuctionSellItemToCenterServerResponse;
		list[ServerMessageType.FuncSendGetPageShowToCenter-offSet]=this::createFuncSendGetPageShowToCenterServerResponse;
		list[ServerMessageType.FuncToCenter-offSet]=this::createFuncToCenterServerResponse;
		list[ServerMessageType.GameLoginToCenter-offSet]=this::createGameLoginToCenterServerResponse;
		list[ServerMessageType.PlayerToCenter-offSet]=this::createPlayerToCenterServerResponse;
		list[ServerMessageType.ReCreateSignedSceneToCenter-offSet]=this::createReCreateSignedSceneToCenterServerResponse;
		list[ServerMessageType.ReceiptWorkToCenter-offSet]=this::createReceiptWorkToCenterServerResponse;
		list[ServerMessageType.RefreshRoleSocialToCenter-offSet]=this::createRefreshRoleSocialToCenterServerResponse;
		list[ServerMessageType.SendCenterWorkCompleteToCenter-offSet]=this::createSendCenterWorkCompleteToCenterServerResponse;
		list[ServerMessageType.SendCenterWorkToCenter-offSet]=this::createSendCenterWorkToCenterServerResponse;
		list[ServerMessageType.SendMQueryPlayerWorkResultToCenter-offSet]=this::createSendMQueryPlayerWorkResultToCenterServerResponse;
		list[ServerMessageType.SendPlayerOnlineNumToCenter-offSet]=this::createSendPlayerOnlineNumToCenterServerResponse;
		list[ServerMessageType.SendPlayerWorkToCenter-offSet]=this::createSendPlayerWorkToCenterServerResponse;
		list[ServerMessageType.UseActivationCodeToCenter-offSet]=this::createUseActivationCodeToCenterServerResponse;
	}
	
	private BaseData createBeGameToCenterServerResponse()
	{
		return new BeGameToCenterServerResponse();
	}
	
	private BaseData createPlayerToCenterServerResponse()
	{
		return new PlayerToCenterServerResponse();
	}
	
	private BaseData createFuncAcceptMatchToCenterServerResponse()
	{
		return new FuncAcceptMatchToCenterServerResponse();
	}
	
	private BaseData createFuncApplyCancelMatchToCenterServerResponse()
	{
		return new FuncApplyCancelMatchToCenterServerResponse();
	}
	
	private BaseData createFuncApplyMatchToCenterServerResponse()
	{
		return new FuncApplyMatchToCenterServerResponse();
	}
	
	private BaseData createCenterTransGameToCenterServerResponse()
	{
		return new CenterTransGameToCenterServerResponse();
	}
	
	private BaseData createReCreateSignedSceneToCenterServerResponse()
	{
		return new ReCreateSignedSceneToCenterServerResponse();
	}
	
	private BaseData createFuncCommitRankValueToCenterServerResponse()
	{
		return new FuncCommitRankValueToCenterServerResponse();
	}
	
	private BaseData createClientGMToCenterServerResponse()
	{
		return new ClientGMToCenterServerResponse();
	}
	
	private BaseData createFuncRemoveRankToCenterServerResponse()
	{
		return new FuncRemoveRankToCenterServerResponse();
	}
	
	private BaseData createFuncPlayerToCenterServerResponse()
	{
		return new FuncPlayerToCenterServerResponse();
	}
	
	private BaseData createCommitRoleSocialToCenterServerResponse()
	{
		return new CommitRoleSocialToCenterServerResponse();
	}
	
	private BaseData createRefreshRoleSocialToCenterServerResponse()
	{
		return new RefreshRoleSocialToCenterServerResponse();
	}
	
	private BaseData createSendPlayerWorkToCenterServerResponse()
	{
		return new SendPlayerWorkToCenterServerResponse();
	}
	
	private BaseData createReceiptWorkToCenterServerResponse()
	{
		return new ReceiptWorkToCenterServerResponse();
	}
	
	private BaseData createMAddPlayerWorkToCenterServerResponse()
	{
		return new MAddPlayerWorkToCenterServerResponse();
	}
	
	private BaseData createSendMQueryPlayerWorkResultToCenterServerResponse()
	{
		return new SendMQueryPlayerWorkResultToCenterServerResponse();
	}
	
	private BaseData createMQueryPlayerWorkToCenterServerResponse()
	{
		return new MQueryPlayerWorkToCenterServerResponse();
	}
	
	private BaseData createSendCenterWorkToCenterServerResponse()
	{
		return new SendCenterWorkToCenterServerResponse();
	}
	
	private BaseData createFuncGetRandomPlayerListFromRoleSocialPoolToCenterServerResponse()
	{
		return new FuncGetRandomPlayerListFromRoleSocialPoolToCenterServerResponse();
	}
	
	private BaseData createUseActivationCodeToCenterServerResponse()
	{
		return new UseActivationCodeToCenterServerResponse();
	}
	
	private BaseData createFuncSendGetPageShowToCenterServerResponse()
	{
		return new FuncSendGetPageShowToCenterServerResponse();
	}
	
	private BaseData createGameLoginToCenterServerResponse()
	{
		return new GameLoginToCenterServerResponse();
	}
	
	private BaseData createCommitCustomRoleSocialToCenterServerResponse()
	{
		return new CommitCustomRoleSocialToCenterServerResponse();
	}
	
	private BaseData createSendPlayerOnlineNumToCenterServerResponse()
	{
		return new SendPlayerOnlineNumToCenterServerResponse();
	}
	
	private BaseData createReBeCenterToManagerServerResponse()
	{
		return new ReBeCenterToManagerServerResponse();
	}
	
	private BaseData createCenterExitServerResponse()
	{
		return new CenterExitServerResponse();
	}
	
	private BaseData createManagerToCenterCommandServerResponse()
	{
		return new ManagerToCenterCommandServerResponse();
	}
	
	private BaseData createCommitRoleGroupToCenterServerResponse()
	{
		return new CommitRoleGroupToCenterServerResponse();
	}
	
	private BaseData createSendCenterWorkCompleteToCenterServerResponse()
	{
		return new SendCenterWorkCompleteToCenterServerResponse();
	}
	
	private BaseData createFuncRoleGroupChangeSimpleToCenterServerResponse()
	{
		return new FuncRoleGroupChangeSimpleToCenterServerResponse();
	}
	
	private BaseData createFuncToCenterServerResponse()
	{
		return new FuncToCenterServerResponse();
	}
	
	private BaseData createFuncSendAuctionSellItemToCenterServerResponse()
	{
		return new FuncSendAuctionSellItemToCenterServerResponse();
	}
	
	private BaseData createFuncSendAuctionCancelSellItemToCenterServerResponse()
	{
		return new FuncSendAuctionCancelSellItemToCenterServerResponse();
	}
	
	private BaseData createFuncSendAuctionBuyItemToCenterServerResponse()
	{
		return new FuncSendAuctionBuyItemToCenterServerResponse();
	}
	
	private BaseData createFuncCommitSubsectionRankValueToCenterServerResponse()
	{
		return new FuncCommitSubsectionRankValueToCenterServerResponse();
	}
	
	private BaseData createFuncRemoveSubsectionRankToCenterServerResponse()
	{
		return new FuncRemoveSubsectionRankToCenterServerResponse();
	}
	
	private BaseData createReloadServerConfigToCenterServerResponse()
	{
		return new ReloadServerConfigToCenterServerResponse();
	}
	
}
