package com.home.commonGame.net.serverRequest.center.func.rank.subsection;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.net.serverRequest.center.func.base.FuncPlayerToCenterServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 分段排行榜删除排行到中心服(generated by shine) */
public class FuncRemoveSubsectionRankToCenterServerRequest extends FuncPlayerToCenterServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncRemoveSubsectionRankToCenter;
	
	/** 版本号 */
	public int version;
	
	public FuncRemoveSubsectionRankToCenterServerRequest()
	{
		_dataID=ServerMessageType.FuncRemoveSubsectionRankToCenter;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncRemoveSubsectionRankToCenterServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.version);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("version");
		writer.sb.append(':');
		writer.sb.append(this.version);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.version=0;
	}
	
	/** 创建实例 */
	public static FuncRemoveSubsectionRankToCenterServerRequest create(long playerID,int funcID,int version)
	{
		FuncRemoveSubsectionRankToCenterServerRequest re=(FuncRemoveSubsectionRankToCenterServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.funcID=funcID;
		re.version=version;
		return re;
	}
	
}
