package com.home.commonGame.net.serverResponse.scene.base;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.global.GameC;
import com.home.commonGame.net.serverResponse.scene.base.SceneToGameServerResponse;
import com.home.commonGame.part.player.Player;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.ctrl.Ctrl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 角色场景服到game服消息(generated by shine) */
public class PlayerSceneToGameServerResponse extends SceneToGameServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.PlayerSceneToGame;
	
	/** 玩家id */
	public long playerID;
	
	/** 角色 */
	public Player me;
	
	public PlayerSceneToGameServerResponse()
	{
		_dataID=ServerMessageType.PlayerSceneToGame;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "PlayerSceneToGameServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.playerID=stream.readLong();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("playerID");
		writer.sb.append(':');
		writer.sb.append(this.playerID);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.playerID=0L;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
	@Override
	protected void preExecute()
	{
		me=GameC.main.getPlayerByID(playerID);
		
		if(me!=null)
		{
			doExecute();
		}
		else
		{
			Ctrl.warnLog("收到PlayerSceneToGameServerResponse时,player丢失",getDataClassName(),playerID);
		}
	}
	
}
