namespace Shine
{
	/** (generated by shine) */
	export class FuncReGetSelfPageShowResponse extends FuncSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.FuncReGetSelfPageShow;
		
		/** 页码 */
		public page:number;
		
		/** 数据组 */
		public list:SList<BaseData>;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.FuncReGetSelfPageShow;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "FuncReGetSelfPageShowResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.page=stream.readInt();
			
			if(stream.readBoolean())
			{
				var listLen:number=stream.readLen();
				if(this.list!=null)
				{
					this.list.clear();
					this.list.ensureCapacity(listLen);
				}
				else
				{
					this.list=new SList<BaseData>();
				}
				
				var listT:SList<BaseData>=this.list;
				for(var listI:number=listLen-1;listI>=0;--listI)
				{
					var listV:BaseData;
					if(stream.readBoolean())
					{
						listV=stream.readDataSimpleNotNull() as BaseData;
					}
					else
					{
						listV=null;
					}
					
					listT.add(listV);
				}
			}
			else
			{
				this.list=null;
			}
			
		}
		
		/** 执行 */
		protected execute():void
		{
			
		}
		
	}
}
