namespace Shine
{
	/** 功能-回复查询每页排行(generated by shine) */
	export class FuncReGetPageShowResponse extends FuncSResponse
	{
		/** 数据类型ID */
		public static dataID:number=GameResponseType.FuncReGetPageShow;
		
		/** 页码 */
		public page:number;
		
		/** 数据组 */
		public dic:SMap<number,KeyData>;
		
		/** 改变页码组 */
		public changePageSet:SSet<number>;
		
		constructor()
		{
			super();
			this._dataID=GameResponseType.FuncReGetPageShow;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "FuncReGetPageShowResponse";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			super.toReadBytesSimple(stream);
			
			this.page=stream.readInt();
			
			if(stream.readBoolean())
			{
				var dicLen:number=stream.readLen();
				if(this.dic!=null)
				{
					this.dic.clear();
					this.dic.ensureCapacity(dicLen);
				}
				else
				{
					this.dic=new SMap<number,KeyData>(dicLen);
				}
				
				var dicT:SMap<number,KeyData>=this.dic;
				for(var dicI:number=dicLen-1;dicI>=0;--dicI)
				{
					var dicK:number;
					var dicV:KeyData;
					dicK=stream.readInt();
					
					if(stream.readBoolean())
					{
						dicV=stream.readDataSimpleNotNull() as KeyData;
					}
					else
					{
						dicV=null;
					}
					
					dicT.put(dicK,dicV);
				}
			}
			else
			{
				this.dic=null;
			}
			
			if(stream.readBoolean())
			{
				var changePageSetLen:number=stream.readLen();
				if(this.changePageSet!=null)
				{
					this.changePageSet.clear();
					this.changePageSet.ensureCapacity(changePageSetLen);
				}
				else
				{
					this.changePageSet=new SSet<number>();
				}
				
				var changePageSetT:SSet<number>=this.changePageSet;
				for(var changePageSetI:number=changePageSetLen-1;changePageSetI>=0;--changePageSetI)
				{
					var changePageSetV:number;
					changePageSetV=stream.readInt();
					
					changePageSetT.add(changePageSetV);
				}
			}
			else
			{
				this.changePageSet=null;
			}
			
		}
		
		/** 执行 */
		protected execute():void
		{
			this.me.func.getPageShowTool(this.funcID).onReceivePage(this.page,this.dic,this.changePageSet);
		}
		
	}
}
