package com.home.commonLogin.net.serverResponse.game.login;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonLogin.global.LoginC;
import com.home.commonLogin.net.serverResponse.game.base.GameToLoginServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 客户端申请绑定平台消息(generated by shine) */
public class ClientApplyBindPlatformToLoginServerResponse extends GameToLoginServerResponse
{
	/** 发起玩家id */
	public long playerID;
	
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.ClientApplyBindPlatformToLogin;
	
	public long userID;
	
	public String uid="";
	
	public String platform="";
	
	public ClientApplyBindPlatformToLoginServerResponse()
	{
		_dataID=ServerMessageType.ClientApplyBindPlatformToLogin;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "ClientApplyBindPlatformToLoginServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.playerID=stream.readLong();
		
		this.userID=stream.readLong();
		
		this.uid=stream.readUTF();
		
		this.platform=stream.readUTF();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("playerID");
		writer.sb.append(':');
		writer.sb.append(this.playerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("userID");
		writer.sb.append(':');
		writer.sb.append(this.userID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("uid");
		writer.sb.append(':');
		writer.sb.append(this.uid);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("platform");
		writer.sb.append(':');
		writer.sb.append(this.platform);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		LoginC.main.bindPlatformByClient(playerID,userID,uid,platform);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.playerID=0L;
		this.userID=0L;
		this.uid="";
		this.platform="";
	}
	
}
