namespace Shine
{
	/** 基础事务数据(用dataID区分)(generated by shine) */
	export class WorkData extends BaseData
	{
		/** 数据类型ID */
		public static dataID:number=BaseDataType.Work;
		
		/** 时间戳 */
		public timestamp:number;
		
		/** 实例ID */
		public workInstanceID:number;
		
		/** 事务类型(见WorkType)(离线,在线,立即) */
		public workType:number;
		
		/** 发起者索引(type+id) */
		public senderIndex:number;
		
		/** 发送者携带ID(做其他业务回执用) */
		public senderCarryID:number;
		
		constructor()
		{
			super();
			this._dataID=BaseDataType.Work;
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "WorkData";
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			this.timestamp=stream.readLong();
			
			this.workInstanceID=stream.readLong();
			
			this.workType=stream.readInt();
			
			this.senderIndex=stream.readInt();
			
			this.senderCarryID=stream.readInt();
			
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			stream.writeLong(this.timestamp);
			
			stream.writeLong(this.workInstanceID);
			
			stream.writeInt(this.workType);
			
			stream.writeInt(this.senderIndex);
			
			stream.writeInt(this.senderCarryID);
			
		}
		
		/** 复制(潜拷贝) */
		protected toShadowCopy(data:BaseData):void
		{
			if(!(data instanceof WorkData))
				return;
			
			var mData:WorkData=data as WorkData;
			
			this.timestamp=mData.timestamp;
			this.workInstanceID=mData.workInstanceID;
			this.workType=mData.workType;
			this.senderIndex=mData.senderIndex;
			this.senderCarryID=mData.senderCarryID;
		}
		
		/** 复制(深拷贝) */
		protected toCopy(data:BaseData):void
		{
			if(!(data instanceof WorkData))
				return;
			
			var mData:WorkData=data as WorkData;
			
			this.timestamp=mData.timestamp;
			
			this.workInstanceID=mData.workInstanceID;
			
			this.workType=mData.workType;
			
			this.senderIndex=mData.senderIndex;
			
			this.senderCarryID=mData.senderCarryID;
			
		}
		
		/** 初始化初值 */
		public initDefault():void
		{
			
		}
		
	}
}
