package com.home.commonBase.data.login;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.social.RoleSocialData;
import com.home.commonBase.data.social.roleGroup.PlayerRoleGroupData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.IntObjectMap;
import com.home.shine.support.collection.LongObjectMap;
import com.home.shine.support.pool.DataPool;

/** 角色切换游戏服额外传输数据(在PlayerList之外)(generated by shine) */
public class PlayerSwitchGameData extends BaseData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.PlayerSwitchGame;
	
	/** 是否是切换登录 */
	public boolean isSwitchLogin;
	
	/** 玩家群组(key:funcID) */
	public IntObjectMap<LongObjectMap<PlayerRoleGroupData>> roleGroups;
	
	/** 社交数据组 */
	public LongObjectMap<RoleSocialData> roleSocialDatas;
	
	/** 是否需要中心服角色显示信息 */
	public boolean needPlayerRoleShowForCenter;
	
	public PlayerSwitchGameData()
	{
		_dataID=BaseDataType.PlayerSwitchGame;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "PlayerSwitchGameData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.needPlayerRoleShowForCenter=stream.readBoolean();
		
		this.isSwitchLogin=stream.readBoolean();
		
		int roleSocialDatasLen=stream.readLen();
		if(this.roleSocialDatas!=null)
		{
			this.roleSocialDatas.clear();
			this.roleSocialDatas.ensureCapacity(roleSocialDatasLen);
		}
		else
		{
			this.roleSocialDatas=new LongObjectMap<RoleSocialData>(RoleSocialData[]::new,roleSocialDatasLen);
		}
		
		LongObjectMap<RoleSocialData> roleSocialDatasT=this.roleSocialDatas;
		for(int roleSocialDatasI=roleSocialDatasLen-1;roleSocialDatasI>=0;--roleSocialDatasI)
		{
			RoleSocialData roleSocialDatasV;
			BaseData roleSocialDatasVT=stream.readDataFullNotNull();
			if(roleSocialDatasVT!=null)
			{
				if(roleSocialDatasVT instanceof RoleSocialData)
				{
					roleSocialDatasV=(RoleSocialData)roleSocialDatasVT;
				}
				else
				{
					roleSocialDatasV=new RoleSocialData();
					if(!(roleSocialDatasVT.getClass().isAssignableFrom(RoleSocialData.class)))
					{
						stream.throwTypeReadError(RoleSocialData.class,roleSocialDatasVT.getClass());
					}
					roleSocialDatasV.shadowCopy(roleSocialDatasVT);
				}
			}
			else
			{
				roleSocialDatasV=null;
			}
			
			roleSocialDatasT.put(roleSocialDatasV.showData.playerID,roleSocialDatasV);
		}
		
		int roleGroupsLen=stream.readLen();
		if(this.roleGroups!=null)
		{
			this.roleGroups.clear();
			this.roleGroups.ensureCapacity(roleGroupsLen);
		}
		else
		{
			this.roleGroups=new IntObjectMap<LongObjectMap<PlayerRoleGroupData>>(LongObjectMap[]::new,roleGroupsLen);
		}
		
		IntObjectMap<LongObjectMap<PlayerRoleGroupData>> roleGroupsT=this.roleGroups;
		for(int roleGroupsI=roleGroupsLen-1;roleGroupsI>=0;--roleGroupsI)
		{
			int roleGroupsK;
			LongObjectMap<PlayerRoleGroupData> roleGroupsV;
			roleGroupsK=stream.readInt();
			
			int roleGroupsVLen=stream.readLen();
			roleGroupsV=new LongObjectMap<PlayerRoleGroupData>(PlayerRoleGroupData[]::new,roleGroupsVLen);
			LongObjectMap<PlayerRoleGroupData> roleGroupsVT=roleGroupsV;
			for(int roleGroupsVI=roleGroupsVLen-1;roleGroupsVI>=0;--roleGroupsVI)
			{
				long roleGroupsVK;
				PlayerRoleGroupData roleGroupsVV;
				roleGroupsVK=stream.readLong();
				
				BaseData roleGroupsVVT=stream.readDataFullNotNull();
				if(roleGroupsVVT!=null)
				{
					if(roleGroupsVVT instanceof PlayerRoleGroupData)
					{
						roleGroupsVV=(PlayerRoleGroupData)roleGroupsVVT;
					}
					else
					{
						roleGroupsVV=new PlayerRoleGroupData();
						if(!(roleGroupsVVT.getClass().isAssignableFrom(PlayerRoleGroupData.class)))
						{
							stream.throwTypeReadError(PlayerRoleGroupData.class,roleGroupsVVT.getClass());
						}
						roleGroupsVV.shadowCopy(roleGroupsVVT);
					}
				}
				else
				{
					roleGroupsVV=null;
				}
				
				roleGroupsVT.put(roleGroupsVK,roleGroupsVV);
			}
			
			roleGroupsT.put(roleGroupsK,roleGroupsV);
		}
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeBoolean(this.needPlayerRoleShowForCenter);
		
		stream.writeBoolean(this.isSwitchLogin);
		
		if(this.roleSocialDatas!=null)
		{
			stream.writeLen(this.roleSocialDatas.size());
			if(!this.roleSocialDatas.isEmpty())
			{
				Object[] roleSocialDatasVValues=this.roleSocialDatas.getValues();
				for(int roleSocialDatasVI=roleSocialDatasVValues.length-1;roleSocialDatasVI>=0;--roleSocialDatasVI)
				{
					if(roleSocialDatasVValues[roleSocialDatasVI]!=null)
					{
						RoleSocialData roleSocialDatasV=(RoleSocialData)roleSocialDatasVValues[roleSocialDatasVI];
						if(roleSocialDatasV!=null)
						{
							stream.writeDataFullNotNull(roleSocialDatasV);
						}
						else
						{
							nullObjError("roleSocialDatasV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("roleSocialDatas");
		}
		
		if(this.roleGroups!=null)
		{
			stream.writeLen(this.roleGroups.size());
			if(!this.roleGroups.isEmpty())
			{
				int roleGroupsKFreeValue=this.roleGroups.getFreeValue();
				int[] roleGroupsKKeys=this.roleGroups.getKeys();
				Object[] roleGroupsVValues=this.roleGroups.getValues();
				for(int roleGroupsKI=roleGroupsKKeys.length-1;roleGroupsKI>=0;--roleGroupsKI)
				{
					int roleGroupsK=roleGroupsKKeys[roleGroupsKI];
					if(roleGroupsK!=roleGroupsKFreeValue)
					{
						LongObjectMap<PlayerRoleGroupData> roleGroupsV=(LongObjectMap<PlayerRoleGroupData>)roleGroupsVValues[roleGroupsKI];
						stream.writeInt(roleGroupsK);
						
						if(roleGroupsV!=null)
						{
							stream.writeLen(roleGroupsV.size());
							if(!roleGroupsV.isEmpty())
							{
								long roleGroupsVKFreeValue=roleGroupsV.getFreeValue();
								long[] roleGroupsVKKeys=roleGroupsV.getKeys();
								Object[] roleGroupsVVValues=roleGroupsV.getValues();
								for(int roleGroupsVKI=roleGroupsVKKeys.length-1;roleGroupsVKI>=0;--roleGroupsVKI)
								{
									long roleGroupsVK=roleGroupsVKKeys[roleGroupsVKI];
									if(roleGroupsVK!=roleGroupsVKFreeValue)
									{
										PlayerRoleGroupData roleGroupsVV=(PlayerRoleGroupData)roleGroupsVVValues[roleGroupsVKI];
										stream.writeLong(roleGroupsVK);
										
										if(roleGroupsVV!=null)
										{
											stream.writeDataFullNotNull(roleGroupsVV);
										}
										else
										{
											nullObjError("roleGroupsVV");
										}
										
									}
								}
							}
						}
						else
						{
							nullObjError("roleGroupsV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("roleGroups");
		}
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.needPlayerRoleShowForCenter=stream.readBoolean();
		
		this.isSwitchLogin=stream.readBoolean();
		
		int roleSocialDatasLen=stream.readLen();
		if(this.roleSocialDatas!=null)
		{
			this.roleSocialDatas.clear();
			this.roleSocialDatas.ensureCapacity(roleSocialDatasLen);
		}
		else
		{
			this.roleSocialDatas=new LongObjectMap<RoleSocialData>(RoleSocialData[]::new,roleSocialDatasLen);
		}
		
		LongObjectMap<RoleSocialData> roleSocialDatasT=this.roleSocialDatas;
		for(int roleSocialDatasI=roleSocialDatasLen-1;roleSocialDatasI>=0;--roleSocialDatasI)
		{
			RoleSocialData roleSocialDatasV;
			roleSocialDatasV=(RoleSocialData)stream.readDataSimpleNotNull();
			
			roleSocialDatasT.put(roleSocialDatasV.showData.playerID,roleSocialDatasV);
		}
		
		int roleGroupsLen=stream.readLen();
		if(this.roleGroups!=null)
		{
			this.roleGroups.clear();
			this.roleGroups.ensureCapacity(roleGroupsLen);
		}
		else
		{
			this.roleGroups=new IntObjectMap<LongObjectMap<PlayerRoleGroupData>>(LongObjectMap[]::new,roleGroupsLen);
		}
		
		IntObjectMap<LongObjectMap<PlayerRoleGroupData>> roleGroupsT=this.roleGroups;
		for(int roleGroupsI=roleGroupsLen-1;roleGroupsI>=0;--roleGroupsI)
		{
			int roleGroupsK;
			LongObjectMap<PlayerRoleGroupData> roleGroupsV;
			roleGroupsK=stream.readInt();
			
			int roleGroupsVLen=stream.readLen();
			roleGroupsV=new LongObjectMap<PlayerRoleGroupData>(PlayerRoleGroupData[]::new,roleGroupsVLen);
			LongObjectMap<PlayerRoleGroupData> roleGroupsVT=roleGroupsV;
			for(int roleGroupsVI=roleGroupsVLen-1;roleGroupsVI>=0;--roleGroupsVI)
			{
				long roleGroupsVK;
				PlayerRoleGroupData roleGroupsVV;
				roleGroupsVK=stream.readLong();
				
				roleGroupsVV=(PlayerRoleGroupData)stream.readDataSimpleNotNull();
				
				roleGroupsVT.put(roleGroupsVK,roleGroupsVV);
			}
			
			roleGroupsT.put(roleGroupsK,roleGroupsV);
		}
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeBoolean(this.needPlayerRoleShowForCenter);
		
		stream.writeBoolean(this.isSwitchLogin);
		
		if(this.roleSocialDatas!=null)
		{
			stream.writeLen(this.roleSocialDatas.size());
			if(!this.roleSocialDatas.isEmpty())
			{
				Object[] roleSocialDatasVValues=this.roleSocialDatas.getValues();
				for(int roleSocialDatasVI=roleSocialDatasVValues.length-1;roleSocialDatasVI>=0;--roleSocialDatasVI)
				{
					if(roleSocialDatasVValues[roleSocialDatasVI]!=null)
					{
						RoleSocialData roleSocialDatasV=(RoleSocialData)roleSocialDatasVValues[roleSocialDatasVI];
						if(roleSocialDatasV!=null)
						{
							stream.writeDataSimpleNotNull(roleSocialDatasV);
						}
						else
						{
							nullObjError("roleSocialDatasV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("roleSocialDatas");
		}
		
		if(this.roleGroups!=null)
		{
			stream.writeLen(this.roleGroups.size());
			if(!this.roleGroups.isEmpty())
			{
				int roleGroupsKFreeValue=this.roleGroups.getFreeValue();
				int[] roleGroupsKKeys=this.roleGroups.getKeys();
				Object[] roleGroupsVValues=this.roleGroups.getValues();
				for(int roleGroupsKI=roleGroupsKKeys.length-1;roleGroupsKI>=0;--roleGroupsKI)
				{
					int roleGroupsK=roleGroupsKKeys[roleGroupsKI];
					if(roleGroupsK!=roleGroupsKFreeValue)
					{
						LongObjectMap<PlayerRoleGroupData> roleGroupsV=(LongObjectMap<PlayerRoleGroupData>)roleGroupsVValues[roleGroupsKI];
						stream.writeInt(roleGroupsK);
						
						if(roleGroupsV!=null)
						{
							stream.writeLen(roleGroupsV.size());
							if(!roleGroupsV.isEmpty())
							{
								long roleGroupsVKFreeValue=roleGroupsV.getFreeValue();
								long[] roleGroupsVKKeys=roleGroupsV.getKeys();
								Object[] roleGroupsVVValues=roleGroupsV.getValues();
								for(int roleGroupsVKI=roleGroupsVKKeys.length-1;roleGroupsVKI>=0;--roleGroupsVKI)
								{
									long roleGroupsVK=roleGroupsVKKeys[roleGroupsVKI];
									if(roleGroupsVK!=roleGroupsVKFreeValue)
									{
										PlayerRoleGroupData roleGroupsVV=(PlayerRoleGroupData)roleGroupsVVValues[roleGroupsVKI];
										stream.writeLong(roleGroupsVK);
										
										if(roleGroupsVV!=null)
										{
											stream.writeDataSimpleNotNull(roleGroupsVV);
										}
										else
										{
											nullObjError("roleGroupsVV");
										}
										
									}
								}
							}
						}
						else
						{
							nullObjError("roleGroupsV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("roleGroups");
		}
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof PlayerSwitchGameData))
			return;
		
		PlayerSwitchGameData mData=(PlayerSwitchGameData)data;
		
		this.needPlayerRoleShowForCenter=mData.needPlayerRoleShowForCenter;
		this.isSwitchLogin=mData.isSwitchLogin;
		this.roleSocialDatas=mData.roleSocialDatas;
		this.roleGroups=mData.roleGroups;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof PlayerSwitchGameData))
			return;
		
		PlayerSwitchGameData mData=(PlayerSwitchGameData)data;
		
		this.needPlayerRoleShowForCenter=mData.needPlayerRoleShowForCenter;
		
		this.isSwitchLogin=mData.isSwitchLogin;
		
		if(mData.roleSocialDatas!=null)
		{
			if(this.roleSocialDatas!=null)
			{
				this.roleSocialDatas.clear();
				this.roleSocialDatas.ensureCapacity(mData.roleSocialDatas.size());
			}
			else
			{
				this.roleSocialDatas=new LongObjectMap<RoleSocialData>(RoleSocialData[]::new,mData.roleSocialDatas.size());
			}
			
			LongObjectMap<RoleSocialData> roleSocialDatasT=this.roleSocialDatas;
			if(!mData.roleSocialDatas.isEmpty())
			{
				Object[] roleSocialDatasVValues=mData.roleSocialDatas.getValues();
				for(int roleSocialDatasVI=roleSocialDatasVValues.length-1;roleSocialDatasVI>=0;--roleSocialDatasVI)
				{
					if(roleSocialDatasVValues[roleSocialDatasVI]!=null)
					{
						RoleSocialData roleSocialDatasV=(RoleSocialData)roleSocialDatasVValues[roleSocialDatasVI];
						RoleSocialData roleSocialDatasU;
						if(roleSocialDatasV!=null)
						{
							roleSocialDatasU=(RoleSocialData)roleSocialDatasV.clone();
						}
						else
						{
							roleSocialDatasU=null;
							nullObjError("roleSocialDatasU");
						}
						
						roleSocialDatasT.put(roleSocialDatasU.showData.playerID,roleSocialDatasU);
					}
				}
			}
		}
		else
		{
			this.roleSocialDatas=null;
			nullObjError("roleSocialDatas");
		}
		
		if(mData.roleGroups!=null)
		{
			if(this.roleGroups!=null)
			{
				this.roleGroups.clear();
				this.roleGroups.ensureCapacity(mData.roleGroups.size());
			}
			else
			{
				this.roleGroups=new IntObjectMap<LongObjectMap<PlayerRoleGroupData>>(LongObjectMap[]::new,mData.roleGroups.size());
			}
			
			IntObjectMap<LongObjectMap<PlayerRoleGroupData>> roleGroupsT=this.roleGroups;
			if(!mData.roleGroups.isEmpty())
			{
				int roleGroupsKFreeValue=mData.roleGroups.getFreeValue();
				int[] roleGroupsKKeys=mData.roleGroups.getKeys();
				Object[] roleGroupsVValues=mData.roleGroups.getValues();
				for(int roleGroupsKI=roleGroupsKKeys.length-1;roleGroupsKI>=0;--roleGroupsKI)
				{
					int roleGroupsK=roleGroupsKKeys[roleGroupsKI];
					if(roleGroupsK!=roleGroupsKFreeValue)
					{
						LongObjectMap<PlayerRoleGroupData> roleGroupsV=(LongObjectMap<PlayerRoleGroupData>)roleGroupsVValues[roleGroupsKI];
						int roleGroupsW;
						LongObjectMap<PlayerRoleGroupData> roleGroupsU;
						roleGroupsW=roleGroupsK;
						
						if(roleGroupsV!=null)
						{
							roleGroupsU=new LongObjectMap<PlayerRoleGroupData>(PlayerRoleGroupData[]::new,roleGroupsV.size());
							LongObjectMap<PlayerRoleGroupData> roleGroupsUT=roleGroupsU;
							if(!roleGroupsV.isEmpty())
							{
								long roleGroupsUKFreeValue=roleGroupsV.getFreeValue();
								long[] roleGroupsUKKeys=roleGroupsV.getKeys();
								Object[] roleGroupsUVValues=roleGroupsV.getValues();
								for(int roleGroupsUKI=roleGroupsUKKeys.length-1;roleGroupsUKI>=0;--roleGroupsUKI)
								{
									long roleGroupsUK=roleGroupsUKKeys[roleGroupsUKI];
									if(roleGroupsUK!=roleGroupsUKFreeValue)
									{
										PlayerRoleGroupData roleGroupsUV=(PlayerRoleGroupData)roleGroupsUVValues[roleGroupsUKI];
										long roleGroupsUW;
										PlayerRoleGroupData roleGroupsUU;
										roleGroupsUW=roleGroupsUK;
										
										if(roleGroupsUV!=null)
										{
											roleGroupsUU=(PlayerRoleGroupData)roleGroupsUV.clone();
										}
										else
										{
											roleGroupsUU=null;
											nullObjError("roleGroupsUU");
										}
										
										roleGroupsUT.put(roleGroupsUW,roleGroupsUU);
									}
								}
							}
						}
						else
						{
							roleGroupsU=null;
							nullObjError("roleGroupsU");
						}
						
						roleGroupsT.put(roleGroupsW,roleGroupsU);
					}
				}
			}
		}
		else
		{
			this.roleGroups=null;
			nullObjError("roleGroups");
		}
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		PlayerSwitchGameData mData=(PlayerSwitchGameData)data;
		if(this.needPlayerRoleShowForCenter!=mData.needPlayerRoleShowForCenter)
			return false;
		
		if(this.isSwitchLogin!=mData.isSwitchLogin)
			return false;
		
		if(mData.roleSocialDatas!=null)
		{
			if(this.roleSocialDatas==null)
				return false;
			if(this.roleSocialDatas.size()!=mData.roleSocialDatas.size())
				return false;
			LongObjectMap<RoleSocialData> roleSocialDatasR=mData.roleSocialDatas;
			if(!this.roleSocialDatas.isEmpty())
			{
				long roleSocialDatasKFreeValue=this.roleSocialDatas.getFreeValue();
				long[] roleSocialDatasKKeys=this.roleSocialDatas.getKeys();
				Object[] roleSocialDatasVValues=this.roleSocialDatas.getValues();
				for(int roleSocialDatasKI=roleSocialDatasKKeys.length-1;roleSocialDatasKI>=0;--roleSocialDatasKI)
				{
					long roleSocialDatasK=roleSocialDatasKKeys[roleSocialDatasKI];
					if(roleSocialDatasK!=roleSocialDatasKFreeValue)
					{
						RoleSocialData roleSocialDatasV=(RoleSocialData)roleSocialDatasVValues[roleSocialDatasKI];
						RoleSocialData roleSocialDatasU=roleSocialDatasR.get(roleSocialDatasK);
						if(roleSocialDatasU!=null)
						{
							if(roleSocialDatasV==null)
								return false;
							if(!roleSocialDatasV.dataEquals(roleSocialDatasU))
								return false;
						}
						else
						{
							if(roleSocialDatasV!=null)
								return false;
						}
						
					}
				}
			}
		}
		else
		{
			if(this.roleSocialDatas!=null)
				return false;
		}
		
		if(mData.roleGroups!=null)
		{
			if(this.roleGroups==null)
				return false;
			if(this.roleGroups.size()!=mData.roleGroups.size())
				return false;
			IntObjectMap<LongObjectMap<PlayerRoleGroupData>> roleGroupsR=mData.roleGroups;
			if(!this.roleGroups.isEmpty())
			{
				int roleGroupsKFreeValue=this.roleGroups.getFreeValue();
				int[] roleGroupsKKeys=this.roleGroups.getKeys();
				Object[] roleGroupsVValues=this.roleGroups.getValues();
				for(int roleGroupsKI=roleGroupsKKeys.length-1;roleGroupsKI>=0;--roleGroupsKI)
				{
					int roleGroupsK=roleGroupsKKeys[roleGroupsKI];
					if(roleGroupsK!=roleGroupsKFreeValue)
					{
						LongObjectMap<PlayerRoleGroupData> roleGroupsV=(LongObjectMap<PlayerRoleGroupData>)roleGroupsVValues[roleGroupsKI];
						LongObjectMap<PlayerRoleGroupData> roleGroupsU=roleGroupsR.get(roleGroupsK);
						if(roleGroupsU!=null)
						{
							if(roleGroupsV==null)
								return false;
							if(roleGroupsV.size()!=roleGroupsU.size())
								return false;
							LongObjectMap<PlayerRoleGroupData> roleGroupsVR=roleGroupsU;
							if(!roleGroupsV.isEmpty())
							{
								long roleGroupsVKFreeValue=roleGroupsV.getFreeValue();
								long[] roleGroupsVKKeys=roleGroupsV.getKeys();
								Object[] roleGroupsVVValues=roleGroupsV.getValues();
								for(int roleGroupsVKI=roleGroupsVKKeys.length-1;roleGroupsVKI>=0;--roleGroupsVKI)
								{
									long roleGroupsVK=roleGroupsVKKeys[roleGroupsVKI];
									if(roleGroupsVK!=roleGroupsVKFreeValue)
									{
										PlayerRoleGroupData roleGroupsVV=(PlayerRoleGroupData)roleGroupsVVValues[roleGroupsVKI];
										PlayerRoleGroupData roleGroupsVU=roleGroupsVR.get(roleGroupsVK);
										if(roleGroupsVU!=null)
										{
											if(roleGroupsVV==null)
												return false;
											if(!roleGroupsVV.dataEquals(roleGroupsVU))
												return false;
										}
										else
										{
											if(roleGroupsVV!=null)
												return false;
										}
										
									}
								}
							}
						}
						else
						{
							if(roleGroupsV!=null)
								return false;
						}
						
					}
				}
			}
		}
		else
		{
			if(this.roleGroups!=null)
				return false;
		}
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("needPlayerRoleShowForCenter");
		writer.sb.append(':');
		writer.sb.append(this.needPlayerRoleShowForCenter);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("isSwitchLogin");
		writer.sb.append(':');
		writer.sb.append(this.isSwitchLogin);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("roleSocialDatas");
		writer.sb.append(':');
		writer.sb.append("Map<long,RoleSocialData>");
		if(this.roleSocialDatas!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.roleSocialDatas.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.roleSocialDatas.isEmpty())
			{
				long roleSocialDatasKFreeValue=this.roleSocialDatas.getFreeValue();
				long[] roleSocialDatasKKeys=this.roleSocialDatas.getKeys();
				Object[] roleSocialDatasVValues=this.roleSocialDatas.getValues();
				for(int roleSocialDatasKI=roleSocialDatasKKeys.length-1;roleSocialDatasKI>=0;--roleSocialDatasKI)
				{
					long roleSocialDatasK=roleSocialDatasKKeys[roleSocialDatasKI];
					if(roleSocialDatasK!=roleSocialDatasKFreeValue)
					{
						RoleSocialData roleSocialDatasV=(RoleSocialData)roleSocialDatasVValues[roleSocialDatasKI];
						writer.writeTabs();
						writer.sb.append(roleSocialDatasK);
						
						writer.sb.append(':');
						if(roleSocialDatasV!=null)
						{
							roleSocialDatasV.writeDataString(writer);
						}
						else
						{
							writer.sb.append("RoleSocialData=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("roleGroups");
		writer.sb.append(':');
		writer.sb.append("Map<int,LongObjectMap<PlayerRoleGroupData>>");
		if(this.roleGroups!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.roleGroups.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.roleGroups.isEmpty())
			{
				int roleGroupsKFreeValue=this.roleGroups.getFreeValue();
				int[] roleGroupsKKeys=this.roleGroups.getKeys();
				Object[] roleGroupsVValues=this.roleGroups.getValues();
				for(int roleGroupsKI=roleGroupsKKeys.length-1;roleGroupsKI>=0;--roleGroupsKI)
				{
					int roleGroupsK=roleGroupsKKeys[roleGroupsKI];
					if(roleGroupsK!=roleGroupsKFreeValue)
					{
						LongObjectMap<PlayerRoleGroupData> roleGroupsV=(LongObjectMap<PlayerRoleGroupData>)roleGroupsVValues[roleGroupsKI];
						writer.writeTabs();
						writer.sb.append(roleGroupsK);
						
						writer.sb.append(':');
						writer.sb.append("Map<long,PlayerRoleGroupData>");
						if(roleGroupsV!=null)
						{
							writer.sb.append('(');
							writer.sb.append(roleGroupsV.size());
							writer.sb.append(')');
							writer.writeEnter();
							writer.writeLeftBrace();
							if(!roleGroupsV.isEmpty())
							{
								long roleGroupsVKFreeValue=roleGroupsV.getFreeValue();
								long[] roleGroupsVKKeys=roleGroupsV.getKeys();
								Object[] roleGroupsVVValues=roleGroupsV.getValues();
								for(int roleGroupsVKI=roleGroupsVKKeys.length-1;roleGroupsVKI>=0;--roleGroupsVKI)
								{
									long roleGroupsVK=roleGroupsVKKeys[roleGroupsVKI];
									if(roleGroupsVK!=roleGroupsVKFreeValue)
									{
										PlayerRoleGroupData roleGroupsVV=(PlayerRoleGroupData)roleGroupsVVValues[roleGroupsVKI];
										writer.writeTabs();
										writer.sb.append(roleGroupsVK);
										
										writer.sb.append(':');
										if(roleGroupsVV!=null)
										{
											roleGroupsVV.writeDataString(writer);
										}
										else
										{
											writer.sb.append("PlayerRoleGroupData=null");
										}
										
										writer.writeEnter();
									}
								}
							}
							writer.writeRightBrace();
						}
						else
						{
							writer.sb.append("=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		this.roleSocialDatas=new LongObjectMap<RoleSocialData>(RoleSocialData[]::new);
		this.roleGroups=new IntObjectMap<LongObjectMap<PlayerRoleGroupData>>(LongObjectMap[]::new);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.needPlayerRoleShowForCenter=false;
		this.isSwitchLogin=false;
		this.roleSocialDatas=null;
		this.roleGroups=null;
	}
	
}
