namespace Shine
{
	/** 发送客户端日志消息(generated by shine) */
	export class SendClientLogRequest extends GameRequest
	{
		/** 数据类型ID */
		public static dataID:number=GameRequestType.SendClientLog;
		
		/** 类型 */
		public type:number;
		
		/** 内容 */
		public content:string;
		
		constructor()
		{
			super();
			this._dataID=GameRequestType.SendClientLog;
		}
		
		protected copyData():void
		{
			super.copyData();
		}
		
		/** 获取数据类名 */
		public getDataClassName():string
		{
			return "SendClientLogRequest";
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			super.toWriteBytesSimple(stream);
			
			stream.writeInt(this.type);
			
			stream.writeUTF(this.content);
			
		}
		
		/** 创建实例 */
		public static createSendClientLog(type:number,content:string):SendClientLogRequest
		{
			var re:SendClientLogRequest=new SendClientLogRequest();
			re.type=type;
			re.content=content;
			return re;
		}
		
	}
}
