package com.home.commonGame.net.response.scene.unit;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.net.response.scene.base.CUnitRResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 单位骑乘载具(generated by shine) */
public class CUnitGetOnVehicleResponse extends CUnitRResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.CUnitGetOnVehicle;
	
	/** 骑乘位置 */
	public int index;
	
	/** 载具实例id */
	public int vehicleInstanceID;
	
	public CUnitGetOnVehicleResponse()
	{
		_dataID=GameResponseType.CUnitGetOnVehicle;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CUnitGetOnVehicleResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.vehicleInstanceID=stream.readInt();
		
		this.index=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.vehicleInstanceID=stream.readInt();
		
		this.index=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("vehicleInstanceID");
		writer.sb.append(':');
		writer.sb.append(this.vehicleInstanceID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("index");
		writer.sb.append(':');
		writer.sb.append(this.index);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		unit.move.getOnVehicle(vehicleInstanceID,index);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.vehicleInstanceID=0;
		this.index=0;
	}
	
}
