package com.home.commonGame.net.response.scene.unit;
import com.home.commonBase.scene.base.Unit;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.net.response.scene.base.CUnitRResponse;
import com.home.commonGame.net.response.scene.base.SceneRResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;

/** 玩家单位技能步骤(generated by shine) */
public class CUnitSkillStepResponse extends CUnitRResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.CUnitSkillStep;
	
	public CUnitSkillStepResponse()
	{
		_dataID=GameResponseType.CUnitSkillStep;
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		unit.fight.clientSkillStep();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CUnitSkillStepResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
}
