package com.home.commonSceneBase.net.sceneBaseResponse.base;
import com.home.commonBase.scene.base.Role;
import com.home.commonSceneBase.constlist.generate.SceneBaseResponseType;
import com.home.commonSceneBase.net.sceneBaseResponse.base.SceneRResponse;
import com.home.shine.bytes.BytesReadStream;

/** 控制角色消息(generated by shine) */
public class CRoleRResponse extends SceneRResponse
{
	/** 数据类型ID */
	public static final int dataID=SceneBaseResponseType.CRoleR;
	
	public Role role;
	
	public CRoleRResponse()
	{
		_dataID=SceneBaseResponseType.CRoleR;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "CRoleRResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		stream.endReadObj();
	}
	
	@Override
	protected void preExecute()
	{
		if(scene==null)
			return;
		
		if((role=scene.role.getRole(_playerID))==null)
			return;
		
		doExecute();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		
	}
	
}
