package com.home.commonCenter.net.serverRequest.game.social;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.role.RoleShowChangeData;
import com.home.commonCenter.net.serverRequest.game.base.CenterToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 刷新排行榜角色显示数据(generated by shine) */
public class RefreshRoleShowDataChangeToGameServerRequest extends CenterToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.RefreshRoleShowDataChangeToGame;
	
	/** 角色ID */
	public long playerID;
	
	/** 改变数据 */
	public RoleShowChangeData data;
	
	public RefreshRoleShowDataChangeToGameServerRequest()
	{
		_dataID=ServerMessageType.RefreshRoleShowDataChangeToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		RoleShowChangeData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(RoleShowChangeData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "RefreshRoleShowDataChangeToGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.playerID);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("playerID");
		writer.sb.append(':');
		writer.sb.append(this.playerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("RoleShowChangeData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.playerID=0L;
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static RefreshRoleShowDataChangeToGameServerRequest create(long playerID,RoleShowChangeData data)
	{
		RefreshRoleShowDataChangeToGameServerRequest re=(RefreshRoleShowDataChangeToGameServerRequest)BytesControl.createRequest(dataID);
		re.playerID=playerID;
		re.data=data;
		return re;
	}
	
}
