package com.home.commonCenter.net.serverRequest.game.social;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonCenter.net.serverRequest.game.base.CenterToGameServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** (generated by shine) */
public class SendGetRoleSocialDataToGameServerRequest extends CenterToGameServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.SendGetRoleSocialDataToGame;
	
	/** 来源角色ID */
	public long fromPlayerID;
	
	/** 目标玩家ID */
	public long targetPlayerID;
	
	/** 类型 */
	public int type;
	
	public SendGetRoleSocialDataToGameServerRequest()
	{
		_dataID=ServerMessageType.SendGetRoleSocialDataToGame;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "SendGetRoleSocialDataToGameServerRequest";
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeLong(this.fromPlayerID);
		
		stream.writeLong(this.targetPlayerID);
		
		stream.writeInt(this.type);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("fromPlayerID");
		writer.sb.append(':');
		writer.sb.append(this.fromPlayerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("targetPlayerID");
		writer.sb.append(':');
		writer.sb.append(this.targetPlayerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("type");
		writer.sb.append(':');
		writer.sb.append(this.type);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.fromPlayerID=0L;
		this.targetPlayerID=0L;
		this.type=0;
	}
	
	/** 创建实例 */
	public static SendGetRoleSocialDataToGameServerRequest create(long fromPlayerID,long targetPlayerID,int type)
	{
		SendGetRoleSocialDataToGameServerRequest re=(SendGetRoleSocialDataToGameServerRequest)BytesControl.createRequest(dataID);
		re.fromPlayerID=fromPlayerID;
		re.targetPlayerID=targetPlayerID;
		re.type=type;
		return re;
	}
	
}
