package com.home.commonBase.data.quest;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 成就完成数据(generated by shine) */
public class AchievementCompleteData extends BaseData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.AchievementComplete;
	
	/** id */
	public int id;
	
	/** 完成时间戳 */
	public long time;
	
	/** 是否领过奖励 */
	public boolean hasGotReward;
	
	public AchievementCompleteData()
	{
		_dataID=BaseDataType.AchievementComplete;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "AchievementCompleteData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.id=stream.readInt();
		
		this.time=stream.readLong();
		
		this.hasGotReward=stream.readBoolean();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeInt(this.id);
		
		stream.writeLong(this.time);
		
		stream.writeBoolean(this.hasGotReward);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		this.id=stream.readInt();
		
		this.time=stream.readLong();
		
		this.hasGotReward=stream.readBoolean();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeInt(this.id);
		
		stream.writeLong(this.time);
		
		stream.writeBoolean(this.hasGotReward);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		if(!(data instanceof AchievementCompleteData))
			return;
		
		AchievementCompleteData mData=(AchievementCompleteData)data;
		
		this.id=mData.id;
		this.time=mData.time;
		this.hasGotReward=mData.hasGotReward;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		if(!(data instanceof AchievementCompleteData))
			return;
		
		AchievementCompleteData mData=(AchievementCompleteData)data;
		
		this.id=mData.id;
		
		this.time=mData.time;
		
		this.hasGotReward=mData.hasGotReward;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		AchievementCompleteData mData=(AchievementCompleteData)data;
		if(this.id!=mData.id)
			return false;
		
		if(this.time!=mData.time)
			return false;
		
		if(this.hasGotReward!=mData.hasGotReward)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.append("id");
		writer.sb.append(':');
		writer.sb.append(this.id);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("time");
		writer.sb.append(':');
		writer.sb.append(this.time);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("hasGotReward");
		writer.sb.append(':');
		writer.sb.append(this.hasGotReward);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		this.id=0;
		this.time=0L;
		this.hasGotReward=false;
	}
	
}
