namespace Shine
{
	/** (generated by shine) */
	export class ClientLoginSelectResult extends BaseData
	{
		/** 数据类型ID */
		public static dataID:number=LoginHttpResponseResultType.ClientLoginSelect;
		
		public info:ClientLoginServerInfoData;
		
		constructor()
		{
			super();
			this._dataID=LoginHttpResponseResultType.ClientLoginSelect;
		}
		
		/** 读取字节流(完整版) */
		protected toReadBytesFull(stream:BytesReadStream):void
		{
			var position:number=BytesReadStream.getReadBytes(stream);
			
			this.info=stream.readDataFullNotNull() as ClientLoginServerInfoData;
			
			BytesReadStream.disReadBytes(stream,position);
		}
		
		/** 写入字节流(完整版) */
		protected toWriteBytesFull(stream:BytesWriteStream):void
		{
			var position:number=BytesWriteStream.getWriteBytes(stream);
			
			stream.writeDataFullNotNull(this.info);
			
			BytesWriteStream.disWriteBytes(stream,position);
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			this.info=stream.readDataSimpleNotNull() as ClientLoginServerInfoData;
			
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			stream.writeDataSimpleNotNull(this.info);
			
		}
		
	}
}
