package com.home.commonManager.net.serverRequest.login.system;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonManager.net.serverRequest.login.base.ManagerToLoginServerRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;

/** 关闭登录服消息(generated by shine) */
public class LoginExitServerRequest extends ManagerToLoginServerRequest
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.LoginExit;
	
	public LoginExitServerRequest()
	{
		_dataID=ServerMessageType.LoginExit;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "LoginExitServerRequest";
	}
	
	/** 创建实例 */
	public static LoginExitServerRequest create()
	{
		LoginExitServerRequest re=(LoginExitServerRequest)BytesControl.createRequest(dataID);
		return re;
	}
	
}
