package com.home.commonGame.net.request.role.munit;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 主单位消息基类(generated by shine) */
public class MUnitSRequest extends GameRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.MUnitS;
	
	/** 主单位序号 */
	public int mIndex;
	
	public MUnitSRequest()
	{
		_dataID=GameRequestType.MUnitS;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "MUnitSRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.mIndex);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.mIndex);
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("mIndex");
		writer.sb.append(':');
		writer.sb.append(this.mIndex);
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.mIndex=0;
	}
	
	/** 创建实例 */
	public static MUnitSRequest create(int mIndex)
	{
		MUnitSRequest re=(MUnitSRequest)BytesControl.createRequest(dataID);
		re.mIndex=mIndex;
		return re;
	}
	
}
