package com.home.commonGame.net.request.role.munit;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.base.GameRequest;
import com.home.commonGame.net.request.role.munit.MUnitSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 主角刷buff剩余次数(generated by shine) */
public class MUnitRefreshBuffLastNumRequest extends MUnitSRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.MUnitRefreshBuffLastNum;
	
	/** buff流水ID */
	public int instanceID;
	
	/** 剩余次数 */
	public int lastNum;
	
	public MUnitRefreshBuffLastNumRequest()
	{
		_dataID=GameRequestType.MUnitRefreshBuffLastNum;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "MUnitRefreshBuffLastNumRequest";
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("instanceID");
		writer.sb.append(':');
		writer.sb.append(this.instanceID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("lastNum");
		writer.sb.append(':');
		writer.sb.append(this.lastNum);
		
		writer.writeEnter();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.instanceID);
		
		stream.writeInt(this.lastNum);
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.instanceID);
		
		stream.writeInt(this.lastNum);
		
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.instanceID=0;
		this.lastNum=0;
	}
	
	/** 创建实例 */
	public static MUnitRefreshBuffLastNumRequest create(int mIndex,int instanceID,int lastNum)
	{
		MUnitRefreshBuffLastNumRequest re=(MUnitRefreshBuffLastNumRequest)BytesControl.createRequest(dataID);
		re.mIndex=mIndex;
		re.instanceID=instanceID;
		re.lastNum=lastNum;
		return re;
	}
	
}
