using ShineEngine;

/// <summary>
/// 建筑身份数据(generated by shine)
/// </summary>
public class BuildingIdentityData:FightUnitIdentityData
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=BaseDataType.BuildingIdentity;
	
	/// <summary>
	/// 建筑状态(见BuildingStateType)
	/// </summary>
	public int state;
	
	/// <summary>
	/// 建造/升级 经过时间
	/// </summary>
	public int passTime;
	
	public BuildingIdentityData()
	{
		_dataID=BaseDataType.BuildingIdentity;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "BuildingIdentityData";
	}
	
	/// <summary>
	/// 读取字节流(完整版)
	/// </summary>
	protected override void toReadBytesFull(BytesReadStream stream)
	{
		base.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.state=stream.readInt();
		
		this.passTime=stream.readInt();
		
		stream.endReadObj();
	}
	
	/// <summary>
	/// 写入字节流(完整版)
	/// </summary>
	protected override void toWriteBytesFull(BytesWriteStream stream)
	{
		base.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.state);
		
		stream.writeInt(this.passTime);
		
		stream.endWriteObj();
	}
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		base.toReadBytesSimple(stream);
		
		this.state=stream.readInt();
		
		this.passTime=stream.readInt();
		
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		stream.writeInt(this.state);
		
		stream.writeInt(this.passTime);
		
	}
	
	/// <summary>
	/// 复制(潜拷贝)
	/// </summary>
	protected override void toShadowCopy(BaseData data)
	{
		base.toShadowCopy(data);
		
		if(!(data is BuildingIdentityData))
			return;
		
		BuildingIdentityData mData=(BuildingIdentityData)data;
		
		this.state=mData.state;
		this.passTime=mData.passTime;
	}
	
	/// <summary>
	/// 复制(深拷贝)
	/// </summary>
	protected override void toCopy(BaseData data)
	{
		base.toCopy(data);
		
		if(!(data is BuildingIdentityData))
			return;
		
		BuildingIdentityData mData=(BuildingIdentityData)data;
		
		this.state=mData.state;
		
		this.passTime=mData.passTime;
		
	}
	
	/// <summary>
	/// 是否数据一致
	/// </summary>
	protected override bool toDataEquals(BaseData data)
	{
		if(!base.toDataEquals(data))
			return false;
		
		BuildingIdentityData mData=(BuildingIdentityData)data;
		if(this.state!=mData.state)
			return false;
		
		if(this.passTime!=mData.passTime)
			return false;
		
		return true;
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("state");
		writer.sb.Append(':');
		writer.sb.Append(this.state);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("passTime");
		writer.sb.Append(':');
		writer.sb.Append(this.passTime);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 初始化初值
	/// </summary>
	public override void initDefault()
	{
		base.initDefault();
		
	}
	
	/// <summary>
	/// 获取战斗单位ID
	/// </summary>
	public override int getFightUnitID()
	{
		return BuildingConfig.get(id).fightUnitID;
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		this.state=0;
		this.passTime=0;
	}
	
}
