package com.home.commonBase.data.social;
import com.home.commonBase.constlist.generate.BaseDataType;
import com.home.commonBase.data.func.FuncToolData;
import com.home.commonBase.data.social.RoleSocialPoolData;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.data.BaseData;
import com.home.shine.support.DataWriter;
import com.home.shine.support.collection.LongObjectMap;
import com.home.shine.support.pool.DataPool;

/** 角色社交数据池工具数据(generated by shine) */
public class RoleSocialPoolToolData extends FuncToolData
{
	/** 数据类型ID */
	public static final int dataID=BaseDataType.RoleSocialPoolTool;
	
	/** 数据 */
	public LongObjectMap<RoleSocialPoolData> dic;
	
	/** 下次裁剪 */
	public long nextCutTime;
	
	public RoleSocialPoolToolData()
	{
		_dataID=BaseDataType.RoleSocialPoolTool;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "RoleSocialPoolToolData";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		int dicLen=stream.readLen();
		if(this.dic!=null)
		{
			this.dic.clear();
			this.dic.ensureCapacity(dicLen);
		}
		else
		{
			this.dic=new LongObjectMap<RoleSocialPoolData>(RoleSocialPoolData[]::new,dicLen);
		}
		
		LongObjectMap<RoleSocialPoolData> dicT=this.dic;
		for(int dicI=dicLen-1;dicI>=0;--dicI)
		{
			long dicK;
			RoleSocialPoolData dicV;
			dicK=stream.readLong();
			
			BaseData dicVT=stream.readDataFullNotNull();
			if(dicVT!=null)
			{
				if(dicVT instanceof RoleSocialPoolData)
				{
					dicV=(RoleSocialPoolData)dicVT;
				}
				else
				{
					dicV=new RoleSocialPoolData();
					if(!(dicVT.getClass().isAssignableFrom(RoleSocialPoolData.class)))
					{
						stream.throwTypeReadError(RoleSocialPoolData.class,dicVT.getClass());
					}
					dicV.shadowCopy(dicVT);
				}
			}
			else
			{
				dicV=null;
			}
			
			dicT.put(dicK,dicV);
		}
		
		this.nextCutTime=stream.readLong();
		
		stream.endReadObj();
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		if(this.dic!=null)
		{
			stream.writeLen(this.dic.size());
			if(!this.dic.isEmpty())
			{
				long dicKFreeValue=this.dic.getFreeValue();
				long[] dicKKeys=this.dic.getKeys();
				Object[] dicVValues=this.dic.getValues();
				for(int dicKI=dicKKeys.length-1;dicKI>=0;--dicKI)
				{
					long dicK=dicKKeys[dicKI];
					if(dicK!=dicKFreeValue)
					{
						RoleSocialPoolData dicV=(RoleSocialPoolData)dicVValues[dicKI];
						stream.writeLong(dicK);
						
						if(dicV!=null)
						{
							stream.writeDataFullNotNull(dicV);
						}
						else
						{
							nullObjError("dicV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("dic");
		}
		
		stream.writeLong(this.nextCutTime);
		
		stream.endWriteObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		int dicLen=stream.readLen();
		if(this.dic!=null)
		{
			this.dic.clear();
			this.dic.ensureCapacity(dicLen);
		}
		else
		{
			this.dic=new LongObjectMap<RoleSocialPoolData>(RoleSocialPoolData[]::new,dicLen);
		}
		
		LongObjectMap<RoleSocialPoolData> dicT=this.dic;
		for(int dicI=dicLen-1;dicI>=0;--dicI)
		{
			long dicK;
			RoleSocialPoolData dicV;
			dicK=stream.readLong();
			
			dicV=(RoleSocialPoolData)stream.readDataSimpleNotNull();
			
			dicT.put(dicK,dicV);
		}
		
		this.nextCutTime=stream.readLong();
		
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		if(this.dic!=null)
		{
			stream.writeLen(this.dic.size());
			if(!this.dic.isEmpty())
			{
				long dicKFreeValue=this.dic.getFreeValue();
				long[] dicKKeys=this.dic.getKeys();
				Object[] dicVValues=this.dic.getValues();
				for(int dicKI=dicKKeys.length-1;dicKI>=0;--dicKI)
				{
					long dicK=dicKKeys[dicKI];
					if(dicK!=dicKFreeValue)
					{
						RoleSocialPoolData dicV=(RoleSocialPoolData)dicVValues[dicKI];
						stream.writeLong(dicK);
						
						if(dicV!=null)
						{
							stream.writeDataSimpleNotNull(dicV);
						}
						else
						{
							nullObjError("dicV");
						}
						
					}
				}
			}
		}
		else
		{
			nullObjError("dic");
		}
		
		stream.writeLong(this.nextCutTime);
		
	}
	
	/** 复制(潜拷贝) */
	@Override
	protected void toShadowCopy(BaseData data)
	{
		super.toShadowCopy(data);
		
		if(!(data instanceof RoleSocialPoolToolData))
			return;
		
		RoleSocialPoolToolData mData=(RoleSocialPoolToolData)data;
		
		this.dic=mData.dic;
		this.nextCutTime=mData.nextCutTime;
	}
	
	/** 复制(深拷贝) */
	@Override
	protected void toCopy(BaseData data)
	{
		super.toCopy(data);
		
		if(!(data instanceof RoleSocialPoolToolData))
			return;
		
		RoleSocialPoolToolData mData=(RoleSocialPoolToolData)data;
		
		if(mData.dic!=null)
		{
			if(this.dic!=null)
			{
				this.dic.clear();
				this.dic.ensureCapacity(mData.dic.size());
			}
			else
			{
				this.dic=new LongObjectMap<RoleSocialPoolData>(RoleSocialPoolData[]::new,mData.dic.size());
			}
			
			LongObjectMap<RoleSocialPoolData> dicT=this.dic;
			if(!mData.dic.isEmpty())
			{
				long dicKFreeValue=mData.dic.getFreeValue();
				long[] dicKKeys=mData.dic.getKeys();
				Object[] dicVValues=mData.dic.getValues();
				for(int dicKI=dicKKeys.length-1;dicKI>=0;--dicKI)
				{
					long dicK=dicKKeys[dicKI];
					if(dicK!=dicKFreeValue)
					{
						RoleSocialPoolData dicV=(RoleSocialPoolData)dicVValues[dicKI];
						long dicW;
						RoleSocialPoolData dicU;
						dicW=dicK;
						
						if(dicV!=null)
						{
							dicU=(RoleSocialPoolData)dicV.clone();
						}
						else
						{
							dicU=null;
							nullObjError("dicU");
						}
						
						dicT.put(dicW,dicU);
					}
				}
			}
		}
		else
		{
			this.dic=null;
			nullObjError("dic");
		}
		
		this.nextCutTime=mData.nextCutTime;
		
	}
	
	/** 是否数据一致 */
	@Override
	protected boolean toDataEquals(BaseData data)
	{
		if(!super.toDataEquals(data))
			return false;
		
		RoleSocialPoolToolData mData=(RoleSocialPoolToolData)data;
		if(mData.dic!=null)
		{
			if(this.dic==null)
				return false;
			if(this.dic.size()!=mData.dic.size())
				return false;
			LongObjectMap<RoleSocialPoolData> dicR=mData.dic;
			if(!this.dic.isEmpty())
			{
				long dicKFreeValue=this.dic.getFreeValue();
				long[] dicKKeys=this.dic.getKeys();
				Object[] dicVValues=this.dic.getValues();
				for(int dicKI=dicKKeys.length-1;dicKI>=0;--dicKI)
				{
					long dicK=dicKKeys[dicKI];
					if(dicK!=dicKFreeValue)
					{
						RoleSocialPoolData dicV=(RoleSocialPoolData)dicVValues[dicKI];
						RoleSocialPoolData dicU=dicR.get(dicK);
						if(dicU!=null)
						{
							if(dicV==null)
								return false;
							if(!dicV.dataEquals(dicU))
								return false;
						}
						else
						{
							if(dicV!=null)
								return false;
						}
						
					}
				}
			}
		}
		else
		{
			if(this.dic!=null)
				return false;
		}
		
		if(this.nextCutTime!=mData.nextCutTime)
			return false;
		
		return true;
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("dic");
		writer.sb.append(':');
		writer.sb.append("Map<long,RoleSocialPoolData>");
		if(this.dic!=null)
		{
			writer.sb.append('(');
			writer.sb.append(this.dic.size());
			writer.sb.append(')');
			writer.writeEnter();
			writer.writeLeftBrace();
			if(!this.dic.isEmpty())
			{
				long dicKFreeValue=this.dic.getFreeValue();
				long[] dicKKeys=this.dic.getKeys();
				Object[] dicVValues=this.dic.getValues();
				for(int dicKI=dicKKeys.length-1;dicKI>=0;--dicKI)
				{
					long dicK=dicKKeys[dicKI];
					if(dicK!=dicKFreeValue)
					{
						RoleSocialPoolData dicV=(RoleSocialPoolData)dicVValues[dicKI];
						writer.writeTabs();
						writer.sb.append(dicK);
						
						writer.sb.append(':');
						if(dicV!=null)
						{
							dicV.writeDataString(writer);
						}
						else
						{
							writer.sb.append("RoleSocialPoolData=null");
						}
						
						writer.writeEnter();
					}
				}
			}
			writer.writeRightBrace();
		}
		else
		{
			writer.sb.append("=null");
		}
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("nextCutTime");
		writer.sb.append(':');
		writer.sb.append(this.nextCutTime);
		
		writer.writeEnter();
	}
	
	/** 初始化初值 */
	@Override
	public void initDefault()
	{
		super.initDefault();
		
		this.dic=new LongObjectMap<RoleSocialPoolData>(RoleSocialPoolData[]::new);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.dic=null;
		this.nextCutTime=0L;
	}
	
}
