package com.home.commonGame.net.request.func.item;
import com.home.commonBase.data.item.ItemData;
import com.home.commonGame.constlist.generate.GameRequestType;
import com.home.commonGame.net.request.func.base.FuncSRequest;
import com.home.shine.bytes.BytesWriteStream;
import com.home.shine.control.BytesControl;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 穿装备(generated by shine) */
public class FuncSendPutOnEquipRequest extends FuncSRequest
{
	/** 数据类型ID */
	public static final int dataID=GameRequestType.FuncSendPutOnEquip;
	
	/** 槽位 */
	public int slot;
	
	/** 数据 */
	public ItemData data;
	
	public FuncSendPutOnEquipRequest()
	{
		_dataID=GameRequestType.FuncSendPutOnEquip;
	}
	
	@Override
	protected void copyData()
	{
		super.copyData();
		ItemData dataTemp=data;
		if(dataTemp!=null)
		{
			this.data=(ItemData)dataTemp.clone();
		}
		else
		{
			this.data=null;
			nullObjError("data");
		}
		
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendPutOnEquipRequest";
	}
	
	/** 写入字节流(完整版) */
	@Override
	protected void toWriteBytesFull(BytesWriteStream stream)
	{
		super.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.slot);
		
		if(this.data!=null)
		{
			stream.writeDataFullNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
		stream.endWriteObj();
	}
	
	/** 写入字节流(简版) */
	@Override
	protected void toWriteBytesSimple(BytesWriteStream stream)
	{
		super.toWriteBytesSimple(stream);
		
		stream.writeInt(this.slot);
		
		if(this.data!=null)
		{
			stream.writeDataSimpleNotNull(this.data);
		}
		else
		{
			nullObjError("data");
		}
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("slot");
		writer.sb.append(':');
		writer.sb.append(this.slot);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("data");
		writer.sb.append(':');
		if(this.data!=null)
		{
			this.data.writeDataString(writer);
		}
		else
		{
			writer.sb.append("ItemData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.slot=0;
		this.data.release(pool);
		this.data=null;
	}
	
	/** 创建实例 */
	public static FuncSendPutOnEquipRequest create(int funcID,int slot,ItemData data)
	{
		FuncSendPutOnEquipRequest re=(FuncSendPutOnEquipRequest)BytesControl.createRequest(dataID);
		re.funcID=funcID;
		re.slot=slot;
		re.data=data;
		return re;
	}
	
}
