using ShineEngine;

/// <summary>
/// 拍卖行临时购买物品数据(generated by shine)
/// </summary>
public class AuctionBuyItemData:BaseData
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=BaseDataType.AuctionBuyItem;
	
	public long instanceID;
	
	public int itemID;
	
	public int num;
	
	public int price;
	
	public AuctionBuyItemData()
	{
		_dataID=BaseDataType.AuctionBuyItem;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "AuctionBuyItemData";
	}
	
	/// <summary>
	/// 读取字节流(完整版)
	/// </summary>
	protected override void toReadBytesFull(BytesReadStream stream)
	{
		stream.startReadObj();
		
		this.instanceID=stream.readLong();
		
		this.itemID=stream.readInt();
		
		this.num=stream.readInt();
		
		this.price=stream.readInt();
		
		stream.endReadObj();
	}
	
	/// <summary>
	/// 写入字节流(完整版)
	/// </summary>
	protected override void toWriteBytesFull(BytesWriteStream stream)
	{
		stream.startWriteObj();
		
		stream.writeLong(this.instanceID);
		
		stream.writeInt(this.itemID);
		
		stream.writeInt(this.num);
		
		stream.writeInt(this.price);
		
		stream.endWriteObj();
	}
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		this.instanceID=stream.readLong();
		
		this.itemID=stream.readInt();
		
		this.num=stream.readInt();
		
		this.price=stream.readInt();
		
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		stream.writeLong(this.instanceID);
		
		stream.writeInt(this.itemID);
		
		stream.writeInt(this.num);
		
		stream.writeInt(this.price);
		
	}
	
	/// <summary>
	/// 复制(潜拷贝)
	/// </summary>
	protected override void toShadowCopy(BaseData data)
	{
		if(!(data is AuctionBuyItemData))
			return;
		
		AuctionBuyItemData mData=(AuctionBuyItemData)data;
		
		this.instanceID=mData.instanceID;
		this.itemID=mData.itemID;
		this.num=mData.num;
		this.price=mData.price;
	}
	
	/// <summary>
	/// 复制(深拷贝)
	/// </summary>
	protected override void toCopy(BaseData data)
	{
		if(!(data is AuctionBuyItemData))
			return;
		
		AuctionBuyItemData mData=(AuctionBuyItemData)data;
		
		this.instanceID=mData.instanceID;
		
		this.itemID=mData.itemID;
		
		this.num=mData.num;
		
		this.price=mData.price;
		
	}
	
	/// <summary>
	/// 是否数据一致
	/// </summary>
	protected override bool toDataEquals(BaseData data)
	{
		AuctionBuyItemData mData=(AuctionBuyItemData)data;
		if(this.instanceID!=mData.instanceID)
			return false;
		
		if(this.itemID!=mData.itemID)
			return false;
		
		if(this.num!=mData.num)
			return false;
		
		if(this.price!=mData.price)
			return false;
		
		return true;
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		writer.writeTabs();
		writer.sb.Append("instanceID");
		writer.sb.Append(':');
		writer.sb.Append(this.instanceID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("itemID");
		writer.sb.Append(':');
		writer.sb.Append(this.itemID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("num");
		writer.sb.Append(':');
		writer.sb.Append(this.num);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("price");
		writer.sb.Append(':');
		writer.sb.Append(this.price);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 初始化初值
	/// </summary>
	public override void initDefault()
	{
		
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		this.instanceID=0L;
		this.itemID=0;
		this.num=0;
		this.price=0;
	}
	
}
