using ShineEngine;

/// <summary>
/// 整形拍卖行查询条件(generated by shine)
/// </summary>
public class IntAuctionQueryConditionData:AuctionQueryConditionData
{
	/// <summary>
	/// 数据类型ID
	/// </summary>
	public const int dataID=BaseDataType.IntAuctionQueryCondition;
	
	/// <summary>
	/// 下限(如相等，则用等号)
	/// </summary>
	public int min;
	
	/// <summary>
	/// 上限
	/// </summary>
	public int max;
	
	public IntAuctionQueryConditionData()
	{
		_dataID=BaseDataType.IntAuctionQueryCondition;
	}
	
	/// <summary>
	/// 获取数据类名
	/// </summary>
	public override string getDataClassName()
	{
		return "IntAuctionQueryConditionData";
	}
	
	/// <summary>
	/// 读取字节流(完整版)
	/// </summary>
	protected override void toReadBytesFull(BytesReadStream stream)
	{
		base.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.min=stream.readInt();
		
		this.max=stream.readInt();
		
		stream.endReadObj();
	}
	
	/// <summary>
	/// 写入字节流(完整版)
	/// </summary>
	protected override void toWriteBytesFull(BytesWriteStream stream)
	{
		base.toWriteBytesFull(stream);
		
		stream.startWriteObj();
		
		stream.writeInt(this.min);
		
		stream.writeInt(this.max);
		
		stream.endWriteObj();
	}
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		base.toReadBytesSimple(stream);
		
		this.min=stream.readInt();
		
		this.max=stream.readInt();
		
	}
	
	/// <summary>
	/// 写入字节流(简版)
	/// </summary>
	protected override void toWriteBytesSimple(BytesWriteStream stream)
	{
		base.toWriteBytesSimple(stream);
		
		stream.writeInt(this.min);
		
		stream.writeInt(this.max);
		
	}
	
	/// <summary>
	/// 复制(潜拷贝)
	/// </summary>
	protected override void toShadowCopy(BaseData data)
	{
		base.toShadowCopy(data);
		
		if(!(data is IntAuctionQueryConditionData))
			return;
		
		IntAuctionQueryConditionData mData=(IntAuctionQueryConditionData)data;
		
		this.min=mData.min;
		this.max=mData.max;
	}
	
	/// <summary>
	/// 复制(深拷贝)
	/// </summary>
	protected override void toCopy(BaseData data)
	{
		base.toCopy(data);
		
		if(!(data is IntAuctionQueryConditionData))
			return;
		
		IntAuctionQueryConditionData mData=(IntAuctionQueryConditionData)data;
		
		this.min=mData.min;
		
		this.max=mData.max;
		
	}
	
	/// <summary>
	/// 是否数据一致
	/// </summary>
	protected override bool toDataEquals(BaseData data)
	{
		if(!base.toDataEquals(data))
			return false;
		
		IntAuctionQueryConditionData mData=(IntAuctionQueryConditionData)data;
		if(this.min!=mData.min)
			return false;
		
		if(this.max!=mData.max)
			return false;
		
		return true;
	}
	
	/// <summary>
	/// 转文本输出
	/// </summary>
	protected override void toWriteDataString(DataWriter writer)
	{
		base.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.Append("min");
		writer.sb.Append(':');
		writer.sb.Append(this.min);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.Append("max");
		writer.sb.Append(':');
		writer.sb.Append(this.max);
		
		writer.writeEnter();
	}
	
	/// <summary>
	/// 初始化初值
	/// </summary>
	public override void initDefault()
	{
		base.initDefault();
		
	}
	
	/// <summary>
	/// 回池
	/// </summary>
	protected override void toRelease(DataPool pool)
	{
		base.toRelease(pool);
		
		this.min=0;
		this.max=0;
	}
	
}
