package com.home.commonGame.net.response.func.aution;
import com.home.commonGame.constlist.generate.GameResponseType;
import com.home.commonGame.global.GameC;
import com.home.commonGame.net.request.func.auction.FuncReGetAuctionItemSuggestPriceRequest;
import com.home.commonGame.net.response.func.base.FuncRResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 获取拍卖行物品推荐价格(generated by shine) */
public class FuncGetAuctionItemSuggestPriceResponse extends FuncRResponse
{
	/** 数据类型ID */
	public static final int dataID=GameResponseType.FuncGetAuctionItemSuggestPrice;
	
	public int itemID;
	
	public FuncGetAuctionItemSuggestPriceResponse()
	{
		_dataID=GameResponseType.FuncGetAuctionItemSuggestPrice;
		setUseMainThread();
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncGetAuctionItemSuggestPriceResponse";
	}
	
	/** 读取字节流(完整版) */
	@Override
	protected void toReadBytesFull(BytesReadStream stream)
	{
		super.toReadBytesFull(stream);
		
		stream.startReadObj();
		
		this.itemID=stream.readInt();
		
		stream.endReadObj();
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.itemID=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("itemID");
		writer.sb.append(':');
		writer.sb.append(this.itemID);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		int itemPrice=GameC.global.func.getAuctionToolBase(funcID).getItemPrice(itemID);
		
		//直接回复
		FuncReGetAuctionItemSuggestPriceRequest.create(funcID,itemID,itemPrice).sendToPlayer(me.role.playerID);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.itemID=0;
	}
	
}
