namespace Shine
{
	/** 单位简版数据(只位置,血量,身份)(generated by shine) */
	export class UnitSimpleData extends BaseData
	{
		/** 数据类型ID */
		public static dataID:number=BaseDataType.UnitSimple;
		
		/** 流水ID */
		public instanceID:number;
		
		/** 身份数据 */
		public identity:UnitIdentityData;
		
		/** 位置数据 */
		public pos:UnitPosData;
		
		/** 属性组(血量) */
		public attributes:SMap<number,number>;
		
		constructor()
		{
			super();
			this._dataID=BaseDataType.UnitSimple;
		}
		
		/** 读取字节流(简版) */
		protected toReadBytesSimple(stream:BytesReadStream):void
		{
			this.instanceID=stream.readInt();
			
			this.identity=stream.readDataSimpleNotNull() as UnitIdentityData;
			
			if(stream.readBoolean())
			{
				this.pos=stream.readDataSimpleNotNull() as UnitPosData;
			}
			else
			{
				this.pos=null;
			}
			
			var attributesLen:number=stream.readLen();
			if(this.attributes!=null)
			{
				this.attributes.clear();
				this.attributes.ensureCapacity(attributesLen);
			}
			else
			{
				this.attributes=new SMap<number,number>(attributesLen);
			}
			
			var attributesT:SMap<number,number>=this.attributes;
			for(var attributesI:number=attributesLen-1;attributesI>=0;--attributesI)
			{
				var attributesK:number;
				var attributesV:number;
				attributesK=stream.readInt();
				
				attributesV=stream.readInt();
				
				attributesT.put(attributesK,attributesV);
			}
			
		}
		
		/** 写入字节流(简版) */
		protected toWriteBytesSimple(stream:BytesWriteStream):void
		{
			stream.writeInt(this.instanceID);
			
			stream.writeDataSimpleNotNull(this.identity);
			
			if(this.pos!=null)
			{
				stream.writeBoolean(true);
				stream.writeDataSimpleNotNull(this.pos);
			}
			else
			{
				stream.writeBoolean(false);
			}
			
			stream.writeLen(this.attributes.size());
			if(!this.attributes.isEmpty())
			{
				for(var attributesK of this.attributes.getKeys())
				{
					var attributesV:number=this.attributes.get(attributesK);
					stream.writeInt(attributesK);
					
					stream.writeInt(attributesV);
					
				}
			}
			
		}
		
		/** 复制(潜拷贝) */
		protected toShadowCopy(data:BaseData):void
		{
			if(!(data instanceof UnitSimpleData))
				return;
			
			var mData:UnitSimpleData=data as UnitSimpleData;
			
			this.instanceID=mData.instanceID;
			this.identity=mData.identity;
			this.pos=mData.pos;
			this.attributes=mData.attributes;
		}
		
		/** 复制(深拷贝) */
		protected toCopy(data:BaseData):void
		{
			if(!(data instanceof UnitSimpleData))
				return;
			
			var mData:UnitSimpleData=data as UnitSimpleData;
			
			this.instanceID=mData.instanceID;
			
			this.identity=mData.identity.clone() as UnitIdentityData;
			
			if(mData.pos!=null)
			{
				this.pos=mData.pos.clone() as UnitPosData;
			}
			else
			{
				this.pos=null;
			}
			
			if(this.attributes!=null)
			{
				this.attributes.clear();
				this.attributes.ensureCapacity(mData.attributes.size());
			}
			else
			{
				this.attributes=new SMap<number,number>(mData.attributes.size());
			}
			
			var attributesT:SMap<number,number>=this.attributes;
			if(!mData.attributes.isEmpty())
			{
				for(var attributesK of mData.attributes.getKeys())
				{
					var attributesV:number=mData.attributes.get(attributesK);
					var attributesW:number;
					var attributesU:number;
					attributesW=attributesK;
					
					attributesU=attributesV;
					
					attributesT.put(attributesW,attributesU);
				}
			}
			
		}
		
		/** 初始化初值 */
		public initDefault():void
		{
			this.identity=new UnitIdentityData();
			this.identity.initDefault();
			this.attributes=new SMap<number,number>();
		}
		
	}
}
