package com.home.shine.tool.generate;
import com.home.shine.constlist.generate.ShineRequestType;
import com.home.shine.constlist.generate.ShineResponseType;
import com.home.shine.tool.MessageBindTool;

/** (generated by shine) */
public class ShineResponseBindTool extends MessageBindTool
{
	public ShineResponseBindTool()
	{
		offSet=ShineResponseType.off;
		list=new int[ShineResponseType.count-offSet][];
	}
	
}
