package com.home.commonGame.net.serverResponse.game.func.roleGroup;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.global.GameC;
import com.home.commonGame.net.serverResponse.game.func.base.FuncToGameServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 移除玩家群简版信息到其他逻辑服(generated by shine) */
public class FuncRemoveRoleGroupSimpleToGameServerResponse extends FuncToGameServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncRemoveRoleGroupSimpleToGame;
	
	public long groupID;
	
	public FuncRemoveRoleGroupSimpleToGameServerResponse()
	{
		_dataID=ServerMessageType.FuncRemoveRoleGroupSimpleToGame;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncRemoveRoleGroupSimpleToGameServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.groupID=stream.readLong();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("groupID");
		writer.sb.append(':');
		writer.sb.append(this.groupID);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		GameC.global.func.getRoleGroupTool(funcID).removeGameRoleGroupSimpleData(groupID);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.groupID=0L;
	}
	
}
