package com.home.commonGame.net.serverResponse.game.func.roleGroup;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonBase.data.scene.scene.SceneLocationData;
import com.home.commonGame.net.serverResponse.game.func.base.FuncPlayerRoleGroupGameToGameServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 回复玩家群进入专属场景参数消息(generated by shine) */
public class FuncRoleGroupReEnterOwnSceneArgToPlayerServerResponse extends FuncPlayerRoleGroupGameToGameServerResponse
{
	/** 场景进入参数 */
	public SceneLocationData location;
	
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncRoleGroupReEnterOwnSceneArgToPlayer;
	
	public FuncRoleGroupReEnterOwnSceneArgToPlayerServerResponse()
	{
		_dataID=ServerMessageType.FuncRoleGroupReEnterOwnSceneArgToPlayer;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncRoleGroupReEnterOwnSceneArgToPlayerServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.location=(SceneLocationData)stream.readDataSimpleNotNull();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("location");
		writer.sb.append(':');
		if(this.location!=null)
		{
			this.location.writeDataString(writer);
		}
		else
		{
			writer.sb.append("SceneLocationData=null");
		}
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		roleGroup.onReEnterOwnScene(location);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.location=null;
	}
	
}
