package com.home.commonGame.net.serverResponse.game.func.roleGroup;
import com.home.commonBase.constlist.generate.ServerMessageType;
import com.home.commonGame.net.serverResponse.game.func.base.FuncPlayerRoleGroupGameToGameServerResponse;
import com.home.shine.bytes.BytesReadStream;
import com.home.shine.support.DataWriter;
import com.home.shine.support.pool.DataPool;

/** 玩家群移除成员(generated by shine) */
public class FuncSendRoleGroupRemoveMemberToPlayerServerResponse extends FuncPlayerRoleGroupGameToGameServerResponse
{
	/** 数据类型ID */
	public static final int dataID=ServerMessageType.FuncSendRoleGroupRemoveMemberToPlayer;
	
	/** 方式 */
	public int type;
	
	/** 成员id */
	public long playerID;
	
	public FuncSendRoleGroupRemoveMemberToPlayerServerResponse()
	{
		_dataID=ServerMessageType.FuncSendRoleGroupRemoveMemberToPlayer;
	}
	
	/** 获取数据类名 */
	@Override
	public String getDataClassName()
	{
		return "FuncSendRoleGroupRemoveMemberToPlayerServerResponse";
	}
	
	/** 读取字节流(简版) */
	@Override
	protected void toReadBytesSimple(BytesReadStream stream)
	{
		super.toReadBytesSimple(stream);
		
		this.playerID=stream.readLong();
		
		this.type=stream.readInt();
		
	}
	
	/** 转文本输出 */
	@Override
	protected void toWriteDataString(DataWriter writer)
	{
		super.toWriteDataString(writer);
		
		writer.writeTabs();
		writer.sb.append("playerID");
		writer.sb.append(':');
		writer.sb.append(this.playerID);
		
		writer.writeEnter();
		writer.writeTabs();
		writer.sb.append("type");
		writer.sb.append(':');
		writer.sb.append(this.type);
		
		writer.writeEnter();
	}
	
	/** 执行 */
	@Override
	protected void execute()
	{
		roleGroup.onRemoveMember(playerID,type);
	}
	
	/** 回池 */
	@Override
	protected void toRelease(DataPool pool)
	{
		super.toRelease(pool);
		
		this.playerID=0L;
		this.type=0;
	}
	
}
