using ShineEngine;

/// <summary>
/// 全局配置表(generated by shine)
/// </summary>
[Hotfix]
public class GlobalReadData:BaseData
{
	/// <summary>
	/// 每个账号一个区服可拥有的角色数目(合服不影响每个被合区服的拥有角色数目)
	/// </summary>
	public int ownPlayerNum;
	
	/// <summary>
	/// 角色名字上限数目(机器字)
	/// </summary>
	public int playerNameLength;
	
	/// <summary>
	/// 角色名字是否使用区服ID作为前缀,如(s1.张三)
	/// </summary>
	public bool isNameUseAreaIDAsFront;
	
	/// <summary>
	/// 角色名字是否可以重名
	/// </summary>
	public bool canPlayerNameRepeat;
	
	/// <summary>
	/// 客户端离线事务，每日可修改时间的次数
	/// </summary>
	public int clientOfflineWorkTimeChangeDailyNum;
	
	/// <summary>
	/// 显示网络延迟圈圈最大超时时间(ms)
	/// </summary>
	public int showNetDelayMaxTime;
	
	/// <summary>
	/// 显示网络延迟圈圈最小间隔(ms)
	/// </summary>
	public int showNetDelayMinTime;
	
	/// <summary>
	/// 激活码长度
	/// </summary>
	public int activationCodeLength;
	
	/// <summary>
	/// 激活码是否使用批次(每批次每个玩家只能用一次)
	/// </summary>
	public bool activationCodeUseBatch;
	
	/// <summary>
	/// 游戏信息日志保留时间(玩家自身)(day)
	/// </summary>
	public int infoLogKeepTime;
	
	/// <summary>
	/// 游戏信息日志保留数目(玩家自身)
	/// </summary>
	public int infoLogKeepNum;
	
	/// <summary>
	/// 翻页显示插件每页CD(s)
	/// </summary>
	public int pageToolShowCD;
	
	/// <summary>
	/// 大Float数字每段位数(3为千,4为万)
	/// </summary>
	public int bigFloatWei;
	
	/// <summary>
	/// 坐标推送缩放比率
	/// </summary>
	public float posSendScale;
	
	/// <summary>
	/// 朝向推送缩放比率
	/// </summary>
	public float directionSendScale;
	
	/// <summary>
	/// 保持当前属性百分比在上限改变前(否则就是保持当前值不变)
	/// </summary>
	public bool keepCurrentPercentAtMaxChange;
	
	/// <summary>
	/// 单位转身XY和最小值(小于此值不转身)
	/// </summary>
	public float unitTurnXYSumMin;
	
	/// <summary>
	/// 单位移动XY和的最大允许误差(超过此值即拉回)
	/// </summary>
	public float unitMovePosMaxDeviation;
	
	/// <summary>
	/// 距离验证允许误差
	/// </summary>
	public float distanceCheckDeviation;
	
	/// <summary>
	/// 移动速度最小值
	/// </summary>
	public int moveSpeedMin;
	
	/// <summary>
	/// 移动速度最大值
	/// </summary>
	public int moveSpeedMax;
	
	/// <summary>
	/// 攻击速度最小值
	/// </summary>
	public int attackSpeedMin;
	
	/// <summary>
	/// 攻击速度最大值
	/// </summary>
	public int attackSpeedMax;
	
	/// <summary>
	/// 施法速度最小值
	/// </summary>
	public int castSpeedMin;
	
	/// <summary>
	/// 施法速度最大值
	/// </summary>
	public int castSpeedMax;
	
	/// <summary>
	/// 使用移动速度比率(使用值=数值*比率)(每秒多少米)
	/// </summary>
	public float useMoveSpeedRatio;
	
	/// <summary>
	/// 命中公式参数0(基础命中率)
	/// </summary>
	public float hitRateArg0;
	
	/// <summary>
	/// 暴击公式参数0(基础暴击率)
	/// </summary>
	public float critArg0;
	
	/// <summary>
	/// 暴击默认伤害比率
	/// </summary>
	public float critDamageBaseRatio;
	
	/// <summary>
	/// 子弹最长保留时间(s)
	/// </summary>
	public int bulletMaxLastTime;
	
	/// <summary>
	/// 场景保留时间(s)
	/// </summary>
	public int sceneKeepTime;
	
	/// <summary>
	/// 攻击范围背向延伸距离(米)
	/// </summary>
	public float attackScopeBackLength;
	
	/// <summary>
	/// 攻击范围默认攻击高度(米)
	/// </summary>
	public float attackScopeDefaultHeight;
	
	/// <summary>
	/// 默认显示帧率
	/// </summary>
	public float defaultShowFps;
	
	/// <summary>
	/// 帧同步缓存帧数
	/// </summary>
	public int frameSyncCacheFrames;
	
	/// <summary>
	/// 徘徊等待时间最小值(s)
	/// </summary>
	public int wanderWaitTimeMin;
	
	/// <summary>
	/// 徘徊等待时间最大值(s)
	/// </summary>
	public int wanderWaitTimeMax;
	
	/// <summary>
	/// 徘徊移动半径(米)
	/// </summary>
	public float wanderMoveRadius;
	
	/// <summary>
	/// 阻止网络延迟时间(ms)
	/// </summary>
	public int preventNetDelayTime;
	
	/// <summary>
	/// 场景分线数目(仅在sceneLinePlayerLimitNum为0时有意义)
	/// </summary>
	public int sceneLineNum;
	
	/// <summary>
	/// 客户端移动消息发送最短间隔(ms)
	/// </summary>
	public int clientMoveSendMinDelay;
	
	/// <summary>
	/// 朝向移动预测最短距离(米)
	/// </summary>
	public float moveDirForecastMinDistance;
	
	/// <summary>
	/// 朝向移动预测时间(ms)
	/// </summary>
	public int moveDirForecastTime;
	
	/// <summary>
	/// 朝向移动预测发送消息间隔(ms)
	/// </summary>
	public int moveDirSendDelay;
	
	/// <summary>
	/// 地图阻挡尺寸(米)
	/// </summary>
	public float mapBlockSize;
	
	/// <summary>
	/// 怪物退回时每秒回血千分比
	/// </summary>
	public int monsterBackAddHPPercent;
	
	/// <summary>
	/// 地图SamplePosition半径(米)
	/// </summary>
	public float mapSamplePositionRadius;
	
	/// <summary>
	/// 光环buff更新时间(ms)
	/// </summary>
	public int ringLightBuffRefreshTime;
	
	/// <summary>
	/// 光环buff单次持续时间(ms)
	/// </summary>
	public int ringLightBuffLastTime;
	
	/// <summary>
	/// 唤醒同伴间隔时间(ms)
	/// </summary>
	public int wakeUpCompanionDelayTime;
	
	/// <summary>
	/// 战斗状态单次持续时间(ms)
	/// </summary>
	public int fightStateOnceLastTime;
	
	/// <summary>
	/// 出生主城ID
	/// </summary>
	public int bornTownID;
	
	/// <summary>
	/// 场景分线角色限制数目(当此值大于0时,视为启用按人数分线策略,并且sceenLineNum值无效)
	/// </summary>
	public int sceneLinePlayerLimitNum;
	
	/// <summary>
	/// 单位AI受击判定最短间隔(ms)
	/// </summary>
	public int unitBeAttackDelay;
	
	/// <summary>
	/// 单位切换基础成本
	/// </summary>
	public float unitSwitchFixedCost;
	
	/// <summary>
	/// 单位切换基础距离
	/// </summary>
	public float unitSwitchBaseDistance;
	
	/// <summary>
	/// 单位切换距离成本系数
	/// </summary>
	public float unitSwitchDistanceCost;
	
	/// <summary>
	/// 单位切换仇恨成本系数
	/// </summary>
	public float unitSwitchHateCost;
	
	/// <summary>
	/// 单位仇恨伤害千分比系数
	/// </summary>
	public float unitHateDamagePercentRatio;
	
	/// <summary>
	/// 出生主城位置ID
	/// </summary>
	public int bornTownPosID;
	
	/// <summary>
	/// 匹配成功后最长等待确认时间(s)
	/// </summary>
	public int matchWaitTime;
	
	/// <summary>
	/// 场景AOI灯塔尺寸
	/// </summary>
	public float aoiTowerSize;
	
	/// <summary>
	/// aoi可视单位上限
	/// </summary>
	public int aoiSeeMax;
	
	/// <summary>
	/// 拾取范围半径(米)
	/// </summary>
	public float pickUpRadius;
	
	/// <summary>
	/// 自增属性计算间隔(ms)
	/// </summary>
	public int increaseAttributeDelay;
	
	/// <summary>
	/// 场景AOI灯塔延长尺寸(过渡区为2倍 该值)
	/// </summary>
	public float aoiTowerExpandSize;
	
	/// <summary>
	/// 摄像机最近距离(与目标距离)
	/// </summary>
	public float cameraMinDistance;
	
	/// <summary>
	/// 摄像机最长距离(与目标距离)
	/// </summary>
	public float cameraMaxDistance;
	
	/// <summary>
	/// 摄像机2.5D视角(角度)
	/// </summary>
	public float camera25DAngle;
	
	/// <summary>
	/// 摄像机最小视角(角度)
	/// </summary>
	public float cameraMinAxisXAngle;
	
	/// <summary>
	/// 摄像机大小视角(角度)
	/// </summary>
	public float cameraMaxAxisXAngle;
	
	/// <summary>
	/// 摄像机缓动时间(s)
	/// </summary>
	public float cameraTweenTime;
	
	/// <summary>
	/// 摄像机鼠标滚轮缩放速度
	/// </summary>
	public float cameraWheelSpeed;
	
	/// <summary>
	/// 摄像机默认距离
	/// </summary>
	public float cameraDefaultDistance;
	
	/// <summary>
	/// 摄像机X轴旋转速度
	/// </summary>
	public float cameraRotateSpeedX;
	
	/// <summary>
	/// 摄像机Y轴旋转速度
	/// </summary>
	public float cameraRotateSpeedY;
	
	/// <summary>
	/// 摄像机触摸缩放速度
	/// </summary>
	public float cameraScaleSpeed;
	
	/// <summary>
	/// 等级上限
	/// </summary>
	public int levelMax;
	
	/// <summary>
	/// 主背包格子数(初始)
	/// </summary>
	public int mainBagGridNum;
	
	/// <summary>
	/// 邮件每页显示数目
	/// </summary>
	public int mailPageEachShowNum;
	
	/// <summary>
	/// 邮件最多保存数目
	/// </summary>
	public int mailSaveMaxNum;
	
	/// <summary>
	/// 邮件最长保存时间(天)
	/// </summary>
	public int mailSaveMaxTime;
	
	/// <summary>
	/// 玩家发送的邮件ID
	/// </summary>
	public int playerMailID;
	
	/// <summary>
	/// 任务可视等级差
	/// </summary>
	public int questCanSeeLevelD;
	
	/// <summary>
	/// 好友功能启用双向好友(否则单向)
	/// </summary>
	public bool useOvonicFriend;
	
	/// <summary>
	/// 好友上限数目(0为无上限)
	/// </summary>
	public int friendMaxNum;
	
	/// <summary>
	/// 任务配置变更版本号
	/// </summary>
	public int questConfigChangeVersion;
	
	/// <summary>
	/// 好友黑名单上限数目(0为无上限)
	/// </summary>
	public int friendBlackListMaxNum;
	
	/// <summary>
	/// 申请添加好友上限数目(0为无上限)
	/// </summary>
	public int applyAddFriendMaxNum;
	
	/// <summary>
	/// 好友申请最长保存时间(天)
	/// </summary>
	public int friendApplySaveMaxTime;
	
	/// <summary>
	/// 工会的玩家群id(<=0则为无工会)
	/// </summary>
	public int unionRoleGroupID;
	
	/// <summary>
	/// 组队的玩家群id(<=0则为无组队功能)
	/// </summary>
	public int teamRoleGroupID;
	
	/// <summary>
	/// 组队共享半径(米)(0为无限)
	/// </summary>
	public float teamShareRadius;
	
	/// <summary>
	/// 客户端随机种子数目
	/// </summary>
	public int clientRandomSeedNum;
	
	/// <summary>
	/// 伤害值是否使用实际伤害值
	/// </summary>
	public bool damageValueUseRealDamage;
	
	/// <summary>
	/// 宠物同一id是否唯一
	/// </summary>
	public bool isPetUnique;
	
	/// <summary>
	/// 宠物是否需要装备功能
	/// </summary>
	public bool isPetNeedEquip;
	
	/// <summary>
	/// 读取字节流(简版)
	/// </summary>
	protected override void toReadBytesSimple(BytesReadStream stream)
	{
		this.ownPlayerNum=stream.readInt();
		
		this.playerNameLength=stream.readInt();
		
		this.isNameUseAreaIDAsFront=stream.readBoolean();
		
		this.canPlayerNameRepeat=stream.readBoolean();
		
		this.clientOfflineWorkTimeChangeDailyNum=stream.readInt();
		
		this.showNetDelayMinTime=stream.readInt();
		
		this.showNetDelayMaxTime=stream.readInt();
		
		this.activationCodeLength=stream.readInt();
		
		this.activationCodeUseBatch=stream.readBoolean();
		
		this.infoLogKeepTime=stream.readInt();
		
		this.infoLogKeepNum=stream.readInt();
		
		this.clientRandomSeedNum=stream.readInt();
		
		this.pageToolShowCD=stream.readInt();
		
		this.bigFloatWei=stream.readInt();
		
		this.posSendScale=stream.readFloat();
		
		this.directionSendScale=stream.readFloat();
		
		this.keepCurrentPercentAtMaxChange=stream.readBoolean();
		
		this.unitTurnXYSumMin=stream.readFloat();
		
		this.unitMovePosMaxDeviation=stream.readFloat();
		
		this.distanceCheckDeviation=stream.readFloat();
		
		this.moveSpeedMin=stream.readInt();
		
		this.moveSpeedMax=stream.readInt();
		
		this.attackSpeedMin=stream.readInt();
		
		this.attackSpeedMax=stream.readInt();
		
		this.castSpeedMin=stream.readInt();
		
		this.castSpeedMax=stream.readInt();
		
		this.useMoveSpeedRatio=stream.readFloat();
		
		this.hitRateArg0=stream.readFloat();
		
		this.critArg0=stream.readFloat();
		
		this.critDamageBaseRatio=stream.readFloat();
		
		this.bulletMaxLastTime=stream.readInt();
		
		this.sceneKeepTime=stream.readInt();
		
		this.attackScopeBackLength=stream.readFloat();
		
		this.attackScopeDefaultHeight=stream.readFloat();
		
		this.defaultShowFps=stream.readFloat();
		
		this.frameSyncCacheFrames=stream.readInt();
		
		this.wanderWaitTimeMin=stream.readInt();
		
		this.wanderWaitTimeMax=stream.readInt();
		
		this.wanderMoveRadius=stream.readFloat();
		
		this.preventNetDelayTime=stream.readInt();
		
		this.increaseAttributeDelay=stream.readInt();
		
		this.clientMoveSendMinDelay=stream.readInt();
		
		this.moveDirSendDelay=stream.readInt();
		
		this.moveDirForecastTime=stream.readInt();
		
		this.moveDirForecastMinDistance=stream.readFloat();
		
		this.mapBlockSize=stream.readFloat();
		
		this.mapSamplePositionRadius=stream.readFloat();
		
		this.monsterBackAddHPPercent=stream.readInt();
		
		this.ringLightBuffRefreshTime=stream.readInt();
		
		this.ringLightBuffLastTime=stream.readInt();
		
		this.fightStateOnceLastTime=stream.readInt();
		
		this.wakeUpCompanionDelayTime=stream.readInt();
		
		this.damageValueUseRealDamage=stream.readBoolean();
		
		this.unitBeAttackDelay=stream.readInt();
		
		this.unitHateDamagePercentRatio=stream.readFloat();
		
		this.unitSwitchHateCost=stream.readFloat();
		
		this.unitSwitchDistanceCost=stream.readFloat();
		
		this.unitSwitchBaseDistance=stream.readFloat();
		
		this.unitSwitchFixedCost=stream.readFloat();
		
		this.sceneLineNum=stream.readInt();
		
		this.sceneLinePlayerLimitNum=stream.readInt();
		
		this.bornTownID=stream.readInt();
		
		this.bornTownPosID=stream.readInt();
		
		this.matchWaitTime=stream.readInt();
		
		this.aoiTowerSize=stream.readFloat();
		
		this.aoiTowerExpandSize=stream.readFloat();
		
		this.aoiSeeMax=stream.readInt();
		
		this.pickUpRadius=stream.readFloat();
		
		this.cameraMinDistance=stream.readFloat();
		
		this.cameraMaxDistance=stream.readFloat();
		
		this.camera25DAngle=stream.readFloat();
		
		this.cameraMinAxisXAngle=stream.readFloat();
		
		this.cameraMaxAxisXAngle=stream.readFloat();
		
		this.cameraTweenTime=stream.readFloat();
		
		this.cameraWheelSpeed=stream.readFloat();
		
		this.cameraDefaultDistance=stream.readFloat();
		
		this.cameraRotateSpeedX=stream.readFloat();
		
		this.cameraRotateSpeedY=stream.readFloat();
		
		this.cameraScaleSpeed=stream.readFloat();
		
		this.levelMax=stream.readInt();
		
		this.mainBagGridNum=stream.readInt();
		
		this.mailPageEachShowNum=stream.readInt();
		
		this.mailSaveMaxNum=stream.readInt();
		
		this.mailSaveMaxTime=stream.readInt();
		
		this.playerMailID=stream.readInt();
		
		this.questCanSeeLevelD=stream.readInt();
		
		this.questConfigChangeVersion=stream.readInt();
		
		this.useOvonicFriend=stream.readBoolean();
		
		this.friendMaxNum=stream.readInt();
		
		this.friendBlackListMaxNum=stream.readInt();
		
		this.applyAddFriendMaxNum=stream.readInt();
		
		this.friendApplySaveMaxTime=stream.readInt();
		
		this.unionRoleGroupID=stream.readInt();
		
		this.teamRoleGroupID=stream.readInt();
		
		this.teamShareRadius=stream.readFloat();
		
		this.isPetUnique=stream.readBoolean();
		
		this.isPetNeedEquip=stream.readBoolean();
		
	}
	
}
